/* ---------- 772 entries ---------- */
const vocab = [
  { no: 1,  chinese: '啊',      pinyin: 'a',        english: 'auxiliary word' },
  { no: 2,  chinese: '爱情',    pinyin: 'àiqíng',   english: 'Love' },
  { no: 3,  chinese: '爱人',    pinyin: 'ài rén',   english: 'lover' },
  { no: 4,  chinese: '安静',    pinyin: 'ānjìng',   english: 'Be quiet' },
  { no: 5,  chinese: '安全',    pinyin: 'ānquán',   english: 'security' },
  { no: 6,  chinese: '白色',    pinyin: 'bái sè',   english: 'white' },
  { no: 7,  chinese: '班长',    pinyin: 'bān zhǎng',english: 'monitor; squad leader' },
  { no: 8,  chinese: '办',      pinyin: 'bàn',      english: 'do' },
  { no: 9,  chinese: '办法',    pinyin: 'bànfǎ',    english: 'Way' },
  { no: 10, chinese: '办公室',  pinyin: 'bàngōngshì',english: 'Office' },
  { no: 11, chinese: '半夜',    pinyin: 'bàn yè',     english: 'midnight' },
  { no: 12, chinese: '帮助',    pinyin: 'bāngzhù',    english: 'Help' },
  { no: 13, chinese: '饱',      pinyin: 'bǎo',        english: 'full' },
  { no: 14, chinese: '报名',    pinyin: 'bàomíng',    english: 'sign up' },
  { no: 15, chinese: '报纸',    pinyin: 'bàozhǐ',     english: 'Newspaper' },
  { no: 16, chinese: '北方',    pinyin: 'běifāng',    english: 'north' },
  { no: 17, chinese: '背（动）', pinyin: 'bēi',       english: 'carry on the back; shoulder' },
  { no: 18, chinese: '比如',    pinyin: 'bǐrú',       english: 'such as' },
  { no: 19, chinese: '比如说',  pinyin: 'bǐ rú shuō', english: 'for example' },
  { no: 20, chinese: '笔',      pinyin: 'bǐ',         english: 'pen' },
  { no: 21, chinese: '笔记',      pinyin: 'bǐ jì',         english: 'note; notes' },
  { no: 22, chinese: '笔记本',    pinyin: 'bǐjìběn',       english: 'Notebook' },
  { no: 23, chinese: '必须',      pinyin: 'bìxū',          english: 'Must' },
  { no: 24, chinese: '边',        pinyin: 'biān',          english: 'side' },
  { no: 25, chinese: '变',        pinyin: 'biàn',          english: 'change' },
  { no: 26, chinese: '变成',      pinyin: 'biàn chéng',    english: 'become; change into' },
  { no: 27, chinese: '遍',        pinyin: 'biàn',          english: 'Times' },
  { no: 28, chinese: '表',        pinyin: 'biǎo',          english: 'watch' },
  { no: 29, chinese: '表示',      pinyin: 'biǎoshì',       english: 'Express' },
  { no: 30, chinese: '不错',      pinyin: 'bú cuò',        english: 'not bad; pretty good' },
  { no: 31, chinese: '不但',      pinyin: 'bú dàn',        english: 'not only' },
  { no: 32, chinese: '不够',      pinyin: 'bú gòu',        english: 'not enough' },
  { no: 33, chinese: '不过',      pinyin: 'búguò',         english: 'However' },
  { no: 34, chinese: '不太',      pinyin: 'bú tài',        english: 'not too; not very much' },
  { no: 35, chinese: '不要',      pinyin: 'bú yào',        english: 'don’t' },
  { no: 36, chinese: '不好意思',  pinyin: 'bù hǎo yì sī',  english: 'sorry; feel embarrassed' },
  { no: 37, chinese: '不久',      pinyin: 'bù jiǔ',        english: 'soon' },
  { no: 38, chinese: '不满',      pinyin: 'bù mǎn',        english: 'dissatisfied' },
  { no: 39, chinese: '不如',      pinyin: 'bùrú',          english: 'not as good as' },
  { no: 40, chinese: '不少',      pinyin: 'bù shǎo',       english: 'not a few; a lot' },
  { no: 41, chinese: '不同',      pinyin: 'bù tóng',       english: 'different' },
  { no: 42, chinese: '不行',      pinyin: 'bù xíng',       english: 'no way; be out of the question' },
  { no: 43, chinese: '不一定',    pinyin: 'bù yī dìng',    english: 'not necessarily; uncertain' },
  { no: 44, chinese: '不一会儿',  pinyin: 'bù yī huìr',    english: 'in a moment; soon' },
  { no: 45, chinese: '部分',      pinyin: 'bùfen',         english: 'Part' },
  { no: 46, chinese: '才（副）',  pinyin: 'cái',           english: 'only; just' },
  { no: 47, chinese: '菜单',      pinyin: 'càidān',        english: 'menu' },
  { no: 48, chinese: '参观',      pinyin: 'cānguān',       english: 'visit' },
  { no: 49, chinese: '参加',      pinyin: 'cānjiā',        english: 'participate in' },
  { no: 50, chinese: '草',        pinyin: 'cǎo',           english: 'grass' },
  { no: 51, chinese: '草地',      pinyin: 'cǎo dì',        english: 'grass; lawn' },
  { no: 52, chinese: '层',        pinyin: 'céng',          english: 'layer' },
  { no: 53, chinese: '查',        pinyin: 'chá',           english: 'search; check' },
  { no: 54, chinese: '差不多',    pinyin: 'chàbuduō',      english: 'Almost' },
  { no: 55, chinese: '长',        pinyin: 'cháng',         english: 'long' },
  { no: 56, chinese: '常见',      pinyin: 'cháng jiàn',    english: 'common' },
  { no: 57, chinese: '常用',      pinyin: 'cháng yòng',    english: 'in common use' },
  { no: 58, chinese: '场',        pinyin: 'chǎng',         english: 'site' },
  { no: 59, chinese: '超过',      pinyin: 'chāoguò',       english: 'Exceed' },
  { no: 60, chinese: '超市',      pinyin: 'chāoshì',       english: 'Supermarket' },
  { no: 61, chinese: '车辆',      pinyin: 'chē liàng',     english: 'car; vehicle' },
  { no: 62, chinese: '称¹（动）', pinyin: 'chēng',         english: 'call; say' },
  { no: 63, chinese: '成（动）',  pinyin: 'chéng',         english: 'become; finish' },
  { no: 64, chinese: '成绩',      pinyin: 'chéngjì',       english: 'achievement' },
  { no: 65, chinese: '成为',      pinyin: 'chéngwéi',      english: 'Become' },
  { no: 66, chinese: '重复',      pinyin: 'chóngfù',       english: 'repeat' },
  { no: 67, chinese: '重新',      pinyin: 'chóngxīn',      english: 'again' },
  { no: 68, chinese: '出发',      pinyin: 'chūfā',         english: 'Set out' },
  { no: 69, chinese: '出国',      pinyin: 'chū guó',       english: 'go abroad' },
  { no: 70, chinese: '出口（名）', pinyin: 'chū kǒu',       english: 'export' },
  { no: 71, chinese: '出门',      pinyin: 'chū mén',       english: 'go out' },
  { no: 72, chinese: '出生',      pinyin: 'chūshēng',      english: 'Birth' },
  { no: 73, chinese: '出现',      pinyin: 'chūxiàn',       english: 'Appear' },
  { no: 74, chinese: '出院',      pinyin: 'chū yuàn',      english: 'discharged; leave hospital' },
  { no: 75, chinese: '出租',      pinyin: 'chū zū',        english: 'rent' },
  { no: 76, chinese: '出租车',    pinyin: 'chūzūchē',       english: 'Taxi' },
  { no: 77, chinese: '船',        pinyin: 'chuán',         english: 'ship' },
  { no: 78, chinese: '吹',        pinyin: 'chuī',          english: 'blow' },
  { no: 79, chinese: '春节',      pinyin: 'chūn jié',       english: 'Spring Festival; Chinese New Year' },
  { no: 80, chinese: '春天',      pinyin: 'chūn tiān',      english: 'spring' },
  { no: 81, chinese: '词',        pinyin: 'cí',            english: 'word' },
  { no: 82, chinese: '词典',      pinyin: 'cídiǎn',        english: 'Dictionary' },
  { no: 83, chinese: '词语',      pinyin: 'cíyǔ',          english: 'terms' },
  { no: 84, chinese: '从小',      pinyin: 'cóng xiǎo',     english: 'from childhood' },
  { no: 85, chinese: '答应',      pinyin: 'dāying',        english: 'promise' },
  { no: 86, chinese: '打工',      pinyin: 'dǎgōng',        english: 'Work' },
  { no: 87, chinese: '打算',      pinyin: 'dǎsuàn',        english: 'Plan' },
  { no: 88, chinese: '打印',      pinyin: 'dǎyìn',         english: 'Print' },
  { no: 89, chinese: '大部分',    pinyin: 'dà bù fèn',     english: 'most' },
  { no: 90, chinese: '大大',      pinyin: 'dà dà',         english: 'greatly; enormously' },
  { no: 91, chinese: '大多数',    pinyin: 'dà duō shù',    english: 'most; great majority' },
  { no: 92, chinese: '大海',      pinyin: 'dà hǎi',        english: 'sea' },
  { no: 93, chinese: '大家',      pinyin: 'dàjiā',         english: 'everybody' },
  { no: 94, chinese: '大量',      pinyin: 'dà liàng',      english: 'a lot of; lots of' },
  { no: 95, chinese: '大门',      pinyin: 'dà mén',        english: 'door; gate' },
  { no: 96, chinese: '大人',      pinyin: 'dà rén',        english: 'adult' },
  { no: 97, chinese: '大声',      pinyin: 'dà shēng',      english: 'loud' },
  { no: 98, chinese: '大小',      pinyin: 'dà xiǎo',       english: 'size' },
  { no: 99, chinese: '大衣',      pinyin: 'dà yī',         english: 'overcoat' },
  { no: 100, chinese: '大自然',    pinyin: 'dà zì rán',      english: 'nature' },
  { no: 101, chinese: '带',        pinyin: 'dài',            english: 'belt' },
  { no: 102, chinese: '带来',      pinyin: 'dài lái',        english: 'bring' },
  { no: 103, chinese: '单位',      pinyin: 'dānwèi',         english: 'Company' },
  { no: 104, chinese: '但',        pinyin: 'dàn',            english: 'but; however' },
  { no: 105, chinese: '但是',      pinyin: 'dàn shì',        english: 'but; however' },
  { no: 106, chinese: '蛋',        pinyin: 'dàn',            english: 'egg' },
  { no: 107, chinese: '当',        pinyin: 'dāng',           english: 'When' },
  { no: 108, chinese: '当时',      pinyin: 'dāngshí',        english: 'at that time' },
  { no: 109, chinese: '倒',        pinyin: 'dǎo',            english: 'fall, topple, fail' },
  { no: 110, chinese: '到处',      pinyin: 'dàochù',         english: 'everywhere' },
  { no: 111, chinese: '倒',        pinyin: 'dào',            english: 'inverted' },
  { no: 112, chinese: '道',        pinyin: 'dào',            english: 'road; way; path' },
  { no: 113, chinese: '道理',      pinyin: 'dàolǐ',          english: 'truth' },
  { no: 114, chinese: '道路',      pinyin: 'dào lù',         english: 'road; way; path' },
  { no: 115, chinese: '得',        pinyin: 'dé',             english: 'get' },
  { no: 116, chinese: '得出',      pinyin: 'dé chū',         english: 'obtain results; reach conclusion' },
  { no: 117, chinese: '的话',      pinyin: 'de huà',         english: 'if' },
  { no: 118, chinese: '得',        pinyin: 'de',             english: 'auxiliary verb' },
  { no: 119, chinese: '灯',        pinyin: 'dēng',           english: 'lamp' },
  { no: 120, chinese: '等（助、名）', pinyin: 'děng',         english: 'etc.; and so on' },
  { no: 121, chinese: '等到',      pinyin: 'děng dào',       english: 'wait until; by the time' },
  { no: 122, chinese: '等于',      pinyin: 'děngyú',         english: 'Be equal to' },
  { no: 123, chinese: '低',        pinyin: 'dī',             english: 'low' },
  { no: 124, chinese: '地球',      pinyin: 'dìqiú',          english: 'earth' },
  { no: 125, chinese: '地铁',      pinyin: 'dìtiě',          english: 'metro' },
  { no: 126, chinese: '地铁站',    pinyin: 'dì tiě zhàn',    english: 'subway station' },
  { no: 127, chinese: '点头',      pinyin: 'diǎn tóu',       english: 'nod' },
  { no: 128, chinese: '店',        pinyin: 'diàn',           english: 'shop; store' },
  { no: 129, chinese: '掉',        pinyin: 'diào',           english: 'fall' },
  { no: 130, chinese: '东北',      pinyin: 'dōng běi',       english: 'northeast' },
  { no: 131, chinese: '东方',      pinyin: 'dōng fāng',      english: 'east' },
  { no: 132, chinese: '东南',      pinyin: 'dōng nán',       english: 'southeast' },
  { no: 133, chinese: '冬天',      pinyin: 'dōng tiān',      english: 'winter' },
  { no: 134, chinese: '懂',        pinyin: 'dǒng',            english: 'understand' },
  { no: 135, chinese: '懂得',      pinyin: 'dǒng de',         english: 'know; understand; comprehend' },
  { no: 136, chinese: '动物',      pinyin: 'dòngwù',          english: 'Animal' },
  { no: 137, chinese: '动物园',    pinyin: 'dòng wù yuán',    english: 'zoo' },
  { no: 138, chinese: '读音',      pinyin: 'dú yīn',          english: 'pronunciation' },
  { no: 139, chinese: '度',        pinyin: 'dù',              english: 'degree; limit' },
  { no: 140, chinese: '短',        pinyin: 'duǎn',            english: 'short' },
  { no: 141, chinese: '短信',      pinyin: 'duǎnxìn',         english: 'message' },
  { no: 142, chinese: '段',        pinyin: 'duàn',            english: 'paragraph' },
  { no: 143, chinese: '队',        pinyin: 'duì',             english: 'team' },
  { no: 144, chinese: '队长',      pinyin: 'duì zhǎng',       english: 'team leader; captain' },
  { no: 145, chinese: '对（介、动）', pinyin: 'duì',           english: 'to; at; face; be opposite; answer' },
  { no: 146, chinese: '对话',      pinyin: 'duìhuà',          english: 'dialogue' },
  { no: 147, chinese: '对面',      pinyin: 'duìmiàn',         english: 'Opposite side' },
  { no: 148, chinese: '多（副）',  pinyin: 'duō',             english: 'much more; far more' },
  { no: 149, chinese: '多久',      pinyin: 'duō jiǔ',         english: 'how long' },
  { no: 150, chinese: '多么',      pinyin: 'duōme',           english: 'what' },
  { no: 151, chinese: '多数',      pinyin: 'duō shù',         english: 'most; majority' },
  { no: 152, chinese: '多云',      pinyin: 'duō yún',         english: 'cloudy' },
  { no: 153, chinese: '而且',      pinyin: 'ér qiě',          english: 'and' },
  { no: 154, chinese: '发',        pinyin: 'fā',              english: 'send out' },
  { no: 155, chinese: '发现',      pinyin: 'fāxiàn',          english: 'find' },
  { no: 156, chinese: '饭馆',      pinyin: 'fàn guǎn',        english: 'restaurant' },
  { no: 157, chinese: '方便',      pinyin: 'fāngbiàn',        english: 'convenient' },
  { no: 158, chinese: '方便面',    pinyin: 'fāng biàn miàn',  english: 'Instant noodles' },
  { no: 159, chinese: '方法',      pinyin: 'fāngfǎ',          english: 'Method' },
  { no: 160, chinese: '方面',      pinyin: 'fāngmiàn',        english: 'Aspect' },
  { no: 161, chinese: '方向',      pinyin: 'fāngxiàng',       english: 'direction' },
  { no: 162, chinese: '放下',      pinyin: 'fàng xià',        english: 'put down; lay down; drop' },
  { no: 163, chinese: '放心',      pinyin: 'fàngxīn',         english: 'Don’t worry' },
  { no: 164, chinese: '分（动）',  pinyin: 'fēn',             english: 'divide; part; distribute' },
  { no: 165, chinese: '分开',      pinyin: 'fēn kāi',         english: 'separate; part' },
  { no: 166, chinese: '分数',      pinyin: 'fēn shù',         english: 'score; mark; fraction' },
  { no: 167, chinese: '分钟',      pinyin: 'fēnzhōng',        english: 'Minute' },
  { no: 168, chinese: '份',        pinyin: 'fèn',             english: 'share' },
  { no: 169, chinese: '封（量）',  pinyin: 'fēng',            english: '(measure word)' },
  { no: 170, chinese: '服务',      pinyin: 'fú wù',           english: 'service' },
  { no: 171, chinese: '复习',      pinyin: 'fùxí',            english: 'Review' },
  { no: 172, chinese: '该（动）',  pinyin: 'gāi',             english: 'deserve; should; owe' },
  { no: 173, chinese: '改',        pinyin: 'gǎi',             english: 'change; correct; revise; switch over' },
  { no: 174, chinese: '改变',      pinyin: 'gǎibiàn',         english: 'change' },
  { no: 175, chinese: '干杯',      pinyin: 'gānbēi',          english: 'Cheers!' },
  { no: 176, chinese: '感到',      pinyin: 'gǎn dào',         english: 'feel; sense' },
  { no: 177, chinese: '感动',      pinyin: 'gǎndòng',         english: 'Be moved' },
  { no: 178, chinese: '感觉',      pinyin: 'gǎnjué',          english: 'feel' },
  { no: 179, chinese: '感谢',      pinyin: 'gǎnxiè',          english: 'Thank' },
  { no: 180, chinese: '干活儿',    pinyin: 'gànhuór',         english: 'work on a job' },
  { no: 181, chinese: '刚',        pinyin: 'gāng',            english: 'just' },
  { no: 182, chinese: '刚才',      pinyin: 'gāngcái',         english: 'just' },
  { no: 183, chinese: '刚刚',      pinyin: 'gāng gāng',       english: 'just; only; just a moment ago' },
  { no: 184, chinese: '高级',      pinyin: 'gāojí',           english: 'senior' },
  { no: 185, chinese: '高中',      pinyin: 'gāo zhōng',       english: 'senior high school' },
  { no: 186, chinese: '个子',      pinyin: 'gèzi',            english: 'Height' },
  { no: 187, chinese: '更',        pinyin: 'gèng',            english: 'more' },
  { no: 188, chinese: '公共汽车',  pinyin: 'gōnggòngqìchē',   english: 'Bus' },
  { no: 189, chinese: '公交车',    pinyin: 'gōng jiāo chē',   english: 'bus' },
  { no: 190, chinese: '公斤',      pinyin: 'gōngjīn',         english: 'Kg.' },
  { no: 191, chinese: '公里',      pinyin: 'gōnglǐ',          english: 'kilometre' },
  { no: 192, chinese: '公路',      pinyin: 'gōng lù',         english: 'highway; highroad' },
  { no: 193, chinese: '公平',      pinyin: 'gōngpíng',        english: 'fair' },
  { no: 194, chinese: '公司',      pinyin: 'gōngsī',          english: 'company' },
  { no: 195, chinese: '公园',      pinyin: 'gōngyuán',        english: 'Park' },
  { no: 196, chinese: '狗',        pinyin: 'gǒu',             english: 'Dog' },
  { no: 197, chinese: '够',        pinyin: 'gòu',             english: 'enough' },
  { no: 198, chinese: '故事',      pinyin: 'gùshi',           english: 'Story' },
  { no: 199, chinese: '故意',      pinyin: 'gùyì',            english: 'deliberately' },
  { no: 200, chinese: '顾客',      pinyin: 'gùkè',            english: 'customer' },
  { no: 201, chinese: '关机',      pinyin: 'guān jī',         english: 'shutdown' },
  { no: 202, chinese: '关心',      pinyin: 'guānxīn',         english: 'Care for' },
  { no: 203, chinese: '观点',      pinyin: 'guāndiǎn',        english: 'viewpoint' },
  { no: 204, chinese: '广场',      pinyin: 'guǎngchǎng',      english: 'square' },
  { no: 205, chinese: '广告',      pinyin: 'guǎnggào',        english: 'Advertisement' },
  { no: 206, chinese: '国际',      pinyin: 'guójì',           english: 'international' },
  { no: 207, chinese: '过来',      pinyin: 'guò lái',         english: 'come; come over' },
  { no: 208, chinese: '过年',      pinyin: 'guò nián',        english: 'celebrate the New Year' },
  { no: 209, chinese: '过去（动）', pinyin: 'guò qù',          english: 'go over; pass by' },
  { no: 210, chinese: '过',        pinyin: 'guò',             english: 'cross; pass; spend; live' },
  { no: 211, chinese: '海',        pinyin: 'hǎi',             english: 'sea' },
  { no: 212, chinese: '海边',      pinyin: 'hǎi biān',        english: 'seaside' },
  { no: 213, chinese: '喊',        pinyin: 'hǎn',             english: 'shout' },
  { no: 214, chinese: '好（副）',  pinyin: 'hǎo',             english: 'well; fine; okay' },
  { no: 215, chinese: '好处',      pinyin: 'hǎochu',          english: 'benefit' },
  { no: 216, chinese: '好多',      pinyin: 'hǎo duō',         english: 'many; a lot of' },
  { no: 217, chinese: '好久',      pinyin: 'hǎo jiǔ',         english: 'for a long time; long' },
  { no: 218, chinese: '好人',      pinyin: 'hǎo rén',         english: 'good person' },
  { no: 219, chinese: '好事',      pinyin: 'hǎo shì',         english: 'good deed; good thing' },
  { no: 220, chinese: '好像',      pinyin: 'hǎoxiàng',        english: 'Be like' },
  { no: 221, chinese: '合适',      pinyin: 'héshì',           english: 'appropriate' },
  { no: 222, chinese: '河',        pinyin: 'hé',              english: 'river' },
  { no: 223, chinese: '黑',        pinyin: 'hēi',             english: 'black' },
  { no: 224, chinese: '黑板',      pinyin: 'hēibǎn',          english: 'blackboard' },
  { no: 225, chinese: '黑色',      pinyin: 'hēi sè',          english: 'black' },
  { no: 226, chinese: '红',        pinyin: 'hóng',            english: 'red' },
  { no: 227, chinese: '红色',      pinyin: 'hóng sè',         english: 'red' },
  { no: 228, chinese: '后来',      pinyin: 'hòulái',          english: 'later' },
  { no: 229, chinese: '忽然',      pinyin: 'hūrán',           english: 'suddenly' },
  { no: 230, chinese: '湖',        pinyin: 'hú',              english: 'lake' },
  { no: 231, chinese: '护照',      pinyin: 'hùzhào',          english: 'passport' },
  { no: 232, chinese: '花（动）',  pinyin: 'huā',             english: 'spend; expend' },
  { no: 233, chinese: '花园',      pinyin: 'huā yuán',        english: 'garden' },
  { no: 234, chinese: '画',        pinyin: 'huà',             english: 'painting' },
  { no: 235, chinese: '画家',      pinyin: 'huà jiā',         english: 'painter; artist' },
  { no: 236, chinese: '画儿',      pinyin: 'huàr',            english: 'painting; drawing' },
  { no: 237, chinese: '坏处',      pinyin: 'huài chù',        english: 'disadvantage; harm' },
  { no: 238, chinese: '坏人',      pinyin: 'huài rén',        english: 'bad person' },
  { no: 239, chinese: '欢迎',      pinyin: 'huānyíng',        english: 'Welcome' },
  { no: 240, chinese: '换',        pinyin: 'huàn',            english: 'change' },
  { no: 241, chinese: '黄',        pinyin: 'huáng',           english: 'yellow' },
  { no: 242, chinese: '黄色',      pinyin: 'huáng sè',        english: 'yellow' },
  { no: 243, chinese: '回（量）',  pinyin: 'huí',             english: '(measure word)' },
  { no: 244, chinese: '回国',      pinyin: 'huí guó',         english: 'return home from abroad' },
  { no: 245, chinese: '会（名）',  pinyin: 'huì',             english: 'meeting; gathering; conference; union; party' },
  { no: 246, chinese: '活动',      pinyin: 'huódòng',         english: 'activity' },
  { no: 247, chinese: '或',        pinyin: 'huò',             english: 'or' },
  { no: 248, chinese: '或者',      pinyin: 'huòzhě',          english: 'perhaps' },
  { no: 249, chinese: '机会',      pinyin: 'jīhuì',           english: 'Opportunity' },
  { no: 250, chinese: '鸡',        pinyin: 'jī',              english: 'chicken' },
  { no: 251, chinese: '级',        pinyin: 'jí',              english: 'level; rank; grade; degree; step' },
  { no: 252, chinese: '急',        pinyin: 'jí',              english: 'fast; anxious; urgent; annoyed' },
  { no: 253, chinese: '计划',      pinyin: 'jìhuà',           english: 'plan' },
  { no: 254, chinese: '计算机',    pinyin: 'jì suàn jī',      english: 'computer' },
  { no: 255, chinese: '加',        pinyin: 'jiā',             english: 'add; increase; put in' },
  { no: 256, chinese: '加油',      pinyin: 'jiā yóu',         english: 'oil; refuel; make an all-out effort' },
  { no: 257, chinese: '家（科学家）', pinyin: 'jiā',          english: 'noun suffix (scientist)' },
  { no: 258, chinese: '家庭',      pinyin: 'jiātíng',         english: 'Family' },
  { no: 259, chinese: '家长',      pinyin: 'jiā zhǎng',       english: 'parent; the head of the family' },
  { no: 260, chinese: '假',        pinyin: 'jiǎ',             english: 'false' },
  { no: 261, chinese: '假期',      pinyin: 'jià qī',          english: 'holiday; vacation' },
  { no: 262, chinese: '检查',      pinyin: 'jiǎnchá',         english: 'inspect; check' },
  { no: 263, chinese: '见到',      pinyin: 'jiàn dào',        english: 'see' },
  { no: 264, chinese: '见过',      pinyin: 'jiàn guò',        english: 'seen; have seen' },
  { no: 265, chinese: '件',        pinyin: 'jiàn',            english: 'piece' },
  { no: 266, chinese: '健康',      pinyin: 'jiànkāng',        english: 'Healthy' },
  { no: 267, chinese: '讲',        pinyin: 'jiǎng',           english: 'speak' },
  { no: 268, chinese: '讲话',      pinyin: 'jiǎng huà',       english: 'speak; talk' },
  { no: 269, chinese: '交',        pinyin: 'jiāo',            english: 'hand over' },
  { no: 270, chinese: '交给',      pinyin: 'jiāo gěi',        english: 'hand over' },
  { no: 271, chinese: '交朋友',    pinyin: 'jiāo péng yǒu',   english: 'make friends' },
  { no: 272, chinese: '交通',      pinyin: 'jiāotōng',        english: 'traffic' },
  { no: 273, chinese: '角',        pinyin: 'jiǎo',            english: 'horn' },
  { no: 274, chinese: '角度',      pinyin: 'jiǎodù',          english: 'angle' },
  { no: 275, chinese: '饺子',      pinyin: 'jiǎozi',          english: 'Dumplings' },
  { no: 276, chinese: '脚',        pinyin: 'jiǎo',            english: 'foot' },
  { no: 277, chinese: '叫作',      pinyin: 'jiào zuò',        english: 'be called; be known as' },
  { no: 278, chinese: '教师',      pinyin: 'jiào shī',        english: 'teacher' },
  { no: 279, chinese: '教室',      pinyin: 'jiàoshì',         english: 'Classroom' },
  { no: 280, chinese: '教学',      pinyin: 'jiào xué',        english: 'teach' },
  { no: 281, chinese: '教育',      pinyin: 'jiàoyù',          english: 'education' },
  { no: 282, chinese: '接',        pinyin: 'jiē',             english: 'meet， pick' },
  { no: 283, chinese: '接到',      pinyin: 'jiē dào',         english: 'receive' },
  { no: 284, chinese: '接受',      pinyin: 'jiēshòu',         english: 'accept' },
  { no: 285, chinese: '接下来',    pinyin: 'jiē xià lái',     english: 'next' },
  { no: 286, chinese: '接着',      pinyin: 'jiēzhe',          english: 'Next' },
  { no: 287, chinese: '街',        pinyin: 'jiē',             english: 'street' },
  { no: 288, chinese: '节（名、量）', pinyin: 'jié',           english: 'festival; holiday; joint; (measure word)' },
  { no: 289, chinese: '节目',      pinyin: 'jiémù',           english: 'program' },
  { no: 290, chinese: '节日',      pinyin: 'jiérì',           english: 'festival' },
  { no: 291, chinese: '结果',      pinyin: 'jiéguǒ',          english: 'Result' },
  { no: 292, chinese: '借',        pinyin: 'jiè',             english: 'borrow' },
  { no: 293, chinese: '斤',        pinyin: 'jīn',             english: 'a unit of weight (=1/2 kilogram)' },
  { no: 294, chinese: '今后',      pinyin: 'jīn hòu',         english: 'from now on; in the future' },
  { no: 295, chinese: '进入',      pinyin: 'jìn rù',          english: 'enter; go in; join' },
  { no: 296, chinese: '进行',      pinyin: 'jìnxíng',         english: 'Conduct' },
  { no: 297, chinese: '近',        pinyin: 'jìn',             english: 'near' },
  { no: 298, chinese: '经常',      pinyin: 'jīngcháng',       english: 'Often' },
  { no: 299, chinese: '经过',      pinyin: 'jīngguò',         english: 'after, through' },
  { no: 300, chinese: '经理',      pinyin: 'jīnglǐ',          english: 'manager' },
  { no: 301, chinese: '酒', pinyin: 'jiǔ', english: 'alcohol; liqueur' },
  { no: 302, chinese: '酒店', pinyin: 'jiǔ diàn', english: 'hotel' },
  { no: 303, chinese: '就要', pinyin: 'jiù yào', english: 'be going to; be about to' },
  { no: 304, chinese: '举', pinyin: 'jǔ', english: 'lift' },
  { no: 305, chinese: '举手', pinyin: 'jǔ shǒu', english: "raise one's hand or hands" },
  { no: 306, chinese: '举行', pinyin: 'jǔxíng', english: 'hold' },
  { no: 307, chinese: '句', pinyin: 'jù', english: 'sentence' },
  { no: 308, chinese: '句子', pinyin: 'jùzi', english: 'sentence' },
  { no: 309, chinese: '卡', pinyin: 'kǎ', english: 'card' },
  { no: 310, chinese: '开机', pinyin: 'kāi jī', english: 'starting up' },
  { no: 311, chinese: '开心', pinyin: 'kāixīn', english: 'Happy' },
  { no: 312, chinese: '开学', pinyin: 'kāi xué', english: 'school opens; term begins' },
  { no: 313, chinese: '看法', pinyin: 'kànfǎ', english: 'view' },
  { no: 314, chinese: '考生', pinyin: 'kǎo shēng', english: 'examinee' },
  { no: 315, chinese: '靠', pinyin: 'kào', english: 'lean' },
  { no: 316, chinese: '科', pinyin: 'kē', english: 'subject; family; section' },
  { no: 317, chinese: '科学', pinyin: 'kēxué', english: 'science' },
  { no: 318, chinese: '可爱', pinyin: 'kě’ài', english: 'Lovely' },
  { no: 319, chinese: '可能', pinyin: 'kěnéng', english: 'Probably' },
  { no: 320, chinese: '可怕', pinyin: 'kěpà', english: 'dreadful' },
  { no: 321, chinese: '可是', pinyin: 'kěshì', english: 'however' },
  { no: 322, chinese: '可以', pinyin: 'kěyǐ', english: 'Sure' },
  { no: 323, chinese: '克', pinyin: 'kè', english: 'gram' },
  { no: 324, chinese: '刻（量）', pinyin: 'kè', english: 'a quarter (of an hour)' },
  { no: 325, chinese: '客人', pinyin: 'kèrén', english: 'Guest' },
  { no: 326, chinese: '课堂', pinyin: 'kè táng', english: 'classroom' },
  { no: 327, chinese: '空气', pinyin: 'kōngqì', english: 'atmosphere' },
  { no: 328, chinese: '哭', pinyin: 'kū', english: 'cry' },
  { no: 329, chinese: '快餐', pinyin: 'kuài cān', english: 'fast food' },
  { no: 330, chinese: '快点儿', pinyin: 'kuài diǎnr', english: 'hurry up' },
  { no: 331, chinese: '快乐', pinyin: 'kuàilè', english: 'happy' },
  { no: 332, chinese: '快要', pinyin: 'kuài yào', english: 'be about to; be going to' },
  { no: 333, chinese: '筷子', pinyin: 'kuàizi', english: 'chopsticks' },
  { no: 334, chinese: '拉', pinyin: 'lā', english: 'pull' },
  { no: 335, chinese: '来自', pinyin: 'láizì', english: 'Come from' },
  { no: 336, chinese: '蓝', pinyin: 'lán', english: 'blue' },
  { no: 337, chinese: '蓝色', pinyin: 'lán sè', english: 'blue' },
  { no: 338, chinese: '篮球', pinyin: 'lán qiú', english: 'basketball' },
  { no: 339, chinese: '老（副）', pinyin: 'lǎo', english: 'always; constantly' },
  { no: 340, chinese: '老（老王）', pinyin: 'lǎo （lǎo wáng）', english: 'noun prefix (Lao Wang)' },
  { no: 341, chinese: '老年', pinyin: 'lǎo nián', english: 'elderly' },
  { no: 342, chinese: '老朋友', pinyin: 'lǎo péng yǒu', english: 'old friend' },
  { no: 343, chinese: '老是', pinyin: 'lǎo shì', english: 'always; all times' },
  { no: 344, chinese: '离', pinyin: 'lí', english: 'leave' },
  { no: 345, chinese: '离开', pinyin: 'líkāi', english: 'leave' },
  { no: 346, chinese: '礼物', pinyin: 'lǐwù', english: 'gift' },
  { no: 347, chinese: '里头', pinyin: 'lǐ tou', english: 'inside' },
  { no: 348, chinese: '理想', pinyin: 'lǐxiǎng', english: 'ideal' },
  { no: 349, chinese: '例如', pinyin: 'lìrú', english: 'for example' },
  { no: 350, chinese: '例子', pinyin: 'lì zi', english: 'example' },
  { no: 351, chinese: '脸', pinyin: 'liǎn', english: 'face' },
  { no: 352, chinese: '练', pinyin: 'liàn', english: 'practice; train' },
  { no: 353, chinese: '练习', pinyin: 'liànxí', english: 'Practice' },
  { no: 354, chinese: '凉', pinyin: 'liáng', english: 'cool' },
  { no: 355, chinese: '凉快', pinyin: 'liángkuai', english: 'Pleasantly cool' },
  { no: 356, chinese: '两（量）', pinyin: 'liǎng', english: 'a unit of weight (=50 grams)' },
  { no: 357, chinese: '亮', pinyin: 'liàng', english: 'bright' },
  { no: 358, chinese: '辆', pinyin: 'liàng', english: 'Car (measure word)' },
  { no: 359, chinese: '零下', pinyin: 'líng xià', english: 'below zero' },
  { no: 360, chinese: '留', pinyin: 'liú', english: 'stay' },
  { no: 361, chinese: '留下', pinyin: 'liú xià', english: 'stay; remain' },
  { no: 362, chinese: '留学生', pinyin: 'liú xué shēng', english: 'student studying abroad; returned student' },
  { no: 363, chinese: '流', pinyin: 'liú', english: 'flow; spread' },
  { no: 364, chinese: '流利', pinyin: 'liúlì', english: 'fluent' },
  { no: 365, chinese: '流行', pinyin: 'liúxíng', english: 'Popular' },
  { no: 366, chinese: '路边', pinyin: 'lù biān', english: 'roadside; wayside' },
  { no: 367, chinese: '旅客', pinyin: 'lǚ kè', english: 'passenger; traveler' },
  { no: 368, chinese: '旅行', pinyin: 'lǚxíng', english: 'travel' },
  { no: 369, chinese: '旅游', pinyin: 'lǚyóu', english: 'Tourism' },
  { no: 370, chinese: '绿', pinyin: 'lǜ', english: 'green' },
  { no: 371, chinese: '绿色', pinyin: 'lǜ sè', english: 'green' },
  { no: 372, chinese: '卖', pinyin: 'mài', english: 'sell' },
  { no: 373, chinese: '满', pinyin: 'mǎn', english: 'full' },
  { no: 374, chinese: '满意', pinyin: 'mǎnyì', english: 'Satisfied' },
  { no: 375, chinese: '猫', pinyin: 'māo', english: 'cat' },
  { no: 376, chinese: '米（量）', pinyin: 'mǐ', english: 'meter' },
  { no: 377, chinese: '面¹（名、量）', pinyin: 'miàn ¹', english: '(measure word); side; aspect' },
  { no: 378, chinese: '面²（名）', pinyin: 'miàn ²', english: 'face; surface; outside; side; scale; flour' },
  { no: 379, chinese: '面前', pinyin: 'miàn qián', english: 'in front of; before' },
  { no: 380, chinese: '名', pinyin: 'míng', english: 'name' },
  { no: 381, chinese: '名称', pinyin: 'míng chēng', english: 'name; designation' },
  { no: 382, chinese: '名单', pinyin: 'míng dān', english: 'list' },
  { no: 383, chinese: '明星', pinyin: 'míngxīng', english: 'Star' },
  { no: 384, chinese: '目的', pinyin: 'mùdì', english: 'objective' },
  { no: 385, chinese: '拿出', pinyin: 'ná chū', english: 'take out' },
  { no: 386, chinese: '拿到', pinyin: 'ná dào', english: 'get' },
  { no: 387, chinese: '那（连）', pinyin: 'nà', english: 'then; in that case' },
  { no: 388, chinese: '那会儿', pinyin: 'nà huìr', english: 'at that time; then' },
  { no: 389, chinese: '那么', pinyin: 'nà me', english: 'like that; in that way' },
  { no: 390, chinese: '那时候｜那时', pinyin: 'nà shí hou ｜ nà shí', english: 'at that time' },
  { no: 391, chinese: '那样', pinyin: 'nà yàng', english: 'that kind; like that; such' },
  { no: 392, chinese: '南方', pinyin: 'nán fāng', english: 'south' },
  { no: 393, chinese: '难过', pinyin: 'nánguò', english: 'Sorry' },
  { no: 394, chinese: '难看', pinyin: 'nán kàn', english: 'ugly' },
  { no: 395, chinese: '难受', pinyin: 'nánshòu', english: 'Uncomfortable' },
  { no: 396, chinese: '难题', pinyin: 'nán tí', english: 'problem; difficult problem; puzzle' },
  { no: 397, chinese: '难听', pinyin: 'nán tīng', english: 'unpleasant to hear' },
  { no: 398, chinese: '能够', pinyin: 'néng gòu', english: 'be able to; can' },
  { no: 399, chinese: '年级', pinyin: 'niánjí', english: 'grade' },
  { no: 400, chinese: '年轻', pinyin: 'niánqīng', english: 'Young' },
  { no: 401, chinese: '鸟', pinyin: 'niǎo', english: 'bird' },
  { no: 402, chinese: '弄', pinyin: 'nòng', english: 'get, make' },
  { no: 403, chinese: '努力', pinyin: 'nǔlì', english: 'Strive' },
  { no: 404, chinese: '爬', pinyin: 'pá', english: 'climb; creep; scramble' },
  { no: 405, chinese: '爬山', pinyin: 'páshān', english: 'Mountain climbing' },
  { no: 406, chinese: '怕（动）', pinyin: 'pà', english: 'be afraid; fear; dread' },
  { no: 407, chinese: '排（名、量）', pinyin: 'pái', english: 'row; line' },
  { no: 408, chinese: '排队', pinyin: 'páiduì', english: 'queue; stand in a line' },
  { no: 409, chinese: '排球', pinyin: 'pái qiú', english: 'volleyball' },
  { no: 410, chinese: '碰', pinyin: 'pèng', english: 'touch, meet' },
  { no: 411, chinese: '碰到', pinyin: 'pèng dào', english: 'meet; run into; bump into' },
  { no: 412, chinese: '碰见', pinyin: 'pèng jiàn', english: 'meet; run into; bump into' },
  { no: 413, chinese: '篇', pinyin: 'piān', english: 'piece' },
  { no: 414, chinese: '便宜', pinyin: 'piányi', english: 'Cheap' },
  { no: 415, chinese: '片', pinyin: 'piàn', english: 'slice' },
  { no: 416, chinese: '漂亮', pinyin: 'piàoliang', english: 'Well done!； beautiful' },
  { no: 417, chinese: '平', pinyin: 'píng', english: 'flat' },
  { no: 418, chinese: '平安', pinyin: 'píng’ān', english: 'sound and safe' },
  { no: 419, chinese: '平常', pinyin: 'píngcháng', english: 'Usual' },
  { no: 420, chinese: '平等', pinyin: 'píngděng', english: 'equality' },
  { no: 421, chinese: '平时', pinyin: 'píngshí', english: 'peacetime' },
  { no: 422, chinese: '瓶', pinyin: 'píng', english: 'bottle' },
  { no: 423, chinese: '瓶子', pinyin: 'píngzi', english: 'Bottle' },
  { no: 424, chinese: '普通', pinyin: 'pǔ tōng', english: 'ordinary; general; average; common' },
  { no: 425, chinese: '普通话', pinyin: 'pǔtōnghuà', english: 'Mandarin' },
  { no: 426, chinese: '其他', pinyin: 'qítā', english: 'Other' },
  { no: 427, chinese: '其中', pinyin: 'qízhōng', english: 'among' },
  { no: 428, chinese: '骑', pinyin: 'qí', english: 'ride' },
  { no: 429, chinese: '骑车', pinyin: 'qí chē', english: 'cycle' },
  { no: 430, chinese: '起飞', pinyin: 'qǐfēi', english: 'take off' },
  { no: 431, chinese: '气', pinyin: 'qì', english: 'air; gas; breath' },
  { no: 432, chinese: '气温', pinyin: 'qì wēn', english: 'air temperature' },
  { no: 433, chinese: '千', pinyin: 'qiān', english: 'thousand' },
  { no: 434, chinese: '千克', pinyin: 'qiān kè', english: 'kilogram' },
  { no: 435, chinese: '前年', pinyin: 'qián nián', english: 'the year before last' },
  { no: 436, chinese: '墙', pinyin: 'qiáng', english: 'wall' },
  { no: 437, chinese: '青年', pinyin: 'qīng nián', english: 'youth; young' },
  { no: 438, chinese: '青少年', pinyin: 'qīngshàonián', english: 'Teenagers' },
  { no: 439, chinese: '轻', pinyin: 'qīng', english: 'light' },
  { no: 440, chinese: '清楚', pinyin: 'qīngchu', english: 'clear' },
  { no: 441, chinese: '晴', pinyin: 'qíng', english: 'Sunny' },
  { no: 442, chinese: '晴天', pinyin: 'qíng tiān', english: 'sunny day' },
  { no: 443, chinese: '请客', pinyin: 'qǐng kè', english: 'stand treat; entertain' },
  { no: 444, chinese: '请求', pinyin: 'qǐngqiú', english: 'request' },
  { no: 445, chinese: '秋天', pinyin: 'qiū tiān', english: 'fall; autumn' },
  { no: 446, chinese: '求', pinyin: 'qiú', english: 'request; beg; entreat; beseech' },
  { no: 447, chinese: '球场', pinyin: 'qiú chǎng', english: 'court; field' },
  { no: 448, chinese: '球队', pinyin: 'qiú duì', english: 'team' },
  { no: 449, chinese: '球鞋', pinyin: 'qiú xié', english: 'sneakers; gym shoes' },
  { no: 450, chinese: '取', pinyin: 'qǔ', english: 'take' },
  { no: 451, chinese: '取得', pinyin: 'qǔ dé', english: 'acquire; gain; obtain' },
  { no: 452, chinese: '全', pinyin: 'quán', english: 'whole; entire; complete' },
  { no: 453, chinese: '全部', pinyin: 'quánbù', english: 'whole' },
  { no: 454, chinese: '全国', pinyin: 'quán guó', english: 'nationwide; entire country' },
  { no: 455, chinese: '全家', pinyin: 'quán jiā', english: 'whole family' },
  { no: 456, chinese: '全年', pinyin: 'quán nián', english: 'annual; yearly' },
  { no: 457, chinese: '全身', pinyin: 'quán shēn', english: 'whole body' },
  { no: 458, chinese: '全体', pinyin: 'quán tǐ', english: 'all; entire; whole' },
  { no: 459, chinese: '然后', pinyin: 'ránhòu', english: 'Then' },
  { no: 460, chinese: '让', pinyin: 'ràng', english: 'Give Way' },
  { no: 461, chinese: '热情', pinyin: 'rèqíng', english: 'Enthusiasm' },
  { no: 462, chinese: '人口', pinyin: 'rénkǒu', english: 'population' },
  { no: 463, chinese: '人们', pinyin: 'rén men', english: 'people' },
  { no: 464, chinese: '人数', pinyin: 'rén shù', english: 'number of people' },
  { no: 465, chinese: '认为', pinyin: 'rènwéi', english: 'think' },
  { no: 466, chinese: '日报', pinyin: 'rì bào', english: 'daily, journal' },
  { no: 467, chinese: '日子', pinyin: 'rìzi', english: 'life, days' },
  { no: 468, chinese: '如果', pinyin: 'rúguǒ', english: 'If' },
  { no: 469, chinese: '入口', pinyin: 'rùkǒu', english: 'Entrance' },
  { no: 470, chinese: '商量', pinyin: 'shāngliang', english: 'discuss' },
  { no: 471, chinese: '商人', pinyin: 'shāng rén', english: 'businessman' },
  { no: 472, chinese: '上周', pinyin: 'shàng zhōu', english: 'last week' },
  { no: 473, chinese: '少数', pinyin: 'shǎo shù', english: 'small number; few; minority' },
  { no: 474, chinese: '少年', pinyin: 'shào nián', english: 'juvenile; young person' },
  { no: 475, chinese: '身边', pinyin: 'shēn biān', english: 'at [by] one’s side' },
  { no: 476, chinese: '什么样', pinyin: 'shén me yàng', english: 'what kind' },
  { no: 477, chinese: '生（动）', pinyin: 'shēng', english: 'give birth; be born' },
  { no: 478, chinese: '生词', pinyin: 'shēng cí', english: 'new word' },
  { no: 479, chinese: '生活', pinyin: 'shēnghuó', english: 'Life' },
  { no: 480, chinese: '声音', pinyin: 'shēngyīn', english: 'voice' },
  { no: 481, chinese: '省（名）', pinyin: 'shěng', english: 'province' },
  { no: 482, chinese: '省（动）', pinyin: 'shěng', english: 'economize; save; omit; leave out' },
  { no: 483, chinese: '十分', pinyin: 'shífēn', english: 'very' },
  { no: 484, chinese: '实际', pinyin: 'shíjì', english: 'Actual' },
  { no: 485, chinese: '实习', pinyin: 'shíxí', english: 'Internship' },
  { no: 486, chinese: '实现', pinyin: 'shíxiàn', english: 'Realization' },
  { no: 487, chinese: '实在', pinyin: 'shízài', english: 'real; indeed' },
  { no: 488, chinese: '实在', pinyin: 'shízai', english: 'done carefully' },
  { no: 489, chinese: '食物', pinyin: 'shíwù', english: 'food' },
  { no: 490, chinese: '使用', pinyin: 'shǐyòng', english: 'Use' },
  { no: 491, chinese: '市', pinyin: 'shì', english: 'city' },
  { no: 492, chinese: '市长', pinyin: 'shì zhǎng', english: 'mayor' },
  { no: 493, chinese: '事情', pinyin: 'shìqing', english: 'Thing' },
  { no: 494, chinese: '收', pinyin: 'shōu', english: 'collect' },
  { no: 495, chinese: '收到', pinyin: 'shōu dào', english: 'receive; obtain' },
  { no: 496, chinese: '收入', pinyin: 'shōurù', english: 'income' },
  { no: 497, chinese: '手表', pinyin: 'shǒubiǎo', english: 'Wrist Watch' },
  { no: 498, chinese: '受到', pinyin: 'shòudào', english: 'Suffer' },
  { no: 499, chinese: '舒服', pinyin: 'shūfu', english: 'comfortable' },
  { no: 500, chinese: '熟', pinyin: 'shú', english: 'ripe; cooked; familiar; skilled' },
  { no: 501, chinese: '数', pinyin: 'shǔ', english: 'to count' },
  { no: 502, chinese: '数字', pinyin: 'shùzì', english: 'number' },
  { no: 503, chinese: '水平', pinyin: 'shuǐpíng', english: 'level' },
  { no: 504, chinese: '顺利', pinyin: 'shùnlì', english: 'smoothly' },
  { no: 505, chinese: '说明', pinyin: 'shuōmíng', english: 'Explain' },
  { no: 506, chinese: '司机', pinyin: 'sījī', english: 'Driver' },
  { no: 507, chinese: '送到', pinyin: 'sòng dào', english: 'sent to (place)' },
  { no: 508, chinese: '送给', pinyin: 'sòng gěi', english: 'give to (somebody)' },
  { no: 509, chinese: '算', pinyin: 'suàn', english: 'count; calculate' },
  { no: 510, chinese: '虽然', pinyin: 'suī rán', english: 'although; though' },
  { no: 511, chinese: '随便', pinyin: 'suíbiàn', english: 'casual' },
  { no: 512, chinese: '随时', pinyin: 'suíshí', english: 'at any time' },
  { no: 513, chinese: '所以', pinyin: 'suǒ yǐ', english: 'so' },
  { no: 514, chinese: '所有', pinyin: 'suǒyǒu', english: 'All' },
  { no: 515, chinese: '它', pinyin: 'tā', english: 'it' },
  { no: 516, chinese: '它们', pinyin: 'tā men', english: 'they' },
  { no: 517, chinese: '太太', pinyin: 'tàitai', english: 'Ma’am' },
  { no: 518, chinese: '太阳', pinyin: 'tàiyáng', english: 'sun' },
  { no: 519, chinese: '态度', pinyin: 'tàidu', english: 'attitude' },
  { no: 520, chinese: '讨论', pinyin: 'tǎolùn', english: 'discuss' },
  { no: 521, chinese: '套', pinyin: 'tào', english: 'set' },
  { no: 522, chinese: '特别', pinyin: 'tèbié', english: 'Especially' },
  { no: 523, chinese: '特点', pinyin: 'tèdiǎn', english: 'Characteristic' },
  { no: 524, chinese: '疼', pinyin: 'téng', english: 'hurt' },
  { no: 525, chinese: '提', pinyin: 'tí', english: 'carry' },
  { no: 526, chinese: '提出', pinyin: 'tí chū', english: 'put forward; propose' },
  { no: 527, chinese: '提到', pinyin: 'tí dào', english: 'mention; refer to' },
  { no: 528, chinese: '提高', pinyin: 'tígāo', english: 'increase, promote' },
  { no: 529, chinese: '题', pinyin: 'tí', english: 'topic' },
  { no: 530, chinese: '体育', pinyin: 'tǐyù', english: 'Sports' },
  { no: 531, chinese: '体育场', pinyin: 'tǐ yù chǎng', english: 'stadium' },
  { no: 532, chinese: '体育馆', pinyin: 'tǐ yù guǎn', english: 'gymnasium' },
  { no: 533, chinese: '天上', pinyin: 'tiān shàng', english: 'the sky; heaven' },
  { no: 534, chinese: '条', pinyin: 'tiáo', english: 'strip' },
  { no: 535, chinese: '条件', pinyin: 'tiáojiàn', english: 'condition' },
  { no: 536, chinese: '听讲', pinyin: 'tīng jiǎng', english: 'attend a lecture' },
  { no: 537, chinese: '听说', pinyin: 'tīng shuō', english: 'be told; hear of' },
  { no: 538, chinese: '停', pinyin: 'tíng', english: 'Stop' },
  { no: 539, chinese: '停车', pinyin: 'tíng chē', english: 'park' },
  { no: 540, chinese: '停车场', pinyin: 'tíng chē chǎng', english: 'parking lot' },
  { no: 541, chinese: '挺（副）', pinyin: 'tǐng', english: 'very; quite' },
  { no: 542, chinese: '挺好', pinyin: 'tǐng hǎo', english: 'very good' },
  { no: 543, chinese: '通', pinyin: 'tōng', english: 'through; common; understand' },
  { no: 544, chinese: '通过', pinyin: 'tōngguò', english: 'adopt' },
  { no: 545, chinese: '通知', pinyin: 'tōngzhī', english: 'notice' },
  { no: 546, chinese: '同时', pinyin: 'tóngshí', english: 'meanwhile' },
  { no: 547, chinese: '同事', pinyin: 'tóngshì', english: 'Colleague' },
  { no: 548, chinese: '同样', pinyin: 'tóng yàng', english: 'same' },
  { no: 549, chinese: '头（名、量）', pinyin: 'tóu', english: 'head; measure word' },
  { no: 550, chinese: '头（里头）', pinyin: 'tóu', english: 'suffix (inside)' },
  { no: 551, chinese: '头发', pinyin: 'tóufa', english: 'Hair' },
  { no: 552, chinese: '图片', pinyin: 'tú piàn', english: 'picture; photograph' },
  { no: 553, chinese: '推', pinyin: 'tuī', english: 'push' },
  { no: 554, chinese: '腿', pinyin: 'tuǐ', english: 'leg' },
  { no: 555, chinese: '外地', pinyin: 'wài dì', english: 'other places; nonlocal' },
  { no: 556, chinese: '外卖', pinyin: 'wài mài', english: 'takeaway; take out' },
  { no: 557, chinese: '完', pinyin: 'wán', english: 'finish' },
  { no: 558, chinese: '完成', pinyin: 'wánchéng', english: 'complete' },
  { no: 559, chinese: '完全', pinyin: 'wánquán', english: 'completely' },
  { no: 560, chinese: '晚安', pinyin: 'wǎn ān', english: 'good night' },
  { no: 561, chinese: '晚报', pinyin: 'wǎn bào', english: 'evening paper' },
  { no: 562, chinese: '晚餐', pinyin: 'wǎn cān', english: 'dinner; supper' },
  { no: 563, chinese: '晚会', pinyin: 'wǎn huì', english: 'evening party' },
  { no: 564, chinese: '碗', pinyin: 'wǎn', english: 'bowl' },
  { no: 565, chinese: '万', pinyin: 'wàn', english: 'ten thousand' },
  { no: 566, chinese: '网', pinyin: 'wǎng', english: 'net; network' },
  { no: 567, chinese: '网球', pinyin: 'wǎngqiú', english: 'Tennis' },
  { no: 568, chinese: '网站', pinyin: 'wǎngzhàn', english: 'website' },
  { no: 569, chinese: '往', pinyin: 'wǎng', english: 'to' },
  { no: 570, chinese: '为', pinyin: 'wèi', english: 'by' },
  { no: 571, chinese: '为什么', pinyin: 'wèishénme', english: 'Why' },
  { no: 572, chinese: '位', pinyin: 'wèi', english: 'person (measure word)' },
  { no: 573, chinese: '味道', pinyin: 'wèidào', english: 'taste' },
  { no: 574, chinese: '喂（叹）', pinyin: 'wèi', english: 'hello; hey' },
  { no: 575, chinese: '温度', pinyin: 'wēndù', english: 'temperature' },
  { no: 576, chinese: '闻', pinyin: 'wén', english: 'smell' },
  { no: 577, chinese: '问路', pinyin: 'wèn lù', english: 'ask for directions' },
  { no: 578, chinese: '问题', pinyin: 'wèntí', english: 'problem' },
  { no: 579, chinese: '午餐', pinyin: 'wǔ cān', english: 'lunch' },
  { no: 580, chinese: '午睡', pinyin: 'wǔ shuì', english: 'nap' },
  { no: 581, chinese: '西北', pinyin: 'xī běi', english: 'northwest' },
  { no: 582, chinese: '西餐', pinyin: 'xī cān', english: 'western food' },
  { no: 583, chinese: '西方', pinyin: 'xī fāng', english: 'west' },
  { no: 584, chinese: '西南', pinyin: 'xī nán', english: 'southwest' },
  { no: 585, chinese: '西医', pinyin: 'xī yī', english: 'western medicine' },
  { no: 586, chinese: '习惯', pinyin: 'xíguàn', english: 'Habit' },
  { no: 587, chinese: '洗衣机', pinyin: 'xǐ yī jī', english: 'washing machine' },
  { no: 588, chinese: '洗澡', pinyin: 'xǐzǎo', english: 'Take a shower' },
  { no: 589, chinese: '下（量）', pinyin: 'xià', english: '(measure word)' },
  { no: 590, chinese: '下雪', pinyin: 'xià xuě', english: 'snow; snowing' },
  { no: 591, chinese: '下周', pinyin: 'xià zhōu', english: 'next week' },
  { no: 592, chinese: '夏天', pinyin: 'xià tiān', english: 'summer' },
  { no: 593, chinese: '相同', pinyin: 'xiāngtóng', english: 'identical' },
  { no: 594, chinese: '相信', pinyin: 'xiāngxìn', english: 'believe' },
  { no: 595, chinese: '响', pinyin: 'xiǎng', english: 'loud' },
  { no: 596, chinese: '想到', pinyin: 'xiǎng dào', english: 'think of; call to mind' },
  { no: 597, chinese: '想法', pinyin: 'xiǎng fǎ', english: 'idea; opinion; thought' },
  { no: 598, chinese: '想起', pinyin: 'xiǎng qǐ', english: 'remember; recall' },
  { no: 599, chinese: '向', pinyin: 'xiàng', english: 'towards' },
  { no: 600, chinese: '相机', pinyin: 'xiàng jī', english: 'camera' },
  { no: 601, chinese: '像（动）', pinyin: 'xiàng', english: 'be like; resemble' },
  { no: 602, chinese: '小（小王）', pinyin: 'xiǎo (xiǎo wáng)', english: 'prefix (Xiao Wang)' },
  { no: 603, chinese: '小声', pinyin: 'xiǎo shēng', english: 'in a low voice' },
  { no: 604, chinese: '小时候', pinyin: 'xiǎo shí hou', english: 'in one’s childhood' },
  { no: 605, chinese: '小说', pinyin: 'xiǎoshuō', english: 'Novel' },
  { no: 606, chinese: '小心', pinyin: 'xiǎoxīn', english: 'Look out' },
  { no: 607, chinese: '小组', pinyin: 'xiǎo zǔ', english: 'group' },
  { no: 608, chinese: '校园', pinyin: 'xiào yuán', english: 'campus; schoolyard' },
  { no: 609, chinese: '校长', pinyin: 'xiàozhǎng', english: 'Principal' },
  { no: 610, chinese: '笑话', pinyin: 'xiàohua', english: 'joke' },
  { no: 611, chinese: '笑话儿', pinyin: 'xiào huàr', english: 'joke' },
  { no: 612, chinese: '鞋', pinyin: 'xié', english: 'shoes' },
  { no: 613, chinese: '心里', pinyin: 'xīn lǐ', english: 'in the heart; at heart' },
  { no: 614, chinese: '心情', pinyin: 'xīnqíng', english: 'mood' },
  { no: 615, chinese: '心中', pinyin: 'xīn zhōng', english: 'in mind' },
  { no: 616, chinese: '新闻', pinyin: 'xīnwén', english: 'news' },
  { no: 617, chinese: '信（名）', pinyin: 'xìn', english: 'letter; mail; faith' },
  { no: 618, chinese: '信号', pinyin: 'xìnhào', english: 'signal' },
  { no: 619, chinese: '信息', pinyin: 'xìnxī', english: 'information' },
  { no: 620, chinese: '信心', pinyin: 'xìnxīn', english: 'confidence' },
  { no: 621, chinese: '信用卡', pinyin: 'xìnyòngkǎ', english: 'Credit card' },
  { no: 622, chinese: '星星', pinyin: 'xīng xing', english: 'star' },
  { no: 623, chinese: '行动', pinyin: 'xíngdòng', english: 'Get some action' },
  { no: 624, chinese: '行人', pinyin: 'xíngrén', english: 'pedestrian' },
  { no: 625, chinese: '行为', pinyin: 'xíngwéi', english: 'behavior' },
  { no: 626, chinese: '姓', pinyin: 'xìng', english: 'surname' },
  { no: 627, chinese: '姓名', pinyin: 'xìng míng', english: 'full name' },
  { no: 628, chinese: '休假', pinyin: 'xiū jià', english: 'take a vacation' },
  { no: 629, chinese: '许多', pinyin: 'xǔduō', english: 'many' },
  { no: 630, chinese: '选', pinyin: 'xuǎn', english: 'choose; select' },
  { no: 631, chinese: '学期', pinyin: 'xuéqī', english: 'Semester' },
  { no: 632, chinese: '雪', pinyin: 'xuě', english: 'Snow' },
  { no: 633, chinese: '颜色', pinyin: 'yánsè', english: 'colour' },
  { no: 634, chinese: '眼', pinyin: 'yǎn', english: 'eye' },
  { no: 635, chinese: '眼睛', pinyin: 'yǎnjing', english: 'Eye' },
  { no: 636, chinese: '养', pinyin: 'yǎng', english: 'raise; keep; support' },
  { no: 637, chinese: '样子', pinyin: 'yàngzi', english: 'A look' },
  { no: 638, chinese: '要求', pinyin: 'yāoqiú', english: 'Requirement' },
  { no: 639, chinese: '药', pinyin: 'yào', english: 'drug' },
  { no: 640, chinese: '药店', pinyin: 'yào diàn', english: 'pharmacy' },
  { no: 641, chinese: '药片', pinyin: 'yào piàn', english: 'pill' },
  { no: 642, chinese: '药水', pinyin: 'yào shuǐ', english: 'liquid medicine' },
  { no: 643, chinese: '也许', pinyin: 'yěxǔ', english: 'perhaps' },
  { no: 644, chinese: '夜', pinyin: 'yè', english: 'night' },
  { no: 645, chinese: '夜里', pinyin: 'yè lǐ', english: 'at night' },
  { no: 646, chinese: '一部分', pinyin: 'yí bù fèn', english: 'a part; a portion' },
  { no: 647, chinese: '一定', pinyin: 'yídìng', english: 'Certain' },
  { no: 648, chinese: '一共', pinyin: 'yígòng', english: 'Altogether' },
  { no: 649, chinese: '一会儿', pinyin: 'yí huìr', english: 'awhile; in a moment' },
  { no: 650, chinese: '一路平安', pinyin: 'yí lù píng ān', english: 'safe journey' },
  { no: 651, chinese: '一路顺风', pinyin: 'yí lù shùn fēng', english: 'Bon voyage' },
  { no: 652, chinese: '已经', pinyin: 'yǐjīng', english: 'Already' },
  { no: 653, chinese: '以后', pinyin: 'yǐ hòu', english: 'after; later on' },
  { no: 654, chinese: '以前', pinyin: 'yǐqián', english: 'before' },
  { no: 655, chinese: '以上', pinyin: 'yǐ shàng', english: 'above; over' },
  { no: 656, chinese: '以外', pinyin: 'yǐ wài', english: 'beyond; outside' },
  { no: 657, chinese: '以为', pinyin: 'yǐwéi', english: 'Think' },
  { no: 658, chinese: '以下', pinyin: 'yǐ xià', english: 'below; under' },
  { no: 659, chinese: '椅子', pinyin: 'yǐzi', english: 'Chair' },
  { no: 660, chinese: '一般', pinyin: 'yìbān', english: 'commonly' },
  { no: 661, chinese: '一点点', pinyin: 'yì diǎn diǎn', english: 'a little bit' },
  { no: 662, chinese: '一生', pinyin: 'yì shēng', english: 'lifetime' },
  { no: 663, chinese: '一直', pinyin: 'yìzhí', english: 'always' },
  { no: 664, chinese: '亿', pinyin: 'yì', english: '100 million' },
  { no: 665, chinese: '意见', pinyin: 'yìjiàn', english: 'Opinion' },
  { no: 666, chinese: '意思', pinyin: 'yìsi', english: 'Meaning' },
  { no: 667, chinese: '因为', pinyin: 'yīn wèi', english: 'because' },
  { no: 668, chinese: '阴', pinyin: 'yīn', english: 'Yin' },
  { no: 669, chinese: '阴天', pinyin: 'yīn tiān', english: 'cloudy day' },
  { no: 670, chinese: '音节', pinyin: 'yīn jié', english: 'syllable' },
  { no: 671, chinese: '音乐', pinyin: 'yīnyuè', english: 'Music' },
  { no: 672, chinese: '音乐会', pinyin: 'yīn yuè huì', english: 'concert' },
  { no: 673, chinese: '银行', pinyin: 'yínháng', english: 'Bank' },
  { no: 674, chinese: '银行卡', pinyin: 'yín háng kǎ', english: 'bank card' },
  { no: 675, chinese: '应该', pinyin: 'yīnggāi', english: 'Should' },
  { no: 676, chinese: '英文', pinyin: 'yīng wén', english: 'English' },
  { no: 677, chinese: '英语', pinyin: 'yīng yǔ', english: 'English' },
  { no: 678, chinese: '影片', pinyin: 'yǐng piàn', english: 'film; movie' },
  { no: 679, chinese: '影响', pinyin: 'yǐngxiǎng', english: 'Influence' },
  { no: 680, chinese: '永远', pinyin: 'yǒngyuǎn', english: 'forever' },
  { no: 681, chinese: '油', pinyin: 'yóu', english: 'oil; fat; grease' },
  { no: 682, chinese: '游客', pinyin: 'yóu kè', english: 'tourist; visitor' },
  { no: 683, chinese: '友好', pinyin: 'yǒuhǎo', english: 'friendly' },
  { no: 684, chinese: '有空儿', pinyin: 'yǒu kòngr', english: 'be free; at leisure' },
  { no: 685, chinese: '有人', pinyin: 'yǒu rén', english: 'someone' },
  { no: 686, chinese: '有点儿', pinyin: 'yǒu (yì) diǎnr', english: 'a little bit' },
  { no: 687, chinese: '有意思', pinyin: 'yǒu yì si', english: 'interesting; significant' },
  { no: 688, chinese: '又', pinyin: 'yòu', english: 'also' },
  { no: 689, chinese: '鱼', pinyin: 'yú', english: 'fish' },
  { no: 690, chinese: '语言', pinyin: 'yǔyán', english: 'language' },
  { no: 691, chinese: '原来', pinyin: 'yuánlái', english: 'Original; formerly' },
  { no: 692, chinese: '原因', pinyin: 'yuányīn', english: 'Reason' },
  { no: 693, chinese: '院', pinyin: 'yuàn', english: 'yard; compound; college' },
  { no: 694, chinese: '院长', pinyin: 'yuàn zhǎng', english: 'dean' },
  { no: 695, chinese: '院子', pinyin: 'yuàn zi', english: 'courtyard' },
  { no: 696, chinese: '愿意', pinyin: 'yuànyì', english: 'Be willing' },
  { no: 697, chinese: '月份', pinyin: 'yuè fèn', english: 'month' },
  { no: 698, chinese: '月亮', pinyin: 'yuèliang', english: 'Moon' },
  { no: 699, chinese: '越', pinyin: 'yuè', english: 'The more' },
  { no: 700, chinese: '越来越', pinyin: 'yuè lái yuè', english: 'more and more' },
  { no: 701, chinese: '云', pinyin: 'yún', english: 'cloud' },
  { no: 702, chinese: '运动', pinyin: 'yùndòng', english: 'motion' },
  { no: 703, chinese: '咱', pinyin: 'zán', english: 'we; us' },
  { no: 704, chinese: '咱们', pinyin: 'zánmen', english: 'We' },
  { no: 705, chinese: '脏', pinyin: 'zāng', english: 'dirty' },
  { no: 706, chinese: '早餐', pinyin: 'zǎo cān', english: 'breakfast' },
  { no: 707, chinese: '早晨', pinyin: 'zǎo chén', english: 'morning' },
  { no: 708, chinese: '早就', pinyin: 'zǎo jiù', english: 'long since' },
  { no: 709, chinese: '怎么办', pinyin: 'zěn me bàn', english: 'what to do' },
  { no: 710, chinese: '怎么样', pinyin: 'zěnmeyàng', english: 'How about' },
  { no: 711, chinese: '怎样', pinyin: 'zěn yàng', english: 'how' },
  { no: 712, chinese: '占', pinyin: 'zhàn', english: 'occupy' },
  { no: 713, chinese: '站（动）', pinyin: 'zhàn', english: 'stand; stop; halt' },
  { no: 714, chinese: '站住', pinyin: 'zhàn zhù', english: 'stop; halt' },
  { no: 715, chinese: '长', pinyin: 'zhǎng', english: 'grow' },
  { no: 716, chinese: '长大', pinyin: 'zhǎng dà', english: 'grow up' },
  { no: 717, chinese: '找出', pinyin: 'zhǎo chū', english: 'find out' },
  { no: 718, chinese: '照顾', pinyin: 'zhàogù', english: 'look after' },
  { no: 719, chinese: '照片', pinyin: 'zhàopiàn', english: 'Photo' },
  { no: 720, chinese: '照相', pinyin: 'zhào xiàng', english: 'take a picture' },
  { no: 721, chinese: '这么', pinyin: 'zhè me', english: 'so; such' },
  { no: 722, chinese: '这时候／这时', pinyin: 'zhè shí hou / zhè shí', english: 'at this moment' },
  { no: 723, chinese: '这样', pinyin: 'zhè yàng', english: 'like this; this way' },
  { no: 724, chinese: '真正', pinyin: 'zhēnzhèng', english: 'real' },
  { no: 725, chinese: '正常', pinyin: 'zhèngcháng', english: 'normal' },
  { no: 726, chinese: '正好', pinyin: 'zhènghǎo', english: 'Just right' },
  { no: 727, chinese: '正确', pinyin: 'zhèngquè', english: 'Correct' },
  { no: 728, chinese: '正是', pinyin: 'zhèng shì', english: 'exactly' },
  { no: 729, chinese: '直接', pinyin: 'zhíjiē', english: 'direct' },
  { no: 730, chinese: '只', pinyin: 'zhǐ', english: 'only; just' },
  { no: 731, chinese: '只能', pinyin: 'zhǐ néng', english: 'can only' },
  { no: 732, chinese: '只要', pinyin: 'zhǐyào', english: 'as long as' },
  { no: 733, chinese: '纸', pinyin: 'zhǐ', english: 'paper' },
  { no: 734, chinese: '中餐', pinyin: 'zhōng cān', english: 'Chinese food' },
  { no: 735, chinese: '中级', pinyin: 'zhōng jí', english: 'intermediate' },
  { no: 736, chinese: '中年', pinyin: 'zhōng nián', english: 'middle age' },
  { no: 737, chinese: '中小学', pinyin: 'zhōng xiǎo xué', english: 'elementary and middle school' },
  { no: 738, chinese: '中心', pinyin: 'zhōngxīn', english: 'core' },
  { no: 739, chinese: '中医', pinyin: 'zhōng yī', english: 'Chinese Medicine' },
  { no: 740, chinese: '重点', pinyin: 'zhòngdiǎn', english: 'A key' },
  { no: 741, chinese: '重视', pinyin: 'zhòngshì', english: 'attach importance to' },
  { no: 742, chinese: '周', pinyin: 'zhōu', english: 'week' },
  { no: 743, chinese: '周末', pinyin: 'zhōumò', english: 'Weekend' },
  { no: 744, chinese: '周年', pinyin: 'zhōunián', english: 'anniversary' },
  { no: 745, chinese: '主人', pinyin: 'zhǔrén', english: 'master' },
  { no: 746, chinese: '主要', pinyin: 'zhǔyào', english: 'main' },
  { no: 747, chinese: '住房', pinyin: 'zhù fáng', english: 'housing; lodging' },
  { no: 748, chinese: '住院', pinyin: 'zhù yuàn', english: 'be in hospital' },
  { no: 749, chinese: '装', pinyin: 'zhuāng', english: 'pretend' },
  { no: 750, chinese: '准确', pinyin: 'zhǔnquè', english: 'accuracy' },
  { no: 751, chinese: '自己', pinyin: 'zìjǐ', english: 'Own, self' },
  { no: 752, chinese: '自行车', pinyin: 'zìxíngchē', english: 'Bicycle' },
  { no: 753, chinese: '自由', pinyin: 'zìyóu', english: 'free' },
  { no: 754, chinese: '字典', pinyin: 'zì diǎn', english: 'dictionary' },
  { no: 755, chinese: '走过', pinyin: 'zǒu guò', english: 'walk through; pass by' },
  { no: 756, chinese: '走进', pinyin: 'zǒu jìn', english: 'walk in' },
  { no: 757, chinese: '走开', pinyin: 'zǒu kāi', english: 'go away' },
  { no: 758, chinese: '租', pinyin: 'zū', english: 'rent' },
  { no: 759, chinese: '组', pinyin: 'zǔ', english: 'group' },
  { no: 760, chinese: '组成', pinyin: 'zǔchéng', english: 'Form' },
  { no: 761, chinese: '组长', pinyin: 'zǔ zhǎng', english: 'group leader' },
  { no: 762, chinese: '嘴', pinyin: 'zuǐ', english: 'mouth' },
  { no: 763, chinese: '最近', pinyin: 'zuìjìn', english: 'Lately' },
  { no: 764, chinese: '作家', pinyin: 'zuòjiā', english: 'writer' },
  { no: 765, chinese: '作文', pinyin: 'zuòwén', english: 'composition' },
  { no: 766, chinese: '作业', pinyin: 'zuòyè', english: 'task, homework' },
  { no: 767, chinese: '作用', pinyin: 'zuòyòng', english: 'Effect' },
  { no: 768, chinese: '座', pinyin: 'zuò', english: 'Seat' },
  { no: 769, chinese: '座位', pinyin: 'zuòwèi', english: 'seat' },
  { no: 770, chinese: '做到', pinyin: 'zuò dào', english: 'accomplish; achieve' },
  { no: 771, chinese: '做法', pinyin: 'zuò fǎ', english: 'practice; way of doing' },
  { no: 772, chinese: '做饭', pinyin: 'zuò fàn', english: 'cook' }
];
/* ---------- Tabulator ---------- */
new Tabulator('#hsk2plusTable', {
  data: vocab,
  layout: 'fitColumns',
  resizableColumns: false,
  columns: [
    {title: 'No',    field: 'no',    width: 60},
    {title: '中文',  field: 'chinese'},
    {title: '拼音',  field: 'pinyin'},
    {title: 'English', field: 'english'}
  ]
});