/* ---------- 973 entires ---------- */
const vocab = [
{no:1,  chinese:'爱心',             pinyin:'àixīn',         english:'love'},
{no:2,  chinese:'安排',             pinyin:'ānpái',         english:'arrange'},
{no:3,  chinese:'安装',             pinyin:'ānzhuāng',      english:'install'},
{no:4,  chinese:'按',               pinyin:'àn',            english:'press; push; check; restrain'},
{no:5,  chinese:'按照',             pinyin:'ànzhào',        english:'according to'},
{no:6,  chinese:'把（介）',          pinyin:'bǎ',            english:'(particle marking the following noun as a direct object)'},
{no:7,  chinese:'把（量）',          pinyin:'bǎ',            english:'(measure word)'},
{no:8,  chinese:'把握',             pinyin:'bǎwò',          english:'grasp'},
{no:9,  chinese:'白（副）',          pinyin:'bái',           english:'without results; in vain; waste efforts'},
{no:10, chinese:'白菜',             pinyin:'bái cài',       english:'Chinese cabbage'},
{no:11, chinese:'班级',             pinyin:'bān jí',        english:'class'},
{no:12, chinese:'搬',               pinyin:'bān',           english:'turn; move'},
{no:13, chinese:'搬家',             pinyin:'bān jiā',       english:'move; move house'},
{no:14, chinese:'板',               pinyin:'bǎn',           english:'board; plank; shutter'},
{no:15, chinese:'办理',             pinyin:'bànlǐ',         english:'handle'},
{no:16, chinese:'保',               pinyin:'bǎo',           english:'defend; protect; keep; guarantee; ensure'},
{no:17, chinese:'保安',             pinyin:'bǎo ān',        english:'security guard; public security; ensure safety'},
{no:18, chinese:'保持',             pinyin:'bǎochí',        english:'keep'},
{no:19, chinese:'保存',             pinyin:'bǎocún',        english:'Preservation'},
{no:20, chinese:'保护',             pinyin:'bǎohù',         english:'protect'},
{no:21, chinese:'保留',             pinyin:'bǎoliú',        english:'Retain'},
{no:22, chinese:'保险',             pinyin:'bǎoxiǎn',       english:'Insurance'},
{no:23, chinese:'保证',             pinyin:'bǎozhèng',      english:'ensure'},
{no:24, chinese:'报（名）',          pinyin:'bào',           english:'newspaper; periodical; journal; report; telegram'},
{no:25, chinese:'报到',             pinyin:'bàodào',        english:'register, check in'},
{no:26, chinese:'报道',             pinyin:'bàodào',        english:'report'},
{no:27, chinese:'报告',             pinyin:'bàogào',        english:'Presentation'},
{no:28, chinese:'背（名）',          pinyin:'bèi',           english:'back'},
{no:29, chinese:'北部',             pinyin:'běi bù',        english:'north'},
{no:30, chinese:'背（名）',          pinyin:'bèi',           english:'back of the body; back side of an object'},
{no:31, chinese:'背后',             pinyin:'bèi hòu',       english:'behind; at the back; in the rear'},
{no:32, chinese:'被',               pinyin:'bèi',           english:'cover'},
{no:33, chinese:'被子',             pinyin:'bèizi',         english:'quilt'},
{no:34, chinese:'本来',             pinyin:'běnlái',        english:'originally'},
{no:35, chinese:'本领',             pinyin:'běnlǐng',       english:'ability'},
{no:36, chinese:'本事',             pinyin:'běnshi',        english:'Skill'},
{no:37, chinese:'比较',             pinyin:'bǐjiào',        english:'compare'},
{no:38, chinese:'比例',             pinyin:'bǐlì',          english:'Proportion'},
{no:39, chinese:'比赛',             pinyin:'bǐsài',         english:'Match'},
{no:40, chinese:'必然',             pinyin:'bìrán',         english:'Inevitable'},
{no:41, chinese:'必要',             pinyin:'bìyào',         english:'necessary'},
{no:42, chinese:'变化',             pinyin:'biànhuà',       english:'change'},
{no:43, chinese:'变为',             pinyin:'biàn wéi',      english:'become; turn into; change into'},
{no:44, chinese:'标题',             pinyin:'biāotí',        english:'title; heading'},
{no:45, chinese:'标准',             pinyin:'biāozhǔn',      english:'standard'},
{no:46, chinese:'表达',             pinyin:'biǎodá',        english:'Expression'},
{no:47, chinese:'表格',             pinyin:'biǎogé',        english:'form'},
{no:48, chinese:'表面',             pinyin:'biǎomiàn',      english:'surface'},
{no:49, chinese:'表明',             pinyin:'biǎomíng',      english:'Indicate'},
{no:50, chinese:'表现',             pinyin:'biǎoxiàn',      english:'performance'},
{no:51, chinese:'表演',             pinyin:'biǎoyǎn',       english:'perform'},
{no:52, chinese:'并（副、连）',       pinyin:'bìng',          english:'and; also; equally; simultaneously; side by side'},
{no:53, chinese:'并且',             pinyin:'bìngqiě',       english:'also'},
{no:54, chinese:'播出',             pinyin:'bō chū',        english:'broadcast; on the air'},
{no:55, chinese:'播放',             pinyin:'bōfàng',        english:'play'},
{no:56, chinese:'不必',             pinyin:'bú bì',         english:'need not; not have to'},
{no:57, chinese:'不断',             pinyin:'búduàn',        english:'Constantly'},
{no:58, chinese:'不论',             pinyin:'bú lùn',        english:'whether; no matter; whether … or'},
{no:59, chinese:'补',               pinyin:'bǔ',            english:'repair; mend; patch; supply; make up for'},
{no:60, chinese:'补充',             pinyin:'bǔchōng',       english:'supplement'},
{no:61, chinese:'不安',             pinyin:'bù’ān',         english:'Uneasy'},
{no:62, chinese:'不得不',           pinyin:'bùdébù',        english:'Cannot but'},
{no:63, chinese:'不光',             pinyin:'bù guāng',      english:'not only'},
{no:64, chinese:'不仅',             pinyin:'bùjǐn',         english:'not only'},
{no:65, chinese:'布',               pinyin:'bù',            english:'cloth'},
{no:66, chinese:'步',               pinyin:'bù',            english:'step; stage; walk; foot'},
{no:67, chinese:'部',               pinyin:'bù',            english:'unit; ministry; department; part; section'},
{no:68, chinese:'部门',             pinyin:'bùmén',         english:'department'},
{no:69, chinese:'部长',             pinyin:'bù zhǎng',      english:'minister; head of a department'},
{no:70, chinese:'才能',             pinyin:'cái néng',      english:'talent; ability; gift'},
{no:71, chinese:'采取',             pinyin:'cǎiqǔ',         english:'take, adopt'},
{no:72, chinese:'采用',             pinyin:'cǎi yòng',      english:'put to use; adopt; use; employ'},
{no:73, chinese:'彩色',             pinyin:'cǎi sè',        english:'multicolour; colour'},
{no:74, chinese:'曾经',             pinyin:'céngjīng',      english:'once'},
{no:75, chinese:'产生',             pinyin:'chǎnshēng',     english:'produce'},
{no:76, chinese:'长城',             pinyin:'Chángchéng',    english:'The Great Wall'},
{no:77, chinese:'长处',             pinyin:'cháng chù',     english:'strength; forte; strong point'},
{no:78, chinese:'长期',             pinyin:'cháng qī',      english:'over a long period of time; long-term'},
{no:79, chinese:'厂',               pinyin:'chǎng',         english:'factory; mill; plant; works'},
{no:80, chinese:'场合',             pinyin:'chǎnghé',       english:'occasion'},
{no:81, chinese:'场所',             pinyin:'chǎngsuǒ',      english:'place'},
{no:82, chinese:'超级',             pinyin:'chāojí',        english:'super'},
{no:83, chinese:'朝',               pinyin:'cháo',          english:'towards'},
{no:84, chinese:'吵',               pinyin:'chǎo',          english:'Noisy'},
{no:85, chinese:'吵架',             pinyin:'chǎojià',       english:'quarrel'},
{no:86, chinese:'衬衫',             pinyin:'chènshān',      english:'shirt'},
{no:87, chinese:'衬衣',             pinyin:'chèn yī',       english:'shirt'},
{no:88, chinese:'称为',             pinyin:'chēng wéi',     english:'call; be called; be known as'},
{no:89, chinese:'成功',             pinyin:'chénggōng',     english:'Success'},
{no:90, chinese:'成果',             pinyin:'chéngguǒ',      english:'Achievements'},
{no:91, chinese:'成就',             pinyin:'chéngjiù',      english:'achievement'},
{no:92, chinese:'成立',             pinyin:'chénglì',       english:'establish'},
{no:93, chinese:'成熟',             pinyin:'chéngshú',      english:'mature'},
{no:94, chinese:'成员',             pinyin:'chéngyuán',     english:'member'},
{no:95, chinese:'成长',             pinyin:'chéngzhǎng',    english:'Grow up'},
{no:96, chinese:'城',               pinyin:'chéng',         english:'city; town'},
{no:97, chinese:'城市',             pinyin:'chéngshì',      english:'City'},
{no:98, chinese:'程度',             pinyin:'chéngdù',       english:'degree'},
{no:99, chinese:'持续',             pinyin:'chíxù',         english:'Continued'},
{no:100, chinese:'充满',            pinyin:'chōngmǎn',      english:'full of'},
{no:101, chinese:'重',              pinyin:'zhòng',         english:'heavy'},
{no:102, chinese:'初',              pinyin:'chū',           english:'beginning; start; basis; at the beginning of'},
{no:103, chinese:'初（初一）',       pinyin:'chū (chū yī)',  english:'prefix (first grade of junior high school)'},
{no:104, chinese:'初步',            pinyin:'chūbù',         english:'preliminary'},
{no:105, chinese:'初级',            pinyin:'chūjí',         english:'primary'},
{no:106, chinese:'初中',            pinyin:'chū zhōng',     english:'junior high school'},
{no:107, chinese:'除了',            pinyin:'chúle',         english:'except'},
{no:108, chinese:'处理',            pinyin:'chǔlǐ',         english:'Handle'},
{no:109, chinese:'传',              pinyin:'chuán',         english:'pass; pass on; hand down; impart; spread; transmit'},
{no:110, chinese:'传播',            pinyin:'chuánbō',       english:'spread'},
{no:111, chinese:'传来',            pinyin:'chuán lái',     english:'came; come through'},
{no:112, chinese:'传说',            pinyin:'chuánshuō',     english:'Legend'},
{no:113, chinese:'创新',            pinyin:'chuàngxīn',     english:'innovate'},
{no:114, chinese:'创业',            pinyin:'chuàngyè',      english:'carve out'},
{no:115, chinese:'创造',            pinyin:'chuàngzào',     english:'create'},
{no:116, chinese:'创作',            pinyin:'chuàngzuò',     english:'A literary creation'},
{no:117, chinese:'从来',            pinyin:'cónglái',       english:'Always'},
{no:118, chinese:'从前',            pinyin:'cóngqián',      english:'before'},
{no:119, chinese:'从事',            pinyin:'cóngshì',       english:'Be engaged in'},
{no:120, chinese:'村',              pinyin:'cūn',           english:'village; hamlet'},
{no:121, chinese:'存',              pinyin:'cún',           english:'Deposit'},
{no:122, chinese:'存在',            pinyin:'cúnzài',        english:'existence'},
{no:123, chinese:'错误',            pinyin:'cuòwù',         english:'error'},
{no:124, chinese:'达到',            pinyin:'dádào',         english:'Achieve'},
{no:125, chinese:'打破',            pinyin:'dǎ pò',         english:'break; smash'},
{no:126, chinese:'打听',            pinyin:'dǎting',        english:'Inquire'},
{no:127, chinese:'大概',            pinyin:'dàgài',         english:'Probably'},
{no:128, chinese:'大使馆',           pinyin:'dàshǐguǎn',     english:'Embassy'},
{no:129, chinese:'大约',            pinyin:'dàyuē',         english:'about'},
{no:130, chinese:'大夫',            pinyin:'dàifu',         english:'Doctor'},
{no:131, chinese:'代',              pinyin:'dài',           english:'substitute; replace; take the place of'},
{no:132, chinese:'代表',            pinyin:'dàibiǎo',       english:'representative'},
{no:133, chinese:'代表团',           pinyin:'dài biǎo tuán', english:'delegation; mission; deputation'},
{no:134, chinese:'带动',            pinyin:'dài dòng',      english:'drive; spur'},
{no:135, chinese:'带领',            pinyin:'dàilǐng',       english:'lead'},
{no:136, chinese:'单元',            pinyin:'dānyuán',       english:'unit'},
{no:137, chinese:'当初',            pinyin:'dāngchū',       english:'Original'},
{no:138, chinese:'当地',            pinyin:'dāngdì',        english:'Local'},
{no:139, chinese:'当然',            pinyin:'dāngrán',       english:'Of course'},
{no:140, chinese:'当中',            pinyin:'dāng zhōng',    english:'among; in the middle; in the centre'},
{no:141, chinese:'刀',              pinyin:'dāo',           english:'knife'},
{no:142, chinese:'导演',            pinyin:'dǎoyǎn',        english:'director'},
{no:143, chinese:'到达',            pinyin:'dàodá',         english:'Arrive'},
{no:144, chinese:'到底',            pinyin:'dàodǐ',         english:'To the end'},
{no:145, chinese:'得分',            pinyin:'dé fēn',        english:'score'},
{no:146, chinese:'等待',            pinyin:'děngdài',       english:'wait for'},
{no:147, chinese:'底下',            pinyin:'dǐ xià',        english:'under; below; beneath'},
{no:148, chinese:'地区',            pinyin:'dìqū',          english:'region'},
{no:149, chinese:'电视剧',           pinyin:'diàn shì jù',   english:'TV series; television drama'},
{no:150, chinese:'电视台',           pinyin:'diàn shì tái',  english:'TV station'},
{no:151, chinese:'电台',            pinyin:'diàntái',       english:'radio station'},
{no:152, chinese:'电子邮件',         pinyin:'diànzǐyóujiàn', english:'E-mail'},
{no:153, chinese:'调',              pinyin:'diào',          english:'transfer; shift; move'},
{no:154, chinese:'调查',            pinyin:'diàochá',       english:'investigation'},
{no:155, chinese:'订',              pinyin:'dìng',          english:'conclude; draw up; order; revise'},
{no:156, chinese:'定期',            pinyin:'dìngqī',        english:'regular'},
{no:157, chinese:'东部',            pinyin:'dōng bù',       english:'east'},
{no:158, chinese:'动力',            pinyin:'dònglì',        english:'power, motivation'},
{no:159, chinese:'动人',            pinyin:'dòng rén',      english:'moving; touching'},
{no:160, chinese:'读者',            pinyin:'dú zhě',        english:'reader'},
{no:161, chinese:'短处',            pinyin:'duǎn chù',      english:'shortcoming; demerit'},
{no:162, chinese:'短裤',            pinyin:'duǎn kù',       english:'shorts'},
{no:163, chinese:'短期',            pinyin:'duǎn qī',       english:'short term'},
{no:164, chinese:'断',              pinyin:'duàn',          english:'break'},
{no:165, chinese:'队员',            pinyin:'duì yuán',      english:'team member'},
{no:166, chinese:'对待',            pinyin:'duìdài',        english:'treat'},
{no:167, chinese:'对方',            pinyin:'duìfāng',       english:'Other party'},
{no:168, chinese:'对手',            pinyin:'duìshǒu',       english:'Opponent'},
{no:169, chinese:'对象',            pinyin:'duìxiàng',      english:'object'},
{no:170, chinese:'顿',              pinyin:'dùn',           english:'Meal'},
{no:171, chinese:'发表',            pinyin:'fābiǎo',        english:'Publish'},
{no:172, chinese:'发出',            pinyin:'fā chū',        english:'issue; send out; give off; emit'},
{no:173, chinese:'发达',            pinyin:'fādá',          english:'developed'},
{no:174, chinese:'发动',            pinyin:'fādòng',        english:'Launch'},
{no:175, chinese:'发明',            pinyin:'fāmíng',        english:'Invention'},
{no:176, chinese:'发生',            pinyin:'fāshēng',       english:'Happen'},
{no:177, chinese:'发送',            pinyin:'fā sòng',       english:'send; transmit; dispatch; ship; forward'},
{no:178, chinese:'发言',            pinyin:'fāyán',         english:'speak'},
{no:179, chinese:'发展',            pinyin:'fāzhǎn',        english:'Development'},
{no:180, chinese:'反对',            pinyin:'fǎnduì',        english:'Opposition'},
{no:181, chinese:'反复',            pinyin:'fǎnfù',         english:'Repeatedly'},
{no:182, chinese:'反应',            pinyin:'fǎnyìng',       english:'reaction'},
{no:183, chinese:'反正',            pinyin:'fǎnzhèng',      english:'anyway'},
{no:184, chinese:'范围',            pinyin:'fànwéi',        english:'Range'},
{no:185, chinese:'方式',            pinyin:'fāngshì',       english:'mode'},
{no:186, chinese:'防',              pinyin:'fáng',          english:'guard against; defend'},
{no:187, chinese:'防止',            pinyin:'fángzhǐ',       english:'Prevent'},
{no:188, chinese:'房东',            pinyin:'fángdōng',      english:'landlord'},
{no:189, chinese:'房屋',            pinyin:'fáng wū',       english:'houses; buildings; tenement'},
{no:190, chinese:'房租',            pinyin:'fáng zū',       english:'rent'},
{no:191, chinese:'访问',            pinyin:'fǎngwèn',       english:'Visit'},
{no:192, chinese:'放到',            pinyin:'fàng dào',      english:'put to; put into'},
{no:193, chinese:'飞行',            pinyin:'fēi xíng',      english:'flight; flying'},
{no:194, chinese:'费',              pinyin:'fèi',           english:'fee; cost'},
{no:195, chinese:'费用',            pinyin:'fèi yòng',      english:'cost; expenses; outlay'},
{no:196, chinese:'分别',            pinyin:'fēnbié',        english:'part'},
{no:197, chinese:'分配',            pinyin:'fēnpèi',        english:'distribution'},
{no:198, chinese:'分组',            pinyin:'fēn zǔ',        english:'grouping'},
{no:199, chinese:'丰富',            pinyin:'fēngfù',        english:'rich'},
{no:200, chinese:'风险',            pinyin:'fēngxiǎn',      english:'risk'},
{no:201, chinese:'否定',            pinyin:'fǒudìng',       english:'negative'},
{no:202, chinese:'否认',            pinyin:'fǒurèn',        english:'deny'},
{no:203, chinese:'服装',            pinyin:'fúzhuāng',      english:'costume; dress'},
{no:204, chinese:'福',              pinyin:'fú',            english:'blessing; good fortune'},
{no:205, chinese:'父母',            pinyin:'fù mǔ',         english:'father and mother; parents'},
{no:206, chinese:'父亲',            pinyin:'fùqīn',         english:'father'},
{no:207, chinese:'付',              pinyin:'fù',            english:'pay; commit; hand over'},
{no:208, chinese:'负责',            pinyin:'fùzé',          english:'Be responsible for'},
{no:209, chinese:'复印',            pinyin:'fùyìn',         english:'To copy'},
{no:210, chinese:'复杂',            pinyin:'fùzá',          english:'complex'},
{no:211, chinese:'富',              pinyin:'fù',            english:'rich'},
{no:212, chinese:'改进',            pinyin:'gǎijìn',        english:'Improvement'},
{no:213, chinese:'改造',            pinyin:'gǎi zào',       english:'transform; reform'},
{no:214, chinese:'概念',            pinyin:'gàiniàn',       english:'concept'},
{no:215, chinese:'赶',              pinyin:'gǎn',           english:'catch up with'},
{no:216, chinese:'赶到',            pinyin:'gǎn dào',       english:'arrived; get to'},
{no:217, chinese:'赶紧',            pinyin:'gǎnjǐn',        english:'Quickly'},
{no:218, chinese:'赶快',            pinyin:'gǎnkuài',       english:'Come on'},
{no:219, chinese:'敢',              pinyin:'gǎn',           english:'dare'},
{no:220, chinese:'感冒',            pinyin:'gǎnmào',        english:'Cold'},
{no:221, chinese:'感情',            pinyin:'gǎnqíng',       english:'feeling'},
{no:222, chinese:'感受',            pinyin:'gǎnshòu',       english:'feel'},
{no:223, chinese:'干吗',            pinyin:'gàn má',        english:'Why'},
{no:224, chinese:'高速',            pinyin:'gāo sù',        english:'high speed'},
{no:225, chinese:'高速公路',         pinyin:'gāosùgōnglù',   english:'Expressway'},
{no:226, chinese:'告别',            pinyin:'gàobié',        english:'farewell'},
{no:227, chinese:'歌迷',            pinyin:'gē mí',         english:'fan'},
{no:228, chinese:'歌声',            pinyin:'gē shēng',      english:'singing'},
{no:229, chinese:'歌手',            pinyin:'gē shǒu',       english:'singer; vocalist'},
{no:230, chinese:'个人',            pinyin:'gèrén',         english:'personal'},
{no:231, chinese:'个性',            pinyin:'gèxìng',        english:'personality'},
{no:232, chinese:'各',              pinyin:'gè',            english:'various'},
{no:233, chinese:'各地',            pinyin:'gè dì',         english:'various regions; everywhere'},
{no:234, chinese:'各位',            pinyin:'gè wèi',        english:'everybody'},
{no:235, chinese:'各种',            pinyin:'gè zhǒng',      english:'all kinds; various; every kind'},
{no:236, chinese:'各自',            pinyin:'gèzì',          english:'Each'},
{no:237, chinese:'根本',            pinyin:'gēnběn',        english:'at all'},
{no:238, chinese:'更加',            pinyin:'gèng jiā',      english:'more; even more'},
{no:239, chinese:'工厂',            pinyin:'gōngchǎng',     english:'factory'},
{no:240, chinese:'工程师',           pinyin:'gōngchéngshī',  english:'Engineer'},
{no:241, chinese:'工夫',            pinyin:'gōng fu',       english:'time'},
{no:242, chinese:'工具',            pinyin:'gōngjù',        english:'tool'},
{no:243, chinese:'工业',            pinyin:'gōngyè',        english:'Industry'},
{no:244, chinese:'工资',            pinyin:'gōngzī',        english:'wages'},
{no:245, chinese:'公布',            pinyin:'gōngbù',        english:'Publish'},
{no:246, chinese:'公共',            pinyin:'gōng gòng',     english:'public; common; community'},
{no:247, chinese:'公开',            pinyin:'gōngkāi',       english:'open'},
{no:248, chinese:'公民',            pinyin:'gōngmín',       english:'citizen'},
{no:249, chinese:'公务员',           pinyin:'gōng wù yuán',  english:'civil servant; public functionary'},
{no:250, chinese:'功夫',            pinyin:'gōngfu',        english:'Kungfu'},
{no:251, chinese:'功课', pinyin:'gōngkè', english:'homework; schoolwork; classwork'},
{no:252, chinese:'功能', pinyin:'gōngnéng', english:'function'},
{no:253, chinese:'共同', pinyin:'gòngtóng', english:'common'},
{no:254, chinese:'共有', pinyin:'gòngyǒu', english:'have altogether; share'},
{no:255, chinese:'姑娘', pinyin:'gūniang', english:'girl'},
{no:256, chinese:'古', pinyin:'gǔ', english:'ancient; old'},
{no:257, chinese:'古代', pinyin:'gǔdài', english:'Ancient'},
{no:258, chinese:'故乡', pinyin:'gùxiāng', english:'Hometown'},
{no:259, chinese:'挂', pinyin:'guà', english:'hang'},
{no:260, chinese:'关系', pinyin:'guānxì', english:'relationship'},
{no:261, chinese:'关注', pinyin:'guānzhù', english:'attention; follow with interest'},
{no:262, chinese:'观察', pinyin:'guānchá', english:'observation'},
{no:263, chinese:'观看', pinyin:'guānkàn', english:'watch; view'},
{no:264, chinese:'观念', pinyin:'guānniàn', english:'concept'},
{no:265, chinese:'观众', pinyin:'guānzhòng', english:'Audience'},
{no:266, chinese:'管', pinyin:'guǎn', english:'manage'},
{no:267, chinese:'管理', pinyin:'guǎnlǐ', english:'Administration'},
{no:268, chinese:'光', pinyin:'guāng', english:'light'},
{no:269, chinese:'光明', pinyin:'guāngmíng', english:'light'},
{no:270, chinese:'广播', pinyin:'guǎngbō', english:'Radio broadcast'},
{no:271, chinese:'广大', pinyin:'guǎngdà', english:'Vast'},
{no:272, chinese:'规定', pinyin:'guīdìng', english:'Regulations'},
{no:273, chinese:'规范', pinyin:'guīfàn', english:'criterion; rule'},
{no:274, chinese:'国内', pinyin:'guónèi', english:'domestic; internal'},
{no:275, chinese:'国庆', pinyin:'guóqìng', english:'National Day'},
{no:276, chinese:'果然', pinyin:'guǒrán', english:'Sure enough'},
{no:277, chinese:'果汁', pinyin:'guǒzhī', english:'fruit juice'},
{no:278, chinese:'过程', pinyin:'guòchéng', english:'process'},
{no:279, chinese:'过去', pinyin:'guòqù', english:'past; old; foretime'},
{no:280, chinese:'哈哈', pinyin:'hāhā', english:'ha-ha'},
{no:281, chinese:'海关', pinyin:'hǎiguān', english:'Customs'},
{no:282, chinese:'害怕', pinyin:'hàipà', english:'Fear'},
{no:283, chinese:'行', pinyin:'háng', english:'row, line'},
{no:284, chinese:'好好', pinyin:'hǎohǎo', english:'really good, really nice'},
{no:285, chinese:'好奇', pinyin:'hàoqí', english:'Be curious'},
{no:286, chinese:'合', pinyin:'hé', english:'close; shut; join'},
{no:287, chinese:'合法', pinyin:'héfǎ', english:'legitimate'},
{no:288, chinese:'合格', pinyin:'hégé', english:'qualified'},
{no:289, chinese:'合理', pinyin:'hélǐ', english:'reasonable'},
{no:290, chinese:'合作', pinyin:'hézuò', english:'cooperation'},
{no:291, chinese:'和平', pinyin:'hépíng', english:'peace'},
{no:292, chinese:'红茶', pinyin:'hóngchá', english:'black tea'},
{no:293, chinese:'红酒', pinyin:'hóngjiǔ', english:'red wine'},
{no:294, chinese:'后果', pinyin:'hòuguǒ', english:'Consequence'},
{no:295, chinese:'后面', pinyin:'hòumiàn', english:'behind'},
{no:296, chinese:'后年', pinyin:'hòunián', english:'the year after next'},
{no:297, chinese:'互联网', pinyin:'hùliánwǎng', english:'Internet'},
{no:298, chinese:'互相', pinyin:'hùxiāng', english:'each other'},
{no:299, chinese:'划船', pinyin:'huáchuán', english:'row; paddle a boat'},
{no:300, chinese:'华人', pinyin:'huárén', english:'Chinese; ethnic Chinese'},
{no:301, chinese:'化', pinyin:'huà', english:'-ize / -ization'},
{no:302, chinese:'话剧', pinyin:'huàjù', english:'drama'},
{no:303, chinese:'话题', pinyin:'huàtí', english:'Topic of conversation'},
{no:304, chinese:'欢乐', pinyin:'huānlè', english:'Happy'},
{no:305, chinese:'环', pinyin:'huán', english:'ring; loop'},
{no:306, chinese:'环保', pinyin:'huánbǎo', english:'environmental protection'},
{no:307, chinese:'环境', pinyin:'huánjìng', english:'Environment'},
{no:308, chinese:'会议', pinyin:'huìyì', english:'Meeting'},
{no:309, chinese:'会员', pinyin:'huìyuán', english:'membership'},
{no:310, chinese:'活', pinyin:'huó', english:'live; alive'},
{no:311, chinese:'火', pinyin:'huǒ', english:'fire; anger'},
{no:312, chinese:'机器', pinyin:'jīqì', english:'machine'},
{no:313, chinese:'积极', pinyin:'jījí', english:'positive'},
{no:314, chinese:'基本', pinyin:'jīběn', english:'basic'},
{no:315, chinese:'基本上', pinyin:'jīběnshang', english:'basically'},
{no:316, chinese:'基础', pinyin:'jīchǔ', english:'Basics'},
{no:317, chinese:'及时', pinyin:'jíshí', english:'timely'},
{no:318, chinese:'…极了', pinyin:'…jíle', english:'extremely'},
{no:319, chinese:'集体', pinyin:'jítǐ', english:'collective'},
{no:320, chinese:'集中', pinyin:'jízhōng', english:'focus'},
{no:321, chinese:'计算', pinyin:'jìsuàn', english:'Calculation'},
{no:322, chinese:'记录', pinyin:'jìlù', english:'Record'},
{no:323, chinese:'记者', pinyin:'jìzhě', english:'Reporter'},
{no:324, chinese:'纪录', pinyin:'jìlù', english:'Record'},
{no:325, chinese:'纪念', pinyin:'jìniàn', english:'Anniversary'},
{no:326, chinese:'技术', pinyin:'jìshù', english:'technology'},
{no:327, chinese:'继续', pinyin:'jìxù', english:'Continue'},
{no:328, chinese:'加工', pinyin:'jiāgōng', english:'machining'},
{no:329, chinese:'加快', pinyin:'jiākuài', english:'speed up'},
{no:330, chinese:'加强', pinyin:'jiāqiáng', english:'strengthen'},
{no:331, chinese:'家具', pinyin:'jiājù', english:'furniture'},
{no:332, chinese:'家属', pinyin:'jiāshǔ', english:'family members'},
{no:333, chinese:'家乡', pinyin:'jiāxiāng', english:'Hometown'},
{no:334, chinese:'价格', pinyin:'jiàgé', english:'Price'},
{no:335, chinese:'价钱', pinyin:'jiàqián', english:'price'},
{no:336, chinese:'价值', pinyin:'jiàzhí', english:'value'},
{no:337, chinese:'架', pinyin:'jià', english:'frame; rack'},
{no:338, chinese:'坚持', pinyin:'jiānchí', english:'Insist'},
{no:339, chinese:'坚决', pinyin:'jiānjué', english:'firm'},
{no:340, chinese:'坚强', pinyin:'jiānqiáng', english:'Firm'},
{no:341, chinese:'简单', pinyin:'jiǎndān', english:'simple'},
{no:342, chinese:'简直', pinyin:'jiǎnzhí', english:'simply'},
{no:343, chinese:'建', pinyin:'jiàn', english:'build; construct'},
{no:344, chinese:'建成', pinyin:'jiànchéng', english:'built up'},
{no:345, chinese:'建立', pinyin:'jiànlì', english:'establish'},
{no:346, chinese:'建设', pinyin:'jiànshè', english:'build'},
{no:347, chinese:'建议', pinyin:'jiànyì', english:'proposal'},
{no:348, chinese:'将近', pinyin:'jiāngjìn', english:'nearly'},
{no:349, chinese:'将来', pinyin:'jiānglái', english:'future'},
{no:350, chinese:'交费', pinyin:'jiāofèi', english:'pay'},
{no:351, chinese:'交警', pinyin:'jiāojǐng', english:'traffic police'},
{no:352, chinese:'交流', pinyin:'jiāoliú', english:'Communication'},
{no:353, chinese:'交往', pinyin:'jiāowǎng', english:'affiliate with'},
{no:354, chinese:'交易', pinyin:'jiāoyì', english:'transaction'},
{no:355, chinese:'叫', pinyin:'jiào', english:'(preposition)'},
{no:356, chinese:'较', pinyin:'jiào', english:'compare'},
{no:357, chinese:'教材', pinyin:'jiàocái', english:'teaching material'},
{no:358, chinese:'教练', pinyin:'jiàoliàn', english:'coach'},
{no:359, chinese:'结实', pinyin:'jiēshi', english:'strong'},
{no:360, chinese:'接待', pinyin:'jiēdài', english:'Reception'},
{no:361, chinese:'接近', pinyin:'jiējìn', english:'near'},
{no:362, chinese:'节约', pinyin:'jiéyuē', english:'save'},
{no:363, chinese:'结合', pinyin:'jiéhé', english:'Combination'},
{no:364, chinese:'结婚', pinyin:'jiéhūn', english:'marry'},
{no:365, chinese:'结束', pinyin:'jiéshù', english:'End'},
{no:366, chinese:'解决', pinyin:'jiějué', english:'Solve'},
{no:367, chinese:'解开', pinyin:'jiěkāi', english:'undo; untie'},
{no:368, chinese:'金', pinyin:'jīn', english:'gold'},
{no:369, chinese:'金牌', pinyin:'jīnpái', english:'gold medal'},
{no:370, chinese:'仅', pinyin:'jǐn', english:'only'},
{no:371, chinese:'仅仅', pinyin:'jǐnjǐn', english:'only'},
{no:372, chinese:'尽量', pinyin:'jǐnliàng', english:'as far as possible'},
{no:373, chinese:'紧', pinyin:'jǐn', english:'tight'},
{no:374, chinese:'紧急', pinyin:'jǐnjí', english:'urgent'},
{no:375, chinese:'紧张', pinyin:'jǐnzhāng', english:'Nervous'},
{no:376, chinese:'进步', pinyin:'jìnbù', english:'progress'},
{no:377, chinese:'进一步', pinyin:'jìnyíbù', english:'further'},
{no:378, chinese:'进展', pinyin:'jìnzhǎn', english:'evolve'},
{no:379, chinese:'近期', pinyin:'jìnqī', english:'recent'},
{no:380, chinese:'京剧', pinyin:'jīngjù', english:'Beijing opera'},
{no:381, chinese:'经济', pinyin:'jīngjì', english:'Economics'},
{no:382, chinese:'经历', pinyin:'jīnglì', english:'experience'},
{no:383, chinese:'经验', pinyin:'jīngyàn', english:'experience'},
{no:384, chinese:'经营', pinyin:'jīngyíng', english:'Management'},
{no:385, chinese:'精彩', pinyin:'jīngcǎi', english:'Marvellous'},
{no:386, chinese:'精神', pinyin:'jīngshén', english:'spirit, mind'},
{no:387, chinese:'精神', pinyin:'jīngshen', english:'lively, vigour'},
{no:388, chinese:'景色', pinyin:'jǐngsè', english:'scenery'},
{no:389, chinese:'警察', pinyin:'jǐngchá', english:'Police'},
{no:390, chinese:'静', pinyin:'jìng', english:'silent; quiet; calm'},
{no:391, chinese:'久', pinyin:'jiǔ', english:'long'},
{no:392, chinese:'旧', pinyin:'jiù', english:'used'},
{no:393, chinese:'救', pinyin:'jiù', english:'save'},
{no:394, chinese:'就是', pinyin:'jiùshì', english:'precisely; exactly'},
{no:395, chinese:'就业', pinyin:'jiùyè', english:'take up an occupation'},
{no:396, chinese:'举办', pinyin:'jǔbàn', english:'hold'},
{no:397, chinese:'具体', pinyin:'jùtǐ', english:'specific'},
{no:398, chinese:'具有', pinyin:'jùyǒu', english:'possess; have'},
{no:399, chinese:'剧场', pinyin:'jùchǎng', english:'theater'},
{no:400, chinese:'据说', pinyin:'jùshuō', english:'allegedly'},
{no:401, chinese:'决定', pinyin:'juédìng', english:'Decision'},
{no:402, chinese:'决赛', pinyin:'juésài', english:'Finals'},
{no:403, chinese:'决心', pinyin:'juéxīn', english:'Determination'},
{no:404, chinese:'绝对', pinyin:'juéduì', english:'Absolutely'},
{no:405, chinese:'咖啡', pinyin:'kāfēi', english:'Coffee'},
{no:406, chinese:'开发', pinyin:'kāifā', english:'Development'},
{no:407, chinese:'开放', pinyin:'kāifàng', english:'To open up'},
{no:408, chinese:'开始', pinyin:'kāishǐ', english:'start'},
{no:409, chinese:'开业', pinyin:'kāiyè', english:'start business'},
{no:410, chinese:'开展', pinyin:'kāizhǎn', english:'Develop'},
{no:411, chinese:'看起来', pinyin:'kànqǐlai', english:'look like'},
{no:412, chinese:'看上去', pinyin:'kànshàngqù', english:'seem'},
{no:413, chinese:'考验', pinyin:'kǎoyàn', english:'test'},
{no:414, chinese:'科技', pinyin:'kējì', english:'science and technology'},
{no:415, chinese:'可靠', pinyin:'kěkào', english:'reliable'},
{no:416, chinese:'可乐', pinyin:'kělè', english:'coke; cola'},
{no:417, chinese:'克服', pinyin:'kèfú', english:'Overcome'},
{no:418, chinese:'客观', pinyin:'kèguān', english:'objective'},
{no:419, chinese:'课程', pinyin:'kèchéng', english:'curriculum'},
{no:420, chinese:'空', pinyin:'kōng', english:'empty'},
{no:421, chinese:'空调', pinyin:'kōngtiáo', english:'Air conditioner'},
{no:422, chinese:'恐怕', pinyin:'kǒngpà', english:'I’m afraid'},
{no:423, chinese:'空儿', pinyin:'kòngr', english:'free time'},
{no:424, chinese:'裤子', pinyin:'kùzi', english:'trousers'},
{no:425, chinese:'快速', pinyin:'kuàisù', english:'fast'},
{no:426, chinese:'困', pinyin:'kùn', english:'sleepy'},
{no:427, chinese:'困难', pinyin:'kùnnán', english:'difficulty'},
{no:428, chinese:'浪费', pinyin:'làngfèi', english:'Waste'},
{no:429, chinese:'老百姓', pinyin:'lǎobǎixìng', english:'Ordinary people'},
{no:430, chinese:'老板', pinyin:'lǎobǎn', english:'Boss'},
{no:431, chinese:'老太太', pinyin:'lǎotàitai', english:'old lady'},
{no:432, chinese:'老头儿', pinyin:'lǎotóur', english:'old man'},
{no:433, chinese:'乐', pinyin:'lè', english:'happy; laugh'},
{no:434, chinese:'乐观', pinyin:'lèguān', english:'optimistic'},
{no:435, chinese:'类', pinyin:'lèi', english:'class; kind'},
{no:436, chinese:'类似', pinyin:'lèisì', english:'Similar'},
{no:437, chinese:'离婚', pinyin:'líhūn', english:'divorce'},
{no:438, chinese:'里面', pinyin:'lǐmiàn', english:'inside'},
{no:439, chinese:'理发', pinyin:'lǐfà', english:'Haircut'},
{no:440, chinese:'理解', pinyin:'lǐjiě', english:'Understand'},
{no:441, chinese:'理论', pinyin:'lǐlùn', english:'theory'},
{no:442, chinese:'理由', pinyin:'lǐyóu', english:'Reason'},
{no:443, chinese:'力', pinyin:'lì', english:'power; force'},
{no:444, chinese:'力量', pinyin:'lìliàng', english:'Power'},
{no:445, chinese:'立刻', pinyin:'lìkè', english:'immediately'},
{no:446, chinese:'利用', pinyin:'lìyòng', english:'utilize'},
{no:447, chinese:'连', pinyin:'lián', english:'even'},
{no:448, chinese:'连忙', pinyin:'liánmáng', english:'Hurriedly'},
{no:449, chinese:'连续', pinyin:'liánxù', english:'serial'},
{no:450, chinese:'连续剧', pinyin:'liánxùjù', english:'series; soap opera'},
{no:451, chinese:'联合', pinyin:'liánhé', english:'union'},
{no:452, chinese:'联合国', pinyin:'liánhéguó', english:'United Nations'},
{no:453, chinese:'联系', pinyin:'liánxì', english:'contact'},
{no:454, chinese:'凉水', pinyin:'liángshuǐ', english:'cold water'},
{no:455, chinese:'了', pinyin:'le', english:'past tense marker'},
{no:456, chinese:'领', pinyin:'lǐng', english:'lead; receive'},
{no:457, chinese:'领导', pinyin:'lǐngdǎo', english:'Leader'},
{no:458, chinese:'领先', pinyin:'lǐngxiān', english:'keep ahead'},
{no:459, chinese:'另外', pinyin:'lìngwài', english:'in addition'},
{no:460, chinese:'另一方面', pinyin:'lìngyìfāngmiàn', english:'on the other hand'},
{no:461, chinese:'留学', pinyin:'liúxué', english:'Overseas Study'},
{no:462, chinese:'龙', pinyin:'lóng', english:'dragon'},
{no:463, chinese:'录', pinyin:'lù', english:'record'},
{no:464, chinese:'录音', pinyin:'lùyīn', english:'Sound recording'},
{no:465, chinese:'路线', pinyin:'lùxiàn', english:'path; route'},
{no:466, chinese:'旅馆', pinyin:'lǚguǎn', english:'hotel'},
{no:467, chinese:'旅行社', pinyin:'lǚxíngshè', english:'travel agency'},
{no:468, chinese:'绿茶', pinyin:'lǜchá', english:'green tea'},
{no:469, chinese:'乱', pinyin:'luàn', english:'chaos'},
{no:470, chinese:'落后', pinyin:'luòhòu', english:'backward'},
{no:471, chinese:'麻烦', pinyin:'máfan', english:'trouble'},
{no:472, chinese:'马', pinyin:'mǎ', english:'Horse'},
{no:473, chinese:'满足', pinyin:'mǎnzú', english:'satisfy'},
{no:474, chinese:'慢慢', pinyin:'mànmàn', english:'slowly'},
{no:475, chinese:'毛', pinyin:'máo', english:'hair; fur; dime'},
{no:476, chinese:'毛病', pinyin:'máobìng', english:'Trouble'},
{no:477, chinese:'没用', pinyin:'méiyòng', english:'useless'},
{no:478, chinese:'媒体', pinyin:'méitǐ', english:'media'},
{no:479, chinese:'每', pinyin:'měi', english:'each'},
{no:480, chinese:'美', pinyin:'měi', english:'beautiful'},
{no:481, chinese:'美好', pinyin:'měihǎo', english:'fine; happy'},
{no:482, chinese:'美丽', pinyin:'měilì', english:'beautiful'},
{no:483, chinese:'美食', pinyin:'měishí', english:'delicious food; gourmet'},
{no:484, chinese:'美术', pinyin:'měishù', english:'Fine Arts'},
{no:485, chinese:'美元', pinyin:'měiyuán', english:'U.S. dollar'},
{no:486, chinese:'迷', pinyin:'mí', english:'fan; confused'},
{no:487, chinese:'米', pinyin:'mǐ', english:'meter; rice'},
{no:488, chinese:'面对', pinyin:'miànduì', english:'Face'},
{no:489, chinese:'面积', pinyin:'miànjī', english:'The measure of area'},
{no:490, chinese:'民间', pinyin:'mínjiān', english:'nongovernmental'},
{no:491, chinese:'民族', pinyin:'mínzú', english:'Nation'},
{no:492, chinese:'明确', pinyin:'míngquè', english:'To make clear'},
{no:493, chinese:'明显', pinyin:'míngxiǎn', english:'obvious'},
{no:494, chinese:'命运', pinyin:'mìngyùn', english:'fate'},
{no:495, chinese:'某', pinyin:'mǒu', english:'some'},
{no:496, chinese:'母亲', pinyin:'mǔqīn', english:'mother'},
{no:497, chinese:'木头', pinyin:'mùtou', english:'wood'},
{no:498, chinese:'目标', pinyin:'mùbiāo', english:'target'},
{no:499, chinese:'目前', pinyin:'mùqián', english:'at present'},
{no:500, chinese:'奶茶', pinyin:'nǎichá', english:'milk tea'},
{no:501, chinese:'男子', pinyin:'nánzǐ', english:'man; male'},
{no:502, chinese:'南部', pinyin:'nánbù', english:'south'},
{no:503, chinese:'难道', pinyin:'nándào', english:'could it be said that …'},
{no:504, chinese:'难度', pinyin:'nándù', english:'difficulty'},
{no:505, chinese:'内', pinyin:'nèi', english:'within'},
{no:506, chinese:'内容', pinyin:'nèiróng', english:'content'},
{no:507, chinese:'内心', pinyin:'nèixīn', english:'heart; inner centre'},
{no:508, chinese:'能不能', pinyin:'néngbunéng', english:'can or not'},
{no:509, chinese:'能力', pinyin:'nénglì', english:'ability'},
{no:510, chinese:'年初', pinyin:'niánchū', english:'beginning of the year'},
{no:511, chinese:'年代', pinyin:'niándài', english:'years'},
{no:512, chinese:'年底', pinyin:'niándǐ', english:'end of the year'},
{no:513, chinese:'年纪', pinyin:'niánjì', english:'Age'},
{no:514, chinese:'念', pinyin:'niàn', english:'Read'},
{no:515, chinese:'牛', pinyin:'niú', english:'cattle; ox; cow'},
{no:516, chinese:'农村', pinyin:'nóngcūn', english:'countryside'},
{no:517, chinese:'农民', pinyin:'nóngmín', english:'farmer'},
{no:518, chinese:'农业', pinyin:'nóngyè', english:'Agriculture'},
{no:519, chinese:'女子', pinyin:'nǚzǐ', english:'woman; female'},
{no:520, chinese:'暖和', pinyin:'nuǎnhuo', english:'warm'},
{no:521, chinese:'怕', pinyin:'pà', english:'perhaps; afraid'},
{no:522, chinese:'拍', pinyin:'pāi', english:'beat'},
{no:523, chinese:'排', pinyin:'pái', english:'arrange; rehearse'},
{no:524, chinese:'排名', pinyin:'páimíng', english:'rank'},
{no:525, chinese:'牌子', pinyin:'páizi', english:'brand; sign'},
{no:526, chinese:'派', pinyin:'pài', english:'send'},
{no:527, chinese:'判断', pinyin:'pànduàn', english:'judge'},
{no:528, chinese:'胖', pinyin:'pàng', english:'fat'},
{no:529, chinese:'跑步', pinyin:'pǎobù', english:'Run'},
{no:530, chinese:'配', pinyin:'pèi', english:'match; fit'},
{no:531, chinese:'配合', pinyin:'pèihé', english:'Coordination'},
{no:532, chinese:'批评', pinyin:'pīpíng', english:'criticism'},
{no:533, chinese:'批准', pinyin:'pīzhǔn', english:'Approval'},
{no:534, chinese:'皮', pinyin:'pí', english:'skin; leather'},
{no:535, chinese:'皮包', pinyin:'píbāo', english:'purse; briefcase'},
{no:536, chinese:'啤酒', pinyin:'píjiǔ', english:'Beer'},
{no:537, chinese:'票价', pinyin:'piàojià', english:'ticket price'},
{no:538, chinese:'评价', pinyin:'píngjià', english:'evaluation'},
{no:539, chinese:'苹果', pinyin:'píngguǒ', english:'Apple'},
{no:540, chinese:'破', pinyin:'pò', english:'broken'},
{no:541, chinese:'破坏', pinyin:'pòhuài', english:'Destruction'},
{no:542, chinese:'普遍', pinyin:'pǔbiàn', english:'universal'},
{no:543, chinese:'普及', pinyin:'pǔjí', english:'Universal'},
{no:544, chinese:'期', pinyin:'qī', english:'period; term'},
{no:545, chinese:'齐', pinyin:'qí', english:'together; neat'},
{no:546, chinese:'其次', pinyin:'qícì', english:'Secondly'},
{no:547, chinese:'其实', pinyin:'qíshí', english:'actually'},
{no:548, chinese:'奇怪', pinyin:'qíguài', english:'strange'},
{no:549, chinese:'气候', pinyin:'qìhòu', english:'climate'},
{no:550, chinese:'千万', pinyin:'qiānwàn', english:'Must'},
{no:551, chinese:'前后', pinyin:'qiánhòu', english:'front and back; around'},
{no:552, chinese:'前进', pinyin:'qiánjìn', english:'advance'},
{no:553, chinese:'前面', pinyin:'qiánmiàn', english:'Front'},
{no:554, chinese:'前往', pinyin:'qiánwǎng', english:'go to; leave for'},
{no:555, chinese:'强', pinyin:'qiáng', english:'strong; powerful'},
{no:556, chinese:'强大', pinyin:'qiángdà', english:'powerful; formidable'},
{no:557, chinese:'强调', pinyin:'qiángdiào', english:'Emphasize'},
{no:558, chinese:'强烈', pinyin:'qiángliè', english:'strong'},
{no:559, chinese:'桥', pinyin:'qiáo', english:'Bridge'},
{no:560, chinese:'巧', pinyin:'qiǎo', english:'opportunely; skilful'},
{no:561, chinese:'亲', pinyin:'qīn', english:'dear; close; relative'},
{no:562, chinese:'亲切', pinyin:'qīnqiè', english:'kind'},
{no:563, chinese:'亲人', pinyin:'qīnrén', english:'relative'},
{no:564, chinese:'亲自', pinyin:'qīnzì', english:'personally'},
{no:565, chinese:'情感', pinyin:'qínggǎn', english:'feeling; emotion'},
{no:566, chinese:'情况', pinyin:'qíngkuàng', english:'Situation'},
{no:567, chinese:'请教', pinyin:'qǐngjiào', english:'Consult'},
{no:568, chinese:'庆祝', pinyin:'qìngzhù', english:'Celebrate'},
{no:569, chinese:'球迷', pinyin:'qiúmí', english:'fans (ball game)'},
{no:570, chinese:'区', pinyin:'qū', english:'area; district'},
{no:571, chinese:'区别', pinyin:'qūbié', english:'Difference'},
{no:572, chinese:'取消', pinyin:'qǔxiāo', english:'cancel'},
{no:573, chinese:'去世', pinyin:'qùshì', english:'Death'},
{no:574, chinese:'全场', pinyin:'quánchǎng', english:'the whole audience'},
{no:575, chinese:'全面', pinyin:'quánmiàn', english:'comprehensive'},
{no:576, chinese:'全球', pinyin:'quánqiú', english:'global; the whole world'},
{no:577, chinese:'缺', pinyin:'quē', english:'be short of; lack'},
{no:578, chinese:'缺点', pinyin:'quēdiǎn', english:'shortcoming'},
{no:579, chinese:'缺少', pinyin:'quēshǎo', english:'Lack'},
{no:580, chinese:'确保', pinyin:'quèbǎo', english:'ensure'},
{no:581, chinese:'确定', pinyin:'quèdìng', english:'Determine'},
{no:582, chinese:'确实', pinyin:'quèshí', english:'Exactly'},
{no:583, chinese:'裙子', pinyin:'qúnzi', english:'skirt'},
{no:584, chinese:'群', pinyin:'qún', english:'group'},
{no:585, chinese:'热爱', pinyin:'rè’ài', english:'Ardently love'},
{no:586, chinese:'热烈', pinyin:'rèliè', english:'warm'},
{no:587, chinese:'人才', pinyin:'réncái', english:'talented person'},
{no:588, chinese:'人工', pinyin:'réngōng', english:'artificial'},
{no:589, chinese:'人类', pinyin:'rénlèi', english:'Human beings'},
{no:590, chinese:'人民', pinyin:'rénmín', english:'people'},
{no:591, chinese:'人民币', pinyin:'rénmínbì', english:'RMB'},
{no:592, chinese:'人群', pinyin:'rénqún', english:'crowd; throng'},
{no:593, chinese:'人生', pinyin:'rénshēng', english:'Life'},
{no:594, chinese:'人员', pinyin:'rényuán', english:'personnel'},
{no:595, chinese:'认出', pinyin:'rènchū', english:'recognize; identify'},
{no:596, chinese:'认得', pinyin:'rèndé', english:'know; recognize'},
{no:597, chinese:'认可', pinyin:'rènkě', english:'certificate; ratify'},
{no:598, chinese:'任', pinyin:'rèn', english:'appoint; assign'},
{no:599, chinese:'任', pinyin:'rèn', english:'no matter (how, what, etc.)'},
{no:600, chinese:'任何', pinyin:'rènhé', english:'whatever, any'},
{no:601, chinese:'任务', pinyin:'rènwu', english:'task'},
{no:602, chinese:'仍', pinyin:'réng', english:'still; remain'},
{no:603, chinese:'仍然', pinyin:'réngrán', english:'still'},
{no:604, chinese:'日常', pinyin:'rìcháng', english:'daily'},
{no:605, chinese:'容易', pinyin:'róngyì', english:'easily'},
{no:606, chinese:'如何', pinyin:'rúhé', english:'How'},
{no:607, chinese:'散步', pinyin:'sànbù', english:'Take a walk'},
{no:608, chinese:'沙发', pinyin:'shāfā', english:'Sofa'},
{no:609, chinese:'沙子', pinyin:'shāzi', english:'sand; grit'},
{no:610, chinese:'伤', pinyin:'shāng', english:'hurt; be harmful'},
{no:611, chinese:'伤心', pinyin:'shāngxīn', english:'Sad'},
{no:612, chinese:'商品', pinyin:'shāngpǐn', english:'commodity'},
{no:613, chinese:'商业', pinyin:'shāngyè', english:'business'},
{no:614, chinese:'上来', pinyin:'shànglái', english:'come up'},
{no:615, chinese:'上面', pinyin:'shàngmiàn', english:'above; on top of'},
{no:616, chinese:'上去', pinyin:'shàngqù', english:'go up'},
{no:617, chinese:'上升', pinyin:'shàngshēng', english:'rise; go up'},
{no:618, chinese:'上衣', pinyin:'shàngyī', english:'upper garment; jacket'},
{no:619, chinese:'设备', pinyin:'shèbèi', english:'equipment'},
{no:620, chinese:'设计', pinyin:'shèjì', english:'Design'},
{no:621, chinese:'设立', pinyin:'shèlì', english:'Establish'},
{no:622, chinese:'社会', pinyin:'shèhuì', english:'Society'},
{no:623, chinese:'身份证', pinyin:'shēnfènzhèng', english:'ID card'},
{no:624, chinese:'深', pinyin:'shēn', english:'deep'},
{no:625, chinese:'深刻', pinyin:'shēnkè', english:'profound'},
{no:626, chinese:'深入', pinyin:'shēnrù', english:'go deep into; thorough'},
{no:627, chinese:'升', pinyin:'shēng', english:'rise'},
{no:628, chinese:'生', pinyin:'shēng', english:'unripe; raw; unfamiliar'},
{no:629, chinese:'生产', pinyin:'shēngchǎn', english:'production'},
{no:630, chinese:'生存', pinyin:'shēngcún', english:'Existence'},
{no:631, chinese:'生动', pinyin:'shēngdòng', english:'vivid'},
{no:632, chinese:'生命', pinyin:'shēngmìng', english:'life'},
{no:633, chinese:'生意', pinyin:'shēngyi', english:'business'},
{no:634, chinese:'生长', pinyin:'shēngzhǎng', english:'grow'},
{no:635, chinese:'声明', pinyin:'shēngmíng', english:'statement'},
{no:636, chinese:'胜', pinyin:'shèng', english:'win; defeat'},
{no:637, chinese:'胜利', pinyin:'shènglì', english:'victory'},
{no:638, chinese:'失去', pinyin:'shīqù', english:'Lose'},
{no:639, chinese:'石头', pinyin:'shítou', english:'stone'},
{no:640, chinese:'石油', pinyin:'shíyóu', english:'petroleum'},
{no:641, chinese:'时', pinyin:'shí', english:'time; hour; season'},
{no:642, chinese:'时代', pinyin:'shídài', english:'times'},
{no:643, chinese:'时刻', pinyin:'shíkè', english:'time'},
{no:644, chinese:'实际上', pinyin:'shíjìshang', english:'actually'},
{no:645, chinese:'实力', pinyin:'shílì', english:'Strength'},
{no:646, chinese:'实行', pinyin:'shíxíng', english:'Implement'},
{no:647, chinese:'实验', pinyin:'shíyàn', english:'Experiment'},
{no:648, chinese:'实验室', pinyin:'shíyànshì', english:'laboratory'},
{no:649, chinese:'食品', pinyin:'shípǐn', english:'food; foodstuff'},
{no:650, chinese:'使', pinyin:'shǐ', english:'make'},
{no:651, chinese:'始终', pinyin:'shǐzhōng', english:'Throughout'},
{no:652, chinese:'世纪', pinyin:'shìjì', english:'century'},
{no:653, chinese:'世界', pinyin:'shìjiè', english:'world'},
{no:654, chinese:'世界杯', pinyin:'shìjièbēi', english:'World Cup'},
{no:655, chinese:'市场', pinyin:'shìchǎng', english:'market'},
{no:656, chinese:'事故', pinyin:'shìgù', english:'Accident'},
{no:657, chinese:'事件', pinyin:'shìjiàn', english:'Event'},
{no:658, chinese:'事实', pinyin:'shìshí', english:'Fact'},
{no:659, chinese:'事实上', pinyin:'shìshíshang', english:'in fact; actually'},
{no:660, chinese:'事业', pinyin:'shìyè', english:'career'},
{no:661, chinese:'试题', pinyin:'shìtí', english:'test questions'},
{no:662, chinese:'试验', pinyin:'shìyàn', english:'test'},
{no:663, chinese:'适合', pinyin:'shìhé', english:'Fit'},
{no:664, chinese:'适应', pinyin:'shìyìng', english:'Adapt'},
{no:665, chinese:'适用', pinyin:'shìyòng', english:'be applicable; suitable'},
{no:666, chinese:'室', pinyin:'shì', english:'room'},
{no:667, chinese:'收费', pinyin:'shōufèi', english:'collect fees; charge'},
{no:668, chinese:'收看', pinyin:'shōukàn', english:'watch'},
{no:669, chinese:'收听', pinyin:'shōutīng', english:'listen to; listen in'},
{no:670, chinese:'收音机', pinyin:'shōuyīnjī', english:'radio'},
{no:671, chinese:'手续', pinyin:'shǒuxù', english:'procedures'},
{no:672, chinese:'手指', pinyin:'shǒuzhǐ', english:'finger'},
{no:673, chinese:'首都', pinyin:'shǒudū', english:'capital'},
{no:674, chinese:'首先', pinyin:'shǒuxiān', english:'First'},
{no:675, chinese:'受', pinyin:'shòu', english:'be subjected; suffer; receive'},
{no:676, chinese:'受伤', pinyin:'shòushāng', english:'Injured'},
{no:677, chinese:'书架', pinyin:'shūjià', english:'bookshelf'},
{no:678, chinese:'输', pinyin:'shū', english:'lose'},
{no:679, chinese:'输入', pinyin:'shūrù', english:'import; input'},
{no:680, chinese:'熟人', pinyin:'shúrén', english:'acquaintance'},
{no:681, chinese:'属', pinyin:'shǔ', english:'belong to; be born in the year of'},
{no:682, chinese:'属于', pinyin:'shǔyú', english:'belong to'},
{no:683, chinese:'束', pinyin:'shù', english:'beam; bunch'},
{no:684, chinese:'数量', pinyin:'shùliàng', english:'quantity'},
{no:685, chinese:'双', pinyin:'shuāng', english:'double'},
{no:686, chinese:'双方', pinyin:'shuāngfāng', english:'both sides'},
{no:687, chinese:'思想', pinyin:'sīxiǎng', english:'thought'},
{no:688, chinese:'死', pinyin:'sǐ', english:'die'},
{no:689, chinese:'速度', pinyin:'sùdù', english:'speed'},
{no:690, chinese:'随', pinyin:'suí', english:'follow; comply with'},
{no:691, chinese:'所', pinyin:'suǒ', english:'place; office; (measure word)'},
{no:692, chinese:'所长', pinyin:'suǒzhǎng', english:'superintendent'},
{no:693, chinese:'台', pinyin:'tái', english:'platform'},
{no:694, chinese:'谈', pinyin:'tán', english:'talk'},
{no:695, chinese:'谈话', pinyin:'tánhuà', english:'conversation; talk'},
{no:696, chinese:'谈判', pinyin:'tánpàn', english:'negotiation'},
{no:697, chinese:'汤', pinyin:'tāng', english:'soup'},
{no:698, chinese:'糖', pinyin:'táng', english:'sugar'},
{no:699, chinese:'特色', pinyin:'tèsè', english:'characteristic'},
{no:700, chinese:'提前', pinyin:'tíqián', english:'Advance'},
{no:701, chinese:'提问', pinyin:'tíwèn', english:'Put questions to'},
{no:702, chinese:'题目', pinyin:'tímù', english:'subject'},
{no:703, chinese:'体会', pinyin:'tǐhuì', english:'Experience'},
{no:704, chinese:'体现', pinyin:'tǐxiàn', english:'Reflect'},
{no:705, chinese:'体验', pinyin:'tǐyàn', english:'experience; taste'},
{no:706, chinese:'天空', pinyin:'tiānkōng', english:'sky'},
{no:707, chinese:'甜', pinyin:'tián', english:'sweet'},
{no:708, chinese:'调', pinyin:'tiáo', english:'adjust; suit well'},
{no:709, chinese:'调整', pinyin:'tiáozhěng', english:'adjustment'},
{no:710, chinese:'跳', pinyin:'tiào', english:'jump; leap'},
{no:711, chinese:'跳高', pinyin:'tiàogāo', english:'high jump'},
{no:712, chinese:'跳舞', pinyin:'tiàowǔ', english:'dance'},
{no:713, chinese:'跳远', pinyin:'tiàoyuǎn', english:'long jump'},
{no:714, chinese:'铁', pinyin:'tiě', english:'iron'},
{no:715, chinese:'铁路', pinyin:'tiělù', english:'railway; railroad'},
{no:716, chinese:'听力', pinyin:'tīnglì', english:'hearing; aural comprehension'},
{no:717, chinese:'听众', pinyin:'tīngzhòng', english:'audience; listeners'},
{no:718, chinese:'停止', pinyin:'tíngzhǐ', english:'stop; cease'},
{no:719, chinese:'通常', pinyin:'tōngcháng', english:'usually'},
{no:720, chinese:'通信', pinyin:'tōngxìn', english:'communicate; correspond'},
{no:721, chinese:'同意', pinyin:'tóngyì', english:'Agree'},
{no:722, chinese:'痛', pinyin:'tòng', english:'sore; painful'},
{no:723, chinese:'痛苦', pinyin:'tòngkǔ', english:'Pain'},
{no:724, chinese:'头', pinyin:'tóu', english:'lead; head'},
{no:725, chinese:'头脑', pinyin:'tóunǎo', english:'mind; brain'},
{no:726, chinese:'突出', pinyin:'tūchū', english:'prominent'},
{no:727, chinese:'突然', pinyin:'tūrán', english:'suddenly'},
{no:728, chinese:'图', pinyin:'tú', english:'picture; chart; drawing'},
{no:729, chinese:'图画', pinyin:'túhuà', english:'drawing; picture'},
{no:730, chinese:'土', pinyin:'tǔ', english:'soil; earth; ground'},
{no:731, chinese:'团', pinyin:'tuán', english:'group'},
{no:732, chinese:'团结', pinyin:'tuánjié', english:'Unite'},
{no:733, chinese:'团体', pinyin:'tuántǐ', english:'group'},
{no:734, chinese:'推动', pinyin:'tuīdòng', english:'promote; push forward'},
{no:735, chinese:'推广', pinyin:'tuīguǎng', english:'Extension'},
{no:736, chinese:'推进', pinyin:'tuījìn', english:'advance; carry forward'},
{no:737, chinese:'推开', pinyin:'tuīkāi', english:'push away'},
{no:738, chinese:'退', pinyin:'tuì', english:'retreat'},
{no:739, chinese:'退出', pinyin:'tuìchū', english:'drop out; quit'},
{no:740, chinese:'退休', pinyin:'tuìxiū', english:'retire'},
{no:741, chinese:'外交', pinyin:'wàijiāo', english:'diplomacy'},
{no:742, chinese:'外面', pinyin:'wàimiàn', english:'outside; outdoors'},
{no:743, chinese:'外文', pinyin:'wàiwén', english:'foreign language'},
{no:744, chinese:'完美', pinyin:'wánměi', english:'perfect'},
{no:745, chinese:'完善', pinyin:'wánshàn', english:'perfect, consummate'},
{no:746, chinese:'完整', pinyin:'wánzhěng', english:'complete'},
{no:747, chinese:'玩具', pinyin:'wánjù', english:'Toys'},
{no:748, chinese:'往往', pinyin:'wǎngwǎng', english:'Often'},
{no:749, chinese:'危害', pinyin:'wēihài', english:'Harm'},
{no:750, chinese:'危险', pinyin:'wēixiǎn', english:'danger'},
{no:751, chinese:'为', pinyin:'wéi', english:'act as; become; be'},
{no:752, chinese:'为', pinyin:'wèi', english:'(preposition)'},
{no:753, chinese:'围', pinyin:'wéi', english:'enclose; surround'},
{no:754, chinese:'伟大', pinyin:'wěidà', english:'great'},
{no:755, chinese:'卫生', pinyin:'wèishēng', english:'hygiene; health'},
{no:756, chinese:'卫生间', pinyin:'wèishēngjiān', english:'toilet'},
{no:757, chinese:'为了', pinyin:'wèile', english:'in order to'},
{no:758, chinese:'温暖', pinyin:'wēnnuǎn', english:'warm'},
{no:759, chinese:'文化', pinyin:'wénhuà', english:'Culture'},
{no:760, chinese:'文件', pinyin:'wénjiàn', english:'file'},
{no:761, chinese:'文明', pinyin:'wénmíng', english:'civilization'},
{no:762, chinese:'文学', pinyin:'wénxué', english:'literature'},
{no:763, chinese:'文章', pinyin:'wénzhāng', english:'Article'},
{no:764, chinese:'文字', pinyin:'wénzì', english:'writing; character'},
{no:765, chinese:'握手', pinyin:'wòshǒu', english:'Handshake'},
{no:766, chinese:'屋子', pinyin:'wūzi', english:'House'},
{no:767, chinese:'武器', pinyin:'wǔqì', english:'arms'},
{no:768, chinese:'武术', pinyin:'wǔshù', english:'A martial art'},
{no:769, chinese:'舞台', pinyin:'wǔtái', english:'stage; arena'},
{no:770, chinese:'西部', pinyin:'xībù', english:'west'},
{no:771, chinese:'希望', pinyin:'xīwàng', english:'hope'},
{no:772, chinese:'系', pinyin:'xì', english:'department'},
{no:773, chinese:'下来', pinyin:'xiàlái', english:'come down; get down'},
{no:774, chinese:'下面', pinyin:'xiàmiàn', english:'below; under'},
{no:775, chinese:'下去', pinyin:'xiàqù', english:'go down; descend'},
{no:776, chinese:'先进', pinyin:'xiānjìn', english:'advanced'},
{no:777, chinese:'显得', pinyin:'xiǎnde', english:'Appear'},
{no:778, chinese:'显然', pinyin:'xiǎnrán', english:'Obviously'},
{no:779, chinese:'显示', pinyin:'xiǎnshì', english:'display'},
{no:780, chinese:'现场', pinyin:'xiànchǎng', english:'scene'},
{no:781, chinese:'现代', pinyin:'xiàndài', english:'modern'},
{no:782, chinese:'现金', pinyin:'xiànjīn', english:'cash'},
{no:783, chinese:'现实', pinyin:'xiànshí', english:'reality'},
{no:784, chinese:'现象', pinyin:'xiànxiàng', english:'phenomenon'},
{no:785, chinese:'线', pinyin:'xiàn', english:'thread; string; wire; line'},
{no:786, chinese:'相比', pinyin:'xiāngbǐ', english:'compare; compare to'},
{no:787, chinese:'相当', pinyin:'xiāngdāng', english:'Quite'},
{no:788, chinese:'相关', pinyin:'xiāngguān', english:'correlate'},
{no:789, chinese:'相互', pinyin:'xiānghù', english:'mutual; each other'},
{no:790, chinese:'相似', pinyin:'xiāngsì', english:'Be similar'},
{no:791, chinese:'香', pinyin:'xiāng', english:'fragrant'},
{no:792, chinese:'香蕉', pinyin:'xiāngjiāo', english:'Banana'},
{no:793, chinese:'消费', pinyin:'xiāofèi', english:'consumption'},
{no:794, chinese:'消失', pinyin:'xiāoshī', english:'disappear'},
{no:795, chinese:'消息', pinyin:'xiāoxi', english:'message'},
{no:796, chinese:'效果', pinyin:'xiàoguǒ', english:'Effect'},
{no:797, chinese:'写作', pinyin:'xiězuò', english:'writing'},
{no:798, chinese:'血', pinyin:'xuè', english:'blood'},
{no:799, chinese:'心', pinyin:'xīn', english:'heart; feeling; centre'},
{no:800, chinese:'信', pinyin:'xìn', english:'believe; trust'},
{no:801, chinese:'信封', pinyin:'xìnfēng', english:'envelope'},
{no:802, chinese:'信任', pinyin:'xìnrèn', english:'trust'},
{no:803, chinese:'行李', pinyin:'xíngli', english:'luggage; baggage'},
{no:804, chinese:'形成', pinyin:'xíngchéng', english:'formation'},
{no:805, chinese:'形式', pinyin:'xíngshì', english:'form'},
{no:806, chinese:'形象', pinyin:'xíngxiàng', english:'image'},
{no:807, chinese:'形状', pinyin:'xíngzhuàng', english:'shape'},
{no:808, chinese:'幸福', pinyin:'xìngfú', english:'happiness'},
{no:809, chinese:'幸运', pinyin:'xìngyùn', english:'Lucky'},
{no:810, chinese:'性', pinyin:'xìng', english:'-ness / -ity (suffix)'},
{no:811, chinese:'性别', pinyin:'xìngbié', english:'Gender'},
{no:812, chinese:'性格', pinyin:'xìnggé', english:'character'},
{no:813, chinese:'修', pinyin:'xiū', english:'repair; build; study'},
{no:814, chinese:'修改', pinyin:'xiūgǎi', english:'modify'},
{no:815, chinese:'需求', pinyin:'xūqiú', english:'demand'},
{no:816, chinese:'需要', pinyin:'xūyào', english:'Need'},
{no:817, chinese:'宣布', pinyin:'xuānbù', english:'Announce'},
{no:818, chinese:'宣传', pinyin:'xuānchuán', english:'Propaganda'},
{no:819, chinese:'选手', pinyin:'xuǎnshǒu', english:'Player'},
{no:820, chinese:'学费', pinyin:'xuéfèi', english:'tuition fee'},
{no:821, chinese:'训练', pinyin:'xùnliàn', english:'train'},
{no:822, chinese:'压', pinyin:'yā', english:'press; push; control'},
{no:823, chinese:'压力', pinyin:'yālì', english:'pressure'},
{no:824, chinese:'烟', pinyin:'yān', english:'smoke; tobacco'},
{no:825, chinese:'眼前', pinyin:'yǎnqián', english:'now; at the moment'},
{no:826, chinese:'演', pinyin:'yǎn', english:'play; act; perform'},
{no:827, chinese:'演唱', pinyin:'yǎnchàng', english:'sing'},
{no:828, chinese:'演唱会', pinyin:'yǎnchànghuì', english:'concert'},
{no:829, chinese:'演出', pinyin:'yǎnchū', english:'show'},
{no:830, chinese:'演员', pinyin:'yǎnyuán', english:'performer, actor'},
{no:831, chinese:'羊', pinyin:'yáng', english:'sheep'},
{no:832, chinese:'阳光', pinyin:'yángguāng', english:'Sunshine'},
{no:833, chinese:'要是', pinyin:'yàoshi', english:'If'},
{no:834, chinese:'衣架', pinyin:'yījià', english:'hanger; clothes stand'},
{no:835, chinese:'一切', pinyin:'yíqiè', english:'everything'},
{no:836, chinese:'已', pinyin:'yǐ', english:'already; afterwards'},
{no:837, chinese:'以来', pinyin:'yǐlái', english:'Since'},
{no:838, chinese:'一方面', pinyin:'yìfāngmiàn', english:'on the one hand'},
{no:839, chinese:'艺术', pinyin:'yìshù', english:'Art'},
{no:840, chinese:'意外', pinyin:'yìwài', english:'Accident'},
{no:841, chinese:'意义', pinyin:'yìyì', english:'Significance'},
{no:842, chinese:'因此', pinyin:'yīncǐ', english:'therefore'},
{no:843, chinese:'银', pinyin:'yín', english:'silver'},
{no:844, chinese:'银牌', pinyin:'yínpái', english:'silver medal'},
{no:845, chinese:'印象', pinyin:'yìnxiàng', english:'impression'},
{no:846, chinese:'应当', pinyin:'yīngdāng', english:'should; ought to'},
{no:847, chinese:'迎接', pinyin:'yíngjiē', english:'meet, welcome'},
{no:848, chinese:'营养', pinyin:'yíngyǎng', english:'Nutrition'},
{no:849, chinese:'赢', pinyin:'yíng', english:'win'},
{no:850, chinese:'影视', pinyin:'yǐngshì', english:'film and television'},
{no:851, chinese:'应用', pinyin:'yìngyòng', english:'application'},
{no:852, chinese:'优点', pinyin:'yōudiǎn', english:'Advantage'},
{no:853, chinese:'优势', pinyin:'yōushì', english:'advantage'},
{no:854, chinese:'由', pinyin:'yóu', english:'from'},
{no:855, chinese:'由于', pinyin:'yóuyú', english:'Because'},
{no:856, chinese:'邮件', pinyin:'yóujiàn', english:'mail; post'},
{no:857, chinese:'邮票', pinyin:'yóupiào', english:'postage stamp'},
{no:858, chinese:'邮箱', pinyin:'yóuxiāng', english:'mailbox'},
{no:859, chinese:'游', pinyin:'yóu', english:'swim; travel; tour'},
{no:860, chinese:'游戏', pinyin:'yóuxì', english:'Game'},
{no:861, chinese:'游泳', pinyin:'yóuyǒng', english:'Swimming'},
{no:862, chinese:'有的是', pinyin:'yǒudeshì', english:'have plenty of'},
{no:863, chinese:'有利', pinyin:'yǒulì', english:'favourable; beneficial'},
{no:864, chinese:'有效', pinyin:'yǒuxiào', english:'effective; valid'},
{no:865, chinese:'预报', pinyin:'yùbào', english:'prediction'},
{no:866, chinese:'预防', pinyin:'yùfáng', english:'Prevention'},
{no:867, chinese:'预计', pinyin:'yùjì', english:'expected; estimate'},
{no:868, chinese:'预习', pinyin:'yùxí', english:'Preview'},
{no:869, chinese:'员', pinyin:'yuán', english:'person engaged in an activity'},
{no:870, chinese:'员工', pinyin:'yuángōng', english:'employee'},
{no:871, chinese:'愿望', pinyin:'yuànwàng', english:'desire'},
{no:872, chinese:'约', pinyin:'yuē', english:'appointment; arrange'},
{no:873, chinese:'乐队', pinyin:'yuèduì', english:'orchestra; band'},
{no:874, chinese:'运输', pinyin:'yùnshū', english:'transport'},
{no:875, chinese:'杂志', pinyin:'zázhì', english:'Magazine'},
{no:876, chinese:'早已', pinyin:'zǎoyǐ', english:'long ago'},
{no:877, chinese:'造', pinyin:'zào', english:'make; build; create'},
{no:878, chinese:'造成', pinyin:'zàochéng', english:'cause'},
{no:879, chinese:'责任', pinyin:'zérèn', english:'responsibility'},
{no:880, chinese:'增加', pinyin:'zēngjiā', english:'increase'},
{no:881, chinese:'增长', pinyin:'zēngzhǎng', english:'increase; grow'},
{no:882, chinese:'展开', pinyin:'zhǎnkāi', english:'Open'},
{no:883, chinese:'张', pinyin:'zhāng', english:'Zhang; paper'},
{no:884, chinese:'照', pinyin:'zhào', english:'reflect'},
{no:885, chinese:'者', pinyin:'zhě', english:'suffix (volunteer)'},
{no:886, chinese:'真实', pinyin:'zhēnshí', english:'real'},
{no:887, chinese:'争', pinyin:'zhēng', english:'contend; fight; strive'},
{no:888, chinese:'争取', pinyin:'zhēngqǔ', english:'strive for'},
{no:889, chinese:'整', pinyin:'zhěng', english:'whole; all; complete'},
{no:890, chinese:'整个', pinyin:'zhěnggè', english:'Whole'},
{no:891, chinese:'整理', pinyin:'zhěnglǐ', english:'Arrangement'},
{no:892, chinese:'整齐', pinyin:'zhěngqí', english:'neat'},
{no:893, chinese:'整体', pinyin:'zhěngtǐ', english:'Whole'},
{no:894, chinese:'整天', pinyin:'zhěngtiān', english:'all day long'},
{no:895, chinese:'整整', pinyin:'zhěngzhěng', english:'whole; full'},
{no:896, chinese:'正', pinyin:'zhèng', english:'straight; upright; correct'},
{no:897, chinese:'正式', pinyin:'zhèngshì', english:'formal'},
{no:898, chinese:'证', pinyin:'zhèng', english:'certificate; proof'},
{no:899, chinese:'证件', pinyin:'zhèngjiàn', english:'Certificates'},
{no:900, chinese:'证据', pinyin:'zhèngjù', english:'evidence'},
{no:901, chinese:'证明', pinyin:'zhèngmíng', english:'Prove'},
{no:902, chinese:'支', pinyin:'zhī', english:'(measure word)'},
{no:903, chinese:'支持', pinyin:'zhīchí', english:'Support'},
{no:904, chinese:'支付', pinyin:'zhīfù', english:'pay; defray'},
{no:905, chinese:'只', pinyin:'zhī', english:'single; lonely'},
{no:906, chinese:'直', pinyin:'zhí', english:'straight'},
{no:907, chinese:'直播', pinyin:'zhíbō', english:'on live'},
{no:908, chinese:'直到', pinyin:'zhídào', english:'until'},
{no:909, chinese:'值', pinyin:'zhí', english:'value; be worth'},
{no:910, chinese:'值得', pinyin:'zhíde', english:'Worth'},
{no:911, chinese:'职工', pinyin:'zhígōng', english:'staff; worker'},
{no:912, chinese:'职业', pinyin:'zhíyè', english:'Occupation'},
{no:913, chinese:'只好', pinyin:'zhǐhǎo', english:'have to'},
{no:914, chinese:'只是', pinyin:'zhǐshì', english:'merely; only; just'},
{no:915, chinese:'只有', pinyin:'zhǐyǒu', english:'only'},
{no:916, chinese:'指', pinyin:'zhǐ', english:'finger'},
{no:917, chinese:'指出', pinyin:'zhǐchū', english:'point out; indicate'},
{no:918, chinese:'指导', pinyin:'zhǐdǎo', english:'guidance'},
{no:919, chinese:'至今', pinyin:'zhìjīn', english:'so far'},
{no:920, chinese:'至少', pinyin:'zhìshǎo', english:'at least'},
{no:921, chinese:'志愿', pinyin:'zhìyuàn', english:'volunteer; wish'},
{no:922, chinese:'志愿者', pinyin:'zhìyuànzhě', english:'Volunteer'},
{no:923, chinese:'制定', pinyin:'zhìdìng', english:'Formulate'},
{no:924, chinese:'制度', pinyin:'zhìdù', english:'system'},
{no:925, chinese:'制造', pinyin:'zhìzào', english:'Manufacture'},
{no:926, chinese:'制作', pinyin:'zhìzuò', english:'Make'},
{no:927, chinese:'中部', pinyin:'zhōngbù', english:'central section'},
{no:928, chinese:'中华民族', pinyin:'zhōnghuámínzú', english:'Chinese nation'},
{no:929, chinese:'终于', pinyin:'zhōngyú', english:'finally'},
{no:930, chinese:'钟', pinyin:'zhōng', english:'bell; clock; time'},
{no:931, chinese:'种', pinyin:'zhǒng', english:'species'},
{no:932, chinese:'种子', pinyin:'zhǒngzi', english:'seed'},
{no:933, chinese:'重大', pinyin:'zhòngdà', english:'significant'},
{no:934, chinese:'周围', pinyin:'zhōuwéi', english:'around'},
{no:935, chinese:'猪', pinyin:'zhū', english:'pig'},
{no:936, chinese:'主持', pinyin:'zhǔchí', english:'Host'},
{no:937, chinese:'主动', pinyin:'zhǔdòng', english:'active'},
{no:938, chinese:'主任', pinyin:'zhǔrèn', english:'Headmaster'},
{no:939, chinese:'主意', pinyin:'zhǔyi', english:'idea'},
{no:940, chinese:'主张', pinyin:'zhǔzhāng', english:'opinion'},
{no:941, chinese:'注意', pinyin:'zhùyì', english:'Be careful'},
{no:942, chinese:'祝', pinyin:'zhù', english:'express good wishes; wish'},
{no:943, chinese:'抓', pinyin:'zhuā', english:'grab'},
{no:944, chinese:'抓住', pinyin:'zhuāzhù', english:'catch; grip'},
{no:945, chinese:'专家', pinyin:'zhuānjiā', english:'expert'},
{no:946, chinese:'专门', pinyin:'zhuānmén', english:'specialized'},
{no:947, chinese:'专题', pinyin:'zhuāntí', english:'special collection'},
{no:948, chinese:'专业', pinyin:'zhuānyè', english:'major'},
{no:949, chinese:'转', pinyin:'zhuǎn', english:'turn'},
{no:950, chinese:'转变', pinyin:'zhuǎnbiàn', english:'change'},
{no:951, chinese:'状况', pinyin:'zhuàngkuàng', english:'status'},
{no:952, chinese:'状态', pinyin:'zhuàngtài', english:'state'},
{no:953, chinese:'追', pinyin:'zhuī', english:'run after'},
{no:954, chinese:'准', pinyin:'zhǔn', english:'permit; standard'},
{no:955, chinese:'资格', pinyin:'zīgé', english:'Qualifications'},
{no:956, chinese:'资金', pinyin:'zījīn', english:'capital'},
{no:957, chinese:'子女', pinyin:'zǐnǚ', english:'child; sons and daughters'},
{no:958, chinese:'自从', pinyin:'zìcóng', english:'Since'},
{no:959, chinese:'自动', pinyin:'zìdòng', english:'automatic'},
{no:960, chinese:'自觉', pinyin:'zìjué', english:'Conscious'},
{no:961, chinese:'自然', pinyin:'zìrán', english:'natural'},
{no:962, chinese:'自身', pinyin:'zìshēn', english:'oneself; self'},
{no:963, chinese:'自主', pinyin:'zìzhǔ', english:'Autonomy'},
{no:964, chinese:'总', pinyin:'zǒng', english:'always; consistently'},
{no:965, chinese:'总结', pinyin:'zǒngjié', english:'summary'},
{no:966, chinese:'总是', pinyin:'zǒngshì', english:'always'},
{no:967, chinese:'足够', pinyin:'zúgòu', english:'enough; sufficient'},
{no:968, chinese:'足球', pinyin:'zúqiú', english:'soccer; football'},
{no:969, chinese:'组合', pinyin:'zǔhé', english:'combination'},
{no:970, chinese:'左右', pinyin:'zuǒyòu', english:'About'},
{no:971, chinese:'作品', pinyin:'zuòpǐn', english:'works'},
{no:972, chinese:'作者', pinyin:'zuòzhě', english:'author'},
{no:973, chinese:'做客', pinyin:'zuòkè', english:'be a guest'}
];

/* ---------- tabulator ---------- */
new Tabulator('#hsk3-table', {
  data: vocab,
  layout: 'fitColumns',
  resizableColumns: false,
  columns: [
    {title:'#', field:'no', width:60},
    {title:'Chinese', field:'chinese'},
    {title:'Pinyin', field:'pinyin'},
    {title:'English', field:'english'},
  ]
});