/* ---------- 500 entries ---------- */
const data = [
{No:1,Chinese:"爱",Pinyin:"ài",English:"love"},
{No:2,Chinese:"爱好",Pinyin:"ài hào",English:"hobby"},
{No:3,Chinese:"八",Pinyin:"bā",English:"eight"},
{No:4,Chinese:"爸爸｜爸",Pinyin:"bàba ｜ bà",English:"dad"},
{No:5,Chinese:"吧",Pinyin:"ba",English:"(interjection particle)"},
{No:6,Chinese:"白（形）",Pinyin:"bái",English:"white"},
{No:7,Chinese:"白天",Pinyin:"bái tiān",English:"day"},
{No:8,Chinese:"百",Pinyin:"bǎi",English:"hundred"},
{No:9,Chinese:"班",Pinyin:"bān",English:"class"},
{No:10,Chinese:"半",Pinyin:"bàn",English:"half"},
{No:11,Chinese:"半年",Pinyin:"bàn nián",English:"half a year"},
{No:12,Chinese:"半天",Pinyin:"bàn tiān",English:"half day"},
{No:13,Chinese:"帮",Pinyin:"bāng",English:"help"},
{No:14,Chinese:"帮忙",Pinyin:"bāng máng",English:"help"},
{No:15,Chinese:"包",Pinyin:"bāo",English:"package"},
{No:16,Chinese:"包子",Pinyin:"bāo zi",English:"bun"},
{No:17,Chinese:"杯",Pinyin:"bēi",English:"cup"},
{No:18,Chinese:"杯子",Pinyin:"bēi zi",English:"cup"},
{No:19,Chinese:"北",Pinyin:"běi",English:"north"},
{No:20,Chinese:"北边",Pinyin:"běi biān",English:"North side"},
{No:21,Chinese:"北京",Pinyin:"běi jīng",English:"Beijing"},
{No:22,Chinese:"本（量）",Pinyin:"běn",English:"(measure word for books or volumes)"},
{No:23,Chinese:"本子",Pinyin:"běn zi",English:"book"},
{No:24,Chinese:"比",Pinyin:"bǐ",English:"particle used for comparison"},
{No:25,Chinese:"别（副）",Pinyin:"bié",English:"Don’t"},
{No:26,Chinese:"别的",Pinyin:"bié de",English:"other"},
{No:27,Chinese:"别人",Pinyin:"bié·rén",English:"other people"},
{No:28,Chinese:"病",Pinyin:"bìng",English:"disease"},
{No:29,Chinese:"病人",Pinyin:"bìng rén",English:"patient"},
{No:30,Chinese:"不大",Pinyin:"bú dà",English:"not big"},
{No:31,Chinese:"不对",Pinyin:"bú duì",English:"wrong"},
{No:32,Chinese:"不客气",Pinyin:"bú kè qì",English:"You’re welcome"},
{No:33,Chinese:"不用",Pinyin:"bú yòng",English:"No need to"},
{No:34,Chinese:"不",Pinyin:"bù",English:"No"},
{No:35,Chinese:"菜",Pinyin:"cài",English:"dish"},
{No:36,Chinese:"茶",Pinyin:"chá",English:"tea"},
{No:37,Chinese:"差",Pinyin:"chà",English:"differ from; bad; short of"},
{No:38,Chinese:"常",Pinyin:"cháng",English:"often"},
{No:39,Chinese:"常常",Pinyin:"cháng cháng",English:"often"},
{No:40,Chinese:"唱",Pinyin:"chàng",English:"sing"},
{No:41,Chinese:"唱歌",Pinyin:"chàng gē",English:"sing"},
{No:42,Chinese:"车",Pinyin:"chē",English:"car"},
{No:43,Chinese:"车票",Pinyin:"chē piào",English:"ticket"},
{No:44,Chinese:"车上",Pinyin:"chē shàng",English:"in the car"},
{No:45,Chinese:"车站",Pinyin:"chē zhàn",English:"station"},
{No:46,Chinese:"吃",Pinyin:"chī",English:"eat"},
{No:47,Chinese:"吃饭",Pinyin:"chī fàn",English:"have meal"},
{No:48,Chinese:"出",Pinyin:"chū",English:"out"},
{No:49,Chinese:"出来",Pinyin:"chū lái",English:"come"},
{No:50,Chinese:"出去",Pinyin:"chū qù",English:"go out"},
{No:51,Chinese:"穿",Pinyin:"chuān",English:"wear"},
{No:52,Chinese:"床",Pinyin:"chuáng",English:"bed"},
{No:53,Chinese:"次（量）",Pinyin:"cì",English:"(measure word for times, frequency)"},
{No:54,Chinese:"从",Pinyin:"cóng",English:"from"},
{No:55,Chinese:"错",Pinyin:"cuò",English:"wrong"},
{No:56,Chinese:"打（动）",Pinyin:"dǎ",English:"hit, take"},
{No:57,Chinese:"打车",Pinyin:"dǎ chē",English:"take a taxi"},
{No:58,Chinese:"打电话",Pinyin:"dǎ diàn huà",English:"make a phonecall"},
{No:59,Chinese:"打开",Pinyin:"dǎ kāi",English:"turn on"},
{No:60,Chinese:"打球",Pinyin:"dǎ qiú",English:"play ball"},
{No:61,Chinese:"大",Pinyin:"dà",English:"large, big"},
{No:62,Chinese:"大学",Pinyin:"dà xué",English:"university"},
{No:63,Chinese:"大学生",Pinyin:"dà xué shēng",English:"university student"},
{No:64,Chinese:"到",Pinyin:"dào",English:"reach"},
{No:65,Chinese:"得到",Pinyin:"dé dào",English:"get"},
{No:66,Chinese:"地",Pinyin:"de",English:"auxiliary word"},
{No:67,Chinese:"的",Pinyin:"de",English:"(aux.)"},
{No:68,Chinese:"等（动）",Pinyin:"děng",English:"wait"},
{No:69,Chinese:"地",Pinyin:"dì",English:"ground"},
{No:70,Chinese:"地点",Pinyin:"dìdiǎn",English:"location"},
{No:71,Chinese:"地方",Pinyin:"dìfang",English:"local"},
{No:72,Chinese:"地上",Pinyin:"dì shàng",English:"on the ground"},
{No:73,Chinese:"地图",Pinyin:"dìtú",English:"Map"},
{No:74,Chinese:"弟弟｜弟",Pinyin:"dì di ｜ dì",English:"younger brother"},
{No:75,Chinese:"第（第二）",Pinyin:"dì （ dì èr ）",English:"auxiliary word for ordinal numbers (second )"},
{No:76,Chinese:"点",Pinyin:"diǎn",English:"spot"},
{No:77,Chinese:"电",Pinyin:"diàn",English:"electricity"},
{No:78,Chinese:"电话",Pinyin:"diàn huà",English:"phone"},
{No:79,Chinese:"电脑",Pinyin:"diànnǎo",English:"Computer"},
{No:80,Chinese:"电视",Pinyin:"diànshì",English:"television"},
{No:81,Chinese:"电视机",Pinyin:"diàn shì jī",English:"television"},
{No:82,Chinese:"电影",Pinyin:"diànyǐng",English:"Film"},
{No:83,Chinese:"电影院",Pinyin:"diàn yǐng yuàn",English:"cinema; movie theater"},
{No:84,Chinese:"东",Pinyin:"dōng",English:"east"},
{No:85,Chinese:"东边",Pinyin:"dōng biān",English:"east side"},
{No:86,Chinese:"东西",Pinyin:"dōngxi",English:"thing"},
{No:87,Chinese:"动",Pinyin:"dòng",English:"move"},
{No:88,Chinese:"动作",Pinyin:"dòngzuò",English:"action"},
{No:89,Chinese:"都",Pinyin:"dōu",English:"all"},
{No:90,Chinese:"读",Pinyin:"dú",English:"read"},
{No:91,Chinese:"读书",Pinyin:"dú shū",English:"reading; study"},
{No:92,Chinese:"对（形）",Pinyin:"duì",English:"right"},
{No:93,Chinese:"对不起",Pinyin:"duìbuqǐ",English:"I’m sorry."},
{No:94,Chinese:"多（形、代）",Pinyin:"duō",English:"many; much; more"},
{No:95,Chinese:"多少",Pinyin:"duōshao",English:"how much"},
{No:96,Chinese:"饿",Pinyin:"è",English:"hungry"},
{No:97,Chinese:"儿子",Pinyin:"érzi",English:"Son"},
{No:98,Chinese:"二",Pinyin:"èr",English:"Two"},
{No:99,Chinese:"饭",Pinyin:"fàn",English:"rice; meal"},
{No:100,Chinese:"饭店",Pinyin:"fàndiàn",English:"restaurant"},
{No:101,Chinese:"房间",Pinyin:"fángjiān",English:"Room"},
{No:102,Chinese:"房子",Pinyin:"fáng zi",English:"house; building"},
{No:103,Chinese:"放",Pinyin:"fàng",English:"discharge"},
{No:104,Chinese:"放假",Pinyin:"fàng jià",English:"holiday; have a holiday"},
{No:105,Chinese:"放学",Pinyin:"fàng xué",English:"off school"},
{No:106,Chinese:"飞",Pinyin:"fēi",English:"fly"},
{No:107,Chinese:"飞机",Pinyin:"fēijī",English:"aircraft"},
{No:108,Chinese:"非常",Pinyin:"fēicháng",English:"very"},
{No:109,Chinese:"分（名、量）",Pinyin:"fēn",English:"minute; point; part; (measure word)"},
{No:110,Chinese:"风",Pinyin:"fēng",English:"wind"},
{No:111,Chinese:"干",Pinyin:"gān",English:"dry"},
{No:112,Chinese:"干净",Pinyin:"gānjìng",English:"clean"},
{No:113,Chinese:"干",Pinyin:"gàn",English:"do"},
{No:114,Chinese:"干什么",Pinyin:"gàn shén me",English:"What to do"},
{No:115,Chinese:"高",Pinyin:"gāo",English:"high"},
{No:116,Chinese:"高兴",Pinyin:"gāoxìng",English:"happy"},
{No:117,Chinese:"告诉",Pinyin:"gàosu",English:"tell"},
{No:118,Chinese:"哥哥｜哥",Pinyin:"gē ge ｜ gē",English:"elder brother"},
{No:119,Chinese:"歌",Pinyin:"gē",English:"song"},
{No:120,Chinese:"个",Pinyin:"gè",English:"individual"},
{No:121,Chinese:"给",Pinyin:"gěi",English:"give"},
{No:122,Chinese:"跟",Pinyin:"gēn",English:"with"},
{No:123,Chinese:"工人",Pinyin:"gōngrén",English:"Worker"},
{No:124,Chinese:"工作",Pinyin:"gōngzuò",English:"work"},
{No:125,Chinese:"关（动）",Pinyin:"guān",English:"shut; close; turn off"},
{No:126,Chinese:"关上",Pinyin:"guān shàng",English:"close;shut to; turn off"},
{No:127,Chinese:"贵",Pinyin:"guì",English:"noble"},
{No:128,Chinese:"国",Pinyin:"guó",English:"country; state; nation"},
{No:129,Chinese:"国家",Pinyin:"guójiā",English:"Country"},
{No:130,Chinese:"国外",Pinyin:"guó wài",English:"foreign; oversea; abroad"},
{No:131,Chinese:"过",Pinyin:"guò",English:"pass"},
{No:132,Chinese:"还",Pinyin:"hái",English:"also; still; yet"},
{No:133,Chinese:"还是",Pinyin:"háishi",English:"still"},
{No:134,Chinese:"还有",Pinyin:"hái yǒu",English:"also; in addition; besides"},
{No:135,Chinese:"孩子",Pinyin:"háizi",English:"Children"},
{No:136,Chinese:"汉语",Pinyin:"hànyǔ",English:"Chinese"},
{No:137,Chinese:"汉字",Pinyin:"hàn zì",English:"Chinese character"},
{No:138,Chinese:"好（形）",Pinyin:"hǎo",English:"good"},
{No:139,Chinese:"好吃",Pinyin:"hǎochī",English:"Yummy"},
{No:140,Chinese:"好看",Pinyin:"hǎo kàn",English:"good looking"},
{No:141,Chinese:"好听",Pinyin:"hǎo tīng",English:"pleasant to hear"},
{No:142,Chinese:"好玩儿",Pinyin:"hǎo wánr",English:"fun; interesting"},
{No:143,Chinese:"号",Pinyin:"hào",English:"Number/date"},
{No:144,Chinese:"喝",Pinyin:"hē",English:"drink"},
{No:145,Chinese:"和",Pinyin:"hé",English:"and"},
{No:146,Chinese:"很",Pinyin:"hěn",English:"very"},
{No:147,Chinese:"后",Pinyin:"hòu",English:"back; behind; after; later"},
{No:148,Chinese:"后边",Pinyin:"hòu biān",English:"behind; back"},
{No:149,Chinese:"后天",Pinyin:"hòu tiān",English:"day after tomorrow"},
{No:150,Chinese:"花（名）",Pinyin:"huā",English:"flower"},
{No:151,Chinese:"话",Pinyin:"huà",English:"word; words"},
{No:152,Chinese:"坏",Pinyin:"huài",English:"bad"},
{No:153,Chinese:"还",Pinyin:"huán",English:"return; pay back"},
{No:154,Chinese:"回（动）",Pinyin:"huí",English:"go back; return"},
{No:155,Chinese:"回答",Pinyin:"huídá",English:"Answer"},
{No:156,Chinese:"回到",Pinyin:"huí dào",English:"back to"},
{No:157,Chinese:"回家",Pinyin:"huí jiā",English:"go home; return home"},
{No:158,Chinese:"回来",Pinyin:"huí lái",English:"come back; return"},
{No:159,Chinese:"回去",Pinyin:"huí qù",English:"go back"},
{No:160,Chinese:"会（动）",Pinyin:"huì",English:"can; be able to"},
{No:161,Chinese:"火车",Pinyin:"huǒ chē",English:"train"},
{No:162,Chinese:"机场",Pinyin:"jīchǎng",English:"Airport"},
{No:163,Chinese:"机票",Pinyin:"jī piào",English:"air ticket"},
{No:164,Chinese:"鸡蛋",Pinyin:"jīdàn",English:"Egg"},
{No:165,Chinese:"几",Pinyin:"jǐ",English:"several"},
{No:166,Chinese:"记",Pinyin:"jì",English:"remember"},
{No:167,Chinese:"记得",Pinyin:"jìdé",English:"remember"},
{No:168,Chinese:"记住",Pinyin:"jì zhù",English:"remember; keep in mind"},
{No:169,Chinese:"家",Pinyin:"jiā",English:"home"},
{No:170,Chinese:"家里",Pinyin:"jiā lǐ",English:"In the home"},
{No:171,Chinese:"家人",Pinyin:"jiā rén",English:"family"},
{No:172,Chinese:"间",Pinyin:"jiān",English:"between; measure word for rooms"},
{No:173,Chinese:"见",Pinyin:"jiàn",English:"see; meet"},
{No:174,Chinese:"见面",Pinyin:"jiànmiàn",English:"meet"},
{No:175,Chinese:"教",Pinyin:"jiāo",English:"teach"},
{No:176,Chinese:"叫（动）",Pinyin:"jiào",English:"call; be called"},
{No:177,Chinese:"教学楼",Pinyin:"jiào xué lóu",English:"teaching building"},
{No:178,Chinese:"姐姐｜姐",Pinyin:"jiě jie ｜ jiě",English:"elder sister"},
{No:179,Chinese:"介绍",Pinyin:"jièshào",English:"introduce"},
{No:180,Chinese:"今年",Pinyin:"jīn nián",English:"this year"},
{No:181,Chinese:"今天",Pinyin:"jīntiān",English:"Today"},
{No:182,Chinese:"进",Pinyin:"jìn",English:"enter"},
{No:183,Chinese:"进来",Pinyin:"jìn lái",English:"come in"},
{No:184,Chinese:"进去",Pinyin:"jìn qù",English:"go in"},
{No:185,Chinese:"九",Pinyin:"jiǔ",English:"Nine"},
{No:186,Chinese:"就",Pinyin:"jiù",English:"as soon as; right away; then"},
{No:187,Chinese:"觉得",Pinyin:"juéde",English:"Think"},
{No:188,Chinese:"开",Pinyin:"kāi",English:"open"},
{No:189,Chinese:"开车",Pinyin:"kāi chē",English:"drive; drive a car"},
{No:190,Chinese:"开会",Pinyin:"kāi huì",English:"have a meeting"},
{No:191,Chinese:"开玩笑",Pinyin:"kāiwánxiào",English:"Make fun of"},
{No:192,Chinese:"看",Pinyin:"kàn",English:"see"},
{No:193,Chinese:"看病",Pinyin:"kàn bìng",English:"see a doctor"},
{No:194,Chinese:"看到",Pinyin:"kàn dào",English:"see"},
{No:195,Chinese:"看见",Pinyin:"kànjiàn",English:"seeing"},
{No:196,Chinese:"考",Pinyin:"kǎo",English:"test; examine"},
{No:197,Chinese:"考试",Pinyin:"kǎoshì",English:"Examination"},
{No:198,Chinese:"渴",Pinyin:"kě",English:"thirsty"},
{No:199,Chinese:"课",Pinyin:"kè",English:"course"},
{No:200,Chinese:"课本",Pinyin:"kè běn",English:"textbook"},
{No:201,Chinese:"课文",Pinyin:"kè wén",English:"text"},
{No:202,Chinese:"口",Pinyin:"kǒu",English:"mouth"},
{No:203,Chinese:"块",Pinyin:"kuài",English:"block"},
{No:204,Chinese:"快",Pinyin:"kuài",English:"fast"},
{No:205,Chinese:"来",Pinyin:"lái",English:"come"},
{No:206,Chinese:"来到",Pinyin:"lái dào",English:"come; arrive"},
{No:207,Chinese:"老（形）",Pinyin:"lǎo",English:"old; aged"},
{No:208,Chinese:"老人",Pinyin:"lǎo rén",English:"old people; the aged"},
{No:209,Chinese:"老师",Pinyin:"lǎoshī",English:"Teacher"},
{No:210,Chinese:"了",Pinyin:"le",English:"past tense marker"},
{No:211,Chinese:"累",Pinyin:"lèi",English:"tired"},
{No:212,Chinese:"冷",Pinyin:"lěng",English:"cold"},
{No:213,Chinese:"里",Pinyin:"lǐ",English:"in"},
{No:214,Chinese:"里边",Pinyin:"lǐ biān",English:"inside"},
{No:215,Chinese:"两（数）",Pinyin:"liǎng",English:"two"},
{No:216,Chinese:"零｜〇",Pinyin:"líng ｜ líng",English:"zero"},
{No:217,Chinese:"六",Pinyin:"liù",English:"Six"},
{No:218,Chinese:"楼",Pinyin:"lóu",English:"floor"},
{No:219,Chinese:"楼上",Pinyin:"lóu shàng",English:"upstairs"},
{No:220,Chinese:"楼下",Pinyin:"lóu xià",English:"downstairs"},
{No:221,Chinese:"路",Pinyin:"lù",English:"road"},
{No:222,Chinese:"路口",Pinyin:"lù kǒu",English:"intersection; crossing"},
{No:223,Chinese:"路上",Pinyin:"lù shàng",English:"on the road"},
{No:224,Chinese:"妈妈｜妈",Pinyin:"mā ma ｜ mā",English:"mom; mother"},
{No:225,Chinese:"马路",Pinyin:"mǎ lù",English:"road; street"},
{No:226,Chinese:"马上",Pinyin:"mǎshàng",English:"Right off"},
{No:227,Chinese:"吗",Pinyin:"ma",English:"auxiliary word"},
{No:228,Chinese:"买",Pinyin:"mǎi",English:"buy"},
{No:229,Chinese:"慢",Pinyin:"màn",English:"slow"},
{No:230,Chinese:"忙",Pinyin:"máng",English:"busy"},
{No:231,Chinese:"毛（量）",Pinyin:"máo",English:"a fractional unit of money in China (measure word)"},
{No:232,Chinese:"没",Pinyin:"méi",English:"no"},
{No:233,Chinese:"没关系",Pinyin:"méiguānxi",English:"No problem"},
{No:234,Chinese:"没什么",Pinyin:"méi shén me",English:"It’s nothing"},
{No:235,Chinese:"没事儿",Pinyin:"méi shìr",English:"It’s okay"},
{No:236,Chinese:"没有",Pinyin:"méi yǒu",English:"have not; no"},
{No:237,Chinese:"妹妹｜妹",Pinyin:"mèi mei ｜ mèi",English:"younger sister"},
{No:238,Chinese:"门",Pinyin:"mén",English:"door"},
{No:239,Chinese:"门口",Pinyin:"mén kǒu",English:"doorway"},
{No:240,Chinese:"门票",Pinyin:"mén piào",English:"tickets"},
{No:241,Chinese:"们（朋友们）",Pinyin:"men （ péng yǒu men ）",English:"plural marker for pronouns and a few animate nouns (friends)"},
{No:242,Chinese:"米饭",Pinyin:"mǐfàn",English:"Steamed Rice"},
{No:243,Chinese:"面包",Pinyin:"miànbāo",English:"Bread"},
{No:244,Chinese:"面条儿",Pinyin:"miàn tiáor",English:"noodles"},
{No:245,Chinese:"名字",Pinyin:"míngzi",English:"Name"},
{No:246,Chinese:"明白",Pinyin:"míngbai",English:"clear"},
{No:247,Chinese:"明年",Pinyin:"míng nián",English:"next year"},
{No:248,Chinese:"明天",Pinyin:"míngtiān",English:"Tomorrow"},
{No:249,Chinese:"拿",Pinyin:"ná",English:"take"},
{No:250,Chinese:"哪",Pinyin:"nǎ",English:"which"},
{No:251,Chinese:"哪里",Pinyin:"nǎ lǐ",English:"where"},
{No:252,Chinese:"哪儿",Pinyin:"nǎr",English:"where"},
{No:253,Chinese:"哪些",Pinyin:"nǎ xiē",English:"which"},
{No:254,Chinese:"那（代）",Pinyin:"nà",English:"that"},
{No:255,Chinese:"那边",Pinyin:"nà biān",English:"there"},
{No:256,Chinese:"那里",Pinyin:"nà lǐ",English:"there"},
{No:257,Chinese:"那儿",Pinyin:"nàr",English:"there"},
{No:258,Chinese:"那些",Pinyin:"nà xiē",English:"those"},
{No:259,Chinese:"奶",Pinyin:"nǎi",English:"milk"},
{No:260,Chinese:"奶奶",Pinyin:"nǎinai",English:"grandma"},
{No:261,Chinese:"男",Pinyin:"nán",English:"Man"},
{No:262,Chinese:"男孩儿",Pinyin:"nán háir",English:"boy"},
{No:263,Chinese:"男朋友",Pinyin:"nán péng yǒu",English:"boyfriend"},
{No:264,Chinese:"男人",Pinyin:"nán ren",English:"man"},
{No:265,Chinese:"男生",Pinyin:"nán shēng",English:"boy"},
{No:266,Chinese:"南",Pinyin:"nán",English:"south"},
{No:267,Chinese:"南边",Pinyin:"nán biān",English:"south; south side"},
{No:268,Chinese:"难",Pinyin:"nán",English:"hard, difficult"},
{No:269,Chinese:"呢",Pinyin:"ne",English:"auxiliary word"},
{No:270,Chinese:"能",Pinyin:"néng",English:"can"},
{No:271,Chinese:"你",Pinyin:"nǐ",English:"you"},
{No:272,Chinese:"你们",Pinyin:"nǐ men",English:"you"},
{No:273,Chinese:"年",Pinyin:"nián",English:"year"},
{No:274,Chinese:"您",Pinyin:"nín",English:"you"},
{No:275,Chinese:"牛奶",Pinyin:"niúnǎi",English:"milk"},
{No:276,Chinese:"女",Pinyin:"nǚ",English:"woman"},
{No:277,Chinese:"女儿",Pinyin:"nǚ’ér",English:"daughter"},
{No:278,Chinese:"女孩儿",Pinyin:"nǚ háir",English:"girl"},
{No:279,Chinese:"女朋友",Pinyin:"nǚ péng yǒu",English:"girlfriend"},
{No:280,Chinese:"女人",Pinyin:"nǚ ren",English:"woman"},
{No:281,Chinese:"女生",Pinyin:"nǚ shēng",English:"girl"},
{No:282,Chinese:"旁边",Pinyin:"pángbiān",English:"Side"},
{No:283,Chinese:"跑",Pinyin:"pǎo",English:"run"},
{No:284,Chinese:"朋友",Pinyin:"péngyou",English:"Friend"},
{No:285,Chinese:"票",Pinyin:"piào",English:"ticket"},
{No:286,Chinese:"七",Pinyin:"qī",English:"Seven"},
{No:287,Chinese:"起",Pinyin:"qǐ",English:"get up; start; rise"},
{No:288,Chinese:"起床",Pinyin:"qǐchuáng",English:"Get up"},
{No:289,Chinese:"起来",Pinyin:"qǐlái",English:"get up"},
{No:290,Chinese:"汽车",Pinyin:"qì chē",English:"car"},
{No:291,Chinese:"前",Pinyin:"qián",English:"front"},
{No:292,Chinese:"前边",Pinyin:"qián biān",English:"in front"},
{No:293,Chinese:"前天",Pinyin:"qián tiān",English:"the day before yesterday"},
{No:294,Chinese:"钱",Pinyin:"qián",English:"money"},
{No:295,Chinese:"钱包",Pinyin:"qián bāo",English:"wallet"},
{No:296,Chinese:"请",Pinyin:"qǐng",English:"please"},
{No:297,Chinese:"请假",Pinyin:"qǐngjià",English:"ask for leave"},
{No:298,Chinese:"请进",Pinyin:"qǐng jìn",English:"please come in"},
{No:299,Chinese:"请问",Pinyin:"qǐng wèn",English:"excuse me"},
{No:300,Chinese:"请坐",Pinyin:"qǐng zuò",English:"please have a seat"},
{No:301,Chinese:"球",Pinyin:"qiú",English:"ball"},
{No:302,Chinese:"去",Pinyin:"qù",English:"go"},
{No:303,Chinese:"去年",Pinyin:"qùnián",English:"Last year"},
{No:304,Chinese:"热",Pinyin:"rè",English:"heat"},
{No:305,Chinese:"人",Pinyin:"rén",English:"people"},
{No:306,Chinese:"认识",Pinyin:"rènshi",English:"know"},
{No:307,Chinese:"认真",Pinyin:"rènzhēn",English:"earnest"},
{No:308,Chinese:"日",Pinyin:"rì",English:"date"},
{No:309,Chinese:"日期",Pinyin:"rìqī",English:"Date"},
{No:310,Chinese:"肉",Pinyin:"ròu",English:"meat"},
{No:311,Chinese:"三",Pinyin:"sān",English:"Three"},
{No:312,Chinese:"山",Pinyin:"shān",English:"mountain"},
{No:313,Chinese:"商场",Pinyin:"shāng chǎng",English:"mall; shopping mall"},
{No:314,Chinese:"商店",Pinyin:"shāngdiàn",English:"Shop"},
{No:315,Chinese:"上",Pinyin:"shàng",English:"upper"},
{No:316,Chinese:"上班",Pinyin:"shàngbān",English:"go to work"},
{No:317,Chinese:"上边",Pinyin:"shàng biān",English:"above; on"},
{No:318,Chinese:"上车",Pinyin:"shàng chē",English:"get on"},
{No:319,Chinese:"上次",Pinyin:"shàng cì",English:"last time"},
{No:320,Chinese:"上课",Pinyin:"shàng kè",English:"attend class; have a class"},
{No:321,Chinese:"上网",Pinyin:"shàngwǎng",English:"Surf the Internet"},
{No:322,Chinese:"上午",Pinyin:"shàngwǔ",English:"morning"},
{No:323,Chinese:"上学",Pinyin:"shàng xué",English:"go to school"},
{No:324,Chinese:"少",Pinyin:"shǎo",English:"less"},
{No:325,Chinese:"谁",Pinyin:"shéi",English:"who"},
{No:326,Chinese:"身上",Pinyin:"shēn shàng",English:"body; on one’s body"},
{No:327,Chinese:"身体",Pinyin:"shēntǐ",English:"body"},
{No:328,Chinese:"什么",Pinyin:"shénme",English:"What"},
{No:329,Chinese:"生病",Pinyin:"shēngbìng",English:"Fall ill"},
{No:330,Chinese:"生气",Pinyin:"shēngqì",English:"get angry"},
{No:331,Chinese:"生日",Pinyin:"shēngrì",English:"Birthday"},
{No:332,Chinese:"十",Pinyin:"shí",English:"Ten"},
{No:333,Chinese:"时候",Pinyin:"shíhou",English:"time"},
{No:334,Chinese:"时间",Pinyin:"shíjiān",English:"time"},
{No:335,Chinese:"事",Pinyin:"shì",English:"thing"},
{No:336,Chinese:"试",Pinyin:"shì",English:"try"},
{No:337,Chinese:"是",Pinyin:"shì",English:"yes"},
{No:338,Chinese:"是不是",Pinyin:"shì bú shì",English:"isn’t it?"},
{No:339,Chinese:"手",Pinyin:"shǒu",English:"hand"},
{No:340,Chinese:"手机",Pinyin:"shǒujī",English:"Mobile phone"},
{No:341,Chinese:"书",Pinyin:"shū",English:"book"},
{No:342,Chinese:"书包",Pinyin:"shū bāo",English:"school bag"},
{No:343,Chinese:"书店",Pinyin:"shū diàn",English:"bookstore"},
{No:344,Chinese:"树",Pinyin:"shù",English:"tree"},
{No:345,Chinese:"水",Pinyin:"shuǐ",English:"water"},
{No:346,Chinese:"水果",Pinyin:"shuǐguǒ",English:"Fruits"},
{No:347,Chinese:"睡",Pinyin:"shuì",English:"sleep"},
{No:348,Chinese:"睡觉",Pinyin:"shuìjiào",English:"sleep"},
{No:349,Chinese:"说",Pinyin:"shuō",English:"speak"},
{No:350,Chinese:"说话",Pinyin:"shuōhuà",English:"talk"},
{No:351,Chinese:"四",Pinyin:"sì",English:"Four"},
{No:352,Chinese:"送",Pinyin:"sòng",English:"give"},
{No:353,Chinese:"岁",Pinyin:"suì",English:"year, age"},
{No:354,Chinese:"他",Pinyin:"tā",English:"he"},
{No:355,Chinese:"他们",Pinyin:"tā men",English:"they"},
{No:356,Chinese:"她",Pinyin:"tā",English:"she"},
{No:357,Chinese:"她们",Pinyin:"tā men",English:"they"},
{No:358,Chinese:"太",Pinyin:"tài",English:"too"},
{No:359,Chinese:"天",Pinyin:"tiān",English:"day"},
{No:360,Chinese:"天气",Pinyin:"tiānqì",English:"weather"},
{No:361,Chinese:"听",Pinyin:"tīng",English:"hear"},
{No:362,Chinese:"听到",Pinyin:"tīng dào",English:"hear"},
{No:363,Chinese:"听见",Pinyin:"tīng jiàn",English:"hear"},
{No:364,Chinese:"听写",Pinyin:"tīng xiě",English:"dictation; dictate"},
{No:365,Chinese:"同学",Pinyin:"tóngxué",English:"Classmate"},
{No:366,Chinese:"图书馆",Pinyin:"túshūguǎn",English:"Library"},
{No:367,Chinese:"外",Pinyin:"wài",English:"abroad, outside"},
{No:368,Chinese:"外边",Pinyin:"wài biān",English:"outside"},
{No:369,Chinese:"外国",Pinyin:"wài guó",English:"foreign country"},
{No:370,Chinese:"外语",Pinyin:"wài yǔ",English:"foreign language"},
{No:371,Chinese:"玩儿",Pinyin:"wánr",English:"play"},
{No:372,Chinese:"晚",Pinyin:"wǎn",English:"late"},
{No:373,Chinese:"晚饭",Pinyin:"wǎn fàn",English:"dinner"},
{No:374,Chinese:"晚上",Pinyin:"wǎnshang",English:"Night"},
{No:375,Chinese:"网上",Pinyin:"wǎng shàng",English:"online"},
{No:376,Chinese:"网友",Pinyin:"wǎng yǒu",English:"net friend"},
{No:377,Chinese:"忘",Pinyin:"wàng",English:"forget"},
{No:378,Chinese:"忘记",Pinyin:"wàngjì",English:"forget"},
{No:379,Chinese:"问",Pinyin:"wèn",English:"ask"},
{No:380,Chinese:"我",Pinyin:"wǒ",English:"I"},
{No:381,Chinese:"我们",Pinyin:"wǒmen",English:"We"},
{No:382,Chinese:"五",Pinyin:"wǔ",English:"Five"},
{No:383,Chinese:"午饭",Pinyin:"wǔ fàn",English:"lunch"},
{No:384,Chinese:"西",Pinyin:"xī",English:"west"},
{No:385,Chinese:"西边",Pinyin:"xī biān",English:"west; west side"},
{No:386,Chinese:"洗",Pinyin:"xǐ",English:"wash"},
{No:387,Chinese:"洗手间",Pinyin:"xǐshǒujiān",English:"Restroom"},
{No:388,Chinese:"喜欢",Pinyin:"xǐhuan",English:"like"},
{No:389,Chinese:"下（名、动）",Pinyin:"xià",English:"below; under; next; go down; get off"},
{No:390,Chinese:"下班",Pinyin:"xià bān",English:"get off work"},
{No:391,Chinese:"下边",Pinyin:"xià biān",English:"below; under"},
{No:392,Chinese:"下车",Pinyin:"xià chē",English:"get off"},
{No:393,Chinese:"下次",Pinyin:"xià cì",English:"next time"},
{No:394,Chinese:"下课",Pinyin:"xià kè",English:"finish class"},
{No:395,Chinese:"下午",Pinyin:"xiàwǔ",English:"Afternoon"},
{No:396,Chinese:"下雨",Pinyin:"xiàyǔ",English:"rain"},
{No:397,Chinese:"先",Pinyin:"xiān",English:"before"},
{No:398,Chinese:"先生",Pinyin:"xiānsheng",English:"Sir"},
{No:399,Chinese:"现在",Pinyin:"xiànzài",English:"Now"},
{No:400,Chinese:"想",Pinyin:"xiǎng",English:"think"},
{No:401,Chinese:"小",Pinyin:"xiǎo",English:"Small"},
{No:402,Chinese:"小孩儿",Pinyin:"xiǎo háir",English:"child; kid"},
{No:403,Chinese:"小姐",Pinyin:"xiǎojiě",English:"Miss"},
{No:404,Chinese:"小朋友",Pinyin:"xiǎo péng yǒu",English:"child; kid"},
{No:405,Chinese:"小时",Pinyin:"xiǎoshí",English:"hour"},
{No:406,Chinese:"小学",Pinyin:"xiǎo xué",English:"primary school; elementary school"},
{No:407,Chinese:"小学生",Pinyin:"xiǎo xué shēng",English:"elementary school student"},
{No:408,Chinese:"笑",Pinyin:"xiào",English:"laugh"},
{No:409,Chinese:"写",Pinyin:"xiě",English:"write"},
{No:410,Chinese:"谢谢",Pinyin:"xièxie",English:"Thank you"},
{No:411,Chinese:"新",Pinyin:"xīn",English:"new"},
{No:412,Chinese:"新年",Pinyin:"xīn nián",English:"New Year"},
{No:413,Chinese:"星期",Pinyin:"xīngqī",English:"week"},
{No:414,Chinese:"星期日",Pinyin:"xīng qī rì",English:"Sunday"},
{No:415,Chinese:"星期天",Pinyin:"xīng qī tiān",English:"Sunday"},
{No:416,Chinese:"行",Pinyin:"xíng",English:"That’s ok"},
{No:417,Chinese:"休息",Pinyin:"xiūxi",English:"Rest"},
{No:418,Chinese:"学",Pinyin:"xué",English:"learn; study"},
{No:419,Chinese:"学生",Pinyin:"xuésheng",English:"Student"},
{No:420,Chinese:"学习",Pinyin:"xuéxí",English:"Study"},
{No:421,Chinese:"学校",Pinyin:"xuéxiào",English:"School"},
{No:422,Chinese:"学院",Pinyin:"xué yuàn",English:"college; academy"},
{No:423,Chinese:"要（动）",Pinyin:"yào",English:"want"},
{No:424,Chinese:"爷爷",Pinyin:"yéye",English:"grandpa"},
{No:425,Chinese:"也",Pinyin:"yě",English:"also"},
{No:426,Chinese:"页",Pinyin:"yè",English:"page"},
{No:427,Chinese:"一",Pinyin:"yī",English:"One"},
{No:428,Chinese:"衣服",Pinyin:"yīfu",English:"clothes"},
{No:429,Chinese:"医生",Pinyin:"yīshēng",English:"Doctor"},
{No:430,Chinese:"医院",Pinyin:"yīyuàn",English:"Hospital"},
{No:431,Chinese:"一半",Pinyin:"yí bàn",English:"half"},
{No:432,Chinese:"一会儿",Pinyin:"yíhuìr",English:"A little while"},
{No:433,Chinese:"一块儿",Pinyin:"yí kuàir",English:"together"},
{No:434,Chinese:"一下儿",Pinyin:"yí xiàr",English:"a little bit"},
{No:435,Chinese:"一样",Pinyin:"yíyàng",English:"equally"},
{No:436,Chinese:"一边",Pinyin:"yìbiān",English:"One side"},
{No:437,Chinese:"一点儿",Pinyin:"yīdiǎnr",English:"a little bit"},
{No:438,Chinese:"一起",Pinyin:"yìqǐ",English:"together"},
{No:439,Chinese:"一些",Pinyin:"yì xiē",English:"some"},
{No:440,Chinese:"用",Pinyin:"yòng",English:"use"},
{No:441,Chinese:"有",Pinyin:"yǒu",English:"have"},
{No:442,Chinese:"有的",Pinyin:"yǒu de",English:"some"},
{No:443,Chinese:"有名",Pinyin:"yǒumíng",English:"Famous"},
{No:444,Chinese:"有时候｜有时",Pinyin:"yǒu shí hòu ｜ yǒu shí",English:"sometimes"},
{No:445,Chinese:"有（一）些",Pinyin:"yǒu （ yì ） xiē",English:"some"},
{No:446,Chinese:"有用",Pinyin:"yǒu yòng",English:"useful"},
{No:447,Chinese:"右",Pinyin:"yòu",English:"right"},
{No:448,Chinese:"右边",Pinyin:"yòubian",English:"Right"},
{No:449,Chinese:"雨",Pinyin:"yǔ",English:"rain"},
{No:450,Chinese:"元",Pinyin:"yuán",English:"element; Yuan"},
{No:451,Chinese:"远",Pinyin:"yuǎn",English:"far"},
{No:452,Chinese:"月",Pinyin:"yuè",English:"month"},
{No:453,Chinese:"再",Pinyin:"zài",English:"again"},
{No:454,Chinese:"再见",Pinyin:"zàijiàn",English:"Bye"},
{No:455,Chinese:"在",Pinyin:"zài",English:"stay; in process of"},
{No:456,Chinese:"在家",Pinyin:"zài jiā",English:"at home"},
{No:457,Chinese:"早",Pinyin:"zǎo",English:"early"},
{No:458,Chinese:"早饭",Pinyin:"zǎo fàn",English:"breakfast"},
{No:459,Chinese:"早上",Pinyin:"zǎoshang",English:"Morning"},
{No:460,Chinese:"怎么",Pinyin:"zěnme",English:"How"},
{No:461,Chinese:"站（名）",Pinyin:"zhàn",English:"station"},
{No:462,Chinese:"找",Pinyin:"zhǎo",English:"look for"},
{No:463,Chinese:"找到",Pinyin:"zhǎo dào",English:"find"},
{No:464,Chinese:"这",Pinyin:"zhè",English:"Here (here)"},
{No:465,Chinese:"这边",Pinyin:"zhè biān",English:"here"},
{No:466,Chinese:"这里",Pinyin:"zhè lǐ",English:"here"},
{No:467,Chinese:"这儿",Pinyin:"zhèr",English:"here"},
{No:468,Chinese:"这些",Pinyin:"zhè xiē",English:"these"},
{No:469,Chinese:"着",Pinyin:"zhe",English:"in process of"},
{No:470,Chinese:"真",Pinyin:"zhēn",English:"really"},
{No:471,Chinese:"真的",Pinyin:"zhēn de",English:"really"},
{No:472,Chinese:"正（副）",Pinyin:"zhèng",English:"just; exactly"},
{No:473,Chinese:"正在",Pinyin:"zhèngzài",English:"in process of"},
{No:474,Chinese:"知道",Pinyin:"zhīdào",English:"know"},
{No:475,Chinese:"知识",Pinyin:"zhīshi",English:"knowledge"},
{No:476,Chinese:"中",Pinyin:"zhōng",English:"middle; in"},
{No:477,Chinese:"中国",Pinyin:"zhōngguó",English:"China"},
{No:478,Chinese:"中间",Pinyin:"zhōngjiān",English:"Middle"},
{No:479,Chinese:"中文",Pinyin:"zhōngwén",English:"Chinese"},
{No:480,Chinese:"中午",Pinyin:"zhōngwǔ",English:"Noon"},
{No:481,Chinese:"中学",Pinyin:"zhōng xué",English:"middle school"},
{No:482,Chinese:"中学生",Pinyin:"zhōng xué shēng",English:"middle School student"},
{No:483,Chinese:"重",Pinyin:"zhòng",English:"heavy"},
{No:484,Chinese:"重要",Pinyin:"zhòngyào",English:"important"},
{No:485,Chinese:"住",Pinyin:"zhù",English:"live"},
{No:486,Chinese:"准备",Pinyin:"zhǔnbèi",English:"Get ready"},
{No:487,Chinese:"桌子",Pinyin:"zhuōzi",English:"Table"},
{No:488,Chinese:"字",Pinyin:"zì",English:"word, character"},
{No:489,Chinese:"子（桌子）",Pinyin:"zi （ zhuō zi ）",English:"noun suffix (table)"},
{No:490,Chinese:"走",Pinyin:"zǒu",English:"go, walk"},
{No:491,Chinese:"走路",Pinyin:"zǒu lù",English:"walk"},
{No:492,Chinese:"最",Pinyin:"zuì",English:"most"},
{No:493,Chinese:"最好",Pinyin:"zuìhǎo",English:"Best"},
{No:494,Chinese:"最后",Pinyin:"zuìhòu",English:"Last"},
{No:495,Chinese:"昨天",Pinyin:"zuótiān",English:"Yesterday"},
{No:496,Chinese:"左",Pinyin:"zuǒ",English:"left"},
{No:497,Chinese:"左边",Pinyin:"zuǒbian",English:"left"},
{No:498,Chinese:"坐",Pinyin:"zuò",English:"sit"},
{No:499,Chinese:"坐下",Pinyin:"zuò xià",English:"sit down"},
{No:500,Chinese:"做",Pinyin:"zuò",English:"do"}
];
/* ---------- Tabulator ---------- */
new Tabulator('#hsk1-table', {
  data: data,
  layout: 'fitColumns',
  resizableColumns: false,
  columns: [
    {title: 'No', field: 'No', width: 50},
    {title: 'Chinese', field: 'Chinese', widthGrow: 1},
    {title: 'Pinyin', field: 'Pinyin', widthGrow: 1},
    {title: 'English', field: 'English', widthGrow: 2}
  ]
});