/* ---------- 1000 entires ---------- */
const vocab = [
{no:1,  chinese:'阿姨', pinyin:'āyí', english:'aunt'},
{no:2,  chinese:'啊', pinyin:'a', english:'ah'},
{no:3,  chinese:'矮', pinyin:'ǎi', english:'short'},
{no:4,  chinese:'矮小', pinyin:'ǎi xiǎo', english:'short and small'},
{no:5,  chinese:'爱国', pinyin:'ài guó', english:'love one’s country'},
{no:6,  chinese:'爱护', pinyin:'àihù', english:'Care'},
{no:7,  chinese:'安', pinyin:'ān', english:'quiet; safe; secure'},
{no:8,  chinese:'安置', pinyin:'ānzhì', english:'put; arrange for'},
{no:9,  chinese:'按时', pinyin:'ànshí', english:'on time'},
{no:10, chinese:'暗', pinyin:'àn', english:'dark'},
{no:11, chinese:'暗示', pinyin:'ànshì', english:'suggest secretly'},
{no:12, chinese:'巴士', pinyin:'bā shì', english:'bus'},
{no:13, chinese:'百货', pinyin:'bǎi huò', english:'department store'},
{no:14, chinese:'摆', pinyin:'bǎi', english:'pendulum'},
{no:15, chinese:'摆动', pinyin:'bǎi dòng', english:'swing; sway'},
{no:16, chinese:'摆脱', pinyin:'bǎituō', english:'cast off'},
{no:17, chinese:'败', pinyin:'bài', english:'defeat; fail'},
{no:18, chinese:'办事', pinyin:'bàn shì', english:'handle affairs'},
{no:19, chinese:'包裹', pinyin:'bāoguǒ', english:'package'},
{no:20, chinese:'包含', pinyin:'bāohán', english:'Contain'},
{no:21, chinese:'包括', pinyin:'bāokuò', english:'Include'},
{no:22, chinese:'薄', pinyin:'báo', english:'thin'},
{no:23, chinese:'宝', pinyin:'bǎo', english:'treasure'},
{no:24, chinese:'宝宝', pinyin:'bǎo bao', english:'baby'},
{no:25, chinese:'宝贝', pinyin:'bǎobèi', english:'baby'},
{no:26, chinese:'宝贵', pinyin:'bǎoguì', english:'valuable'},
{no:27, chinese:'宝石', pinyin:'bǎo shí', english:'gemstone'},
{no:28, chinese:'保密', pinyin:'bǎomì', english:'secrecy'},
{no:29, chinese:'保守', pinyin:'bǎoshǒu', english:'Conservative'},
{no:30, chinese:'抱', pinyin:'bào', english:'Hold, hug'},
{no:31, chinese:'背景', pinyin:'bèijǐng', english:'background'},
{no:32, chinese:'倍', pinyin:'bèi', english:'times'},
{no:33, chinese:'被迫', pinyin:'bèi pò', english:'be compelled'},
{no:34, chinese:'本科', pinyin:'běnkē', english:'Undergraduate'},
{no:35, chinese:'笨', pinyin:'bèn', english:'stupid'},
{no:36, chinese:'比分', pinyin:'bǐ fēn', english:'score'},
{no:37, chinese:'毕业', pinyin:'bìyè', english:'graduation'},
{no:38, chinese:'毕业生', pinyin:'bì yè shēng', english:'graduate'},
{no:39, chinese:'避', pinyin:'bì', english:'avoid'},
{no:40, chinese:'避免', pinyin:'bìmiǎn', english:'avoid'},
{no:41, chinese:'编', pinyin:'biān', english:'invent; edit'},
{no:42, chinese:'辩论', pinyin:'biànlùn', english:'Debate'},
{no:43, chinese:'标志', pinyin:'biāozhì', english:'sign'},
{no:44, chinese:'表情', pinyin:'biǎoqíng', english:'Expression'},
{no:45, chinese:'表扬', pinyin:'biǎoyáng', english:'Praise'},
{no:46, chinese:'别（动）', pinyin:'bié', english:'do not; leave'},
{no:47, chinese:'冰', pinyin:'bīng', english:'ice'},
{no:48, chinese:'冰箱', pinyin:'bīngxiāng', english:'Refrigerator'},
{no:49, chinese:'冰雪', pinyin:'bīng xuě', english:'ice and snow'},
{no:50, chinese:'兵', pinyin:'bīng', english:'soldier'},
{no:51, chinese:'并（动）', pinyin:'bìng', english:'combine'},
{no:52, chinese:'不要紧', pinyin:'búyàojǐn', english:'Never mind'},
{no:53, chinese:'不在乎', pinyin:'bú zài hū', english:'not care'},
{no:54, chinese:'不管', pinyin:'bùguǎn', english:'no matter'},
{no:55, chinese:'不然', pinyin:'bùrán', english:'otherwise'},
{no:56, chinese:'布置', pinyin:'bùzhì', english:'Arrangement'},
{no:57, chinese:'步行', pinyin:'bù xíng', english:'walk'},
{no:58, chinese:'擦', pinyin:'cā', english:'wipe'},
{no:59, chinese:'才（名）', pinyin:'cái', english:'talent'},
{no:60, chinese:'材料', pinyin:'cáiliào', english:'Materials'},
{no:61, chinese:'财产', pinyin:'cáichǎn', english:'property'},
{no:62, chinese:'财富', pinyin:'cáifù', english:'wealth'},
{no:63, chinese:'采访', pinyin:'cǎifǎng', english:'interview'},
{no:64, chinese:'参考', pinyin:'cānkǎo', english:'Reference'},
{no:65, chinese:'参与', pinyin:'cānyù', english:'participate'},
{no:66, chinese:'操场', pinyin:'cāochǎng', english:'Playground'},
{no:67, chinese:'操作', pinyin:'cāozuò', english:'operation'},
{no:68, chinese:'测', pinyin:'cè', english:'measure'},
{no:69, chinese:'测量', pinyin:'cèliáng', english:'measure'},
{no:70, chinese:'测试', pinyin:'cè shì', english:'test'},
{no:71, chinese:'曾', pinyin:'céng', english:'once'},
{no:72, chinese:'茶叶', pinyin:'chá yè', english:'tea-leaves'},
{no:73, chinese:'产品', pinyin:'chǎnpǐn', english:'product'},
{no:74, chinese:'长途', pinyin:'chángtú', english:'Long-distance'},
{no:75, chinese:'常识', pinyin:'chángshí', english:'common sense'},
{no:76, chinese:'唱片', pinyin:'chàng piàn', english:'record'},
{no:77, chinese:'抄', pinyin:'chāo', english:'copy'},
{no:78, chinese:'抄写', pinyin:'chāo xiě', english:'transcribe'},
{no:79, chinese:'潮', pinyin:'cháo', english:'tide'},
{no:80, chinese:'潮流', pinyin:'cháoliú', english:'Trend'},
{no:81, chinese:'潮湿', pinyin:'cháoshī', english:'damp'},
{no:82, chinese:'彻底', pinyin:'chèdǐ', english:'thorough'},
{no:83, chinese:'沉', pinyin:'chén', english:'sink'},
{no:84, chinese:'沉默', pinyin:'chénmò', english:'silent'},
{no:85, chinese:'沉重', pinyin:'chénzhòng', english:'heavy'},
{no:86, chinese:'称赞', pinyin:'chēngzàn', english:'Praise'},
{no:87, chinese:'成人', pinyin:'chéngrén', english:'adult'},
{no:88, chinese:'诚实', pinyin:'chéngshí', english:'honest'},
{no:89, chinese:'诚信', pinyin:'chéng xìn', english:'integrity'},
{no:90, chinese:'承担', pinyin:'chéngdān', english:'bear'},
{no:91, chinese:'承认', pinyin:'chéngrèn', english:'Admit'},
{no:92, chinese:'承受', pinyin:'chéngshòu', english:'bear'},
{no:93, chinese:'程序', pinyin:'chéngxù', english:'program'},
{no:94, chinese:'吃惊', pinyin:'chījīng', english:'Be amazed'},
{no:95, chinese:'迟到', pinyin:'chídào', english:'Late'},
{no:96, chinese:'尺', pinyin:'chǐ', english:'ruler'},
{no:97, chinese:'尺寸', pinyin:'chǐ cùn', english:'size'},
{no:98, chinese:'尺子', pinyin:'chǐzi', english:'Ruler'},
{no:99, chinese:'冲', pinyin:'chōng', english:'punching'},
{no:100, chinese:'充电', pinyin:'chōng diàn', english:'recharge'},
{no:101, chinese:'充电器', pinyin:'chōngdiànqì', english:'Charger'},
{no:102, chinese:'充分', pinyin:'chōngfèn', english:'To the full'},
{no:103, chinese:'虫子', pinyin:'chóng zi', english:'insect; worm; bug'},
{no:104, chinese:'抽', pinyin:'chōu', english:'pump; take out; pick out'},
{no:105, chinese:'抽奖', pinyin:'chōu jiǎng', english:'lottery; lottery draw'},
{no:106, chinese:'抽烟', pinyin:'chōuyān', english:'smoking'},
{no:107, chinese:'出口', pinyin:'chūkǒu', english:'Exit'},
{no:108, chinese:'出色', pinyin:'chūsè', english:'excellent; outstanding'},
{no:109, chinese:'出售', pinyin:'chū shòu', english:'offer for sale; sell'},
{no:110, chinese:'出席', pinyin:'chūxí', english:'Attend'},
{no:111, chinese:'处于', pinyin:'chǔ yú', english:'be in; be (in a certain condition)'},
{no:112, chinese:'处', pinyin:'chǔ', english:'dwell; live; be in a position of'},
{no:113, chinese:'穿上', pinyin:'chuān shàng', english:'put on'},
{no:114, chinese:'传统', pinyin:'chuántǒng', english:'tradition'},
{no:115, chinese:'窗户', pinyin:'chuānghu', english:'Window'},
{no:116, chinese:'窗台', pinyin:'chuāng tái', english:'windowsill; sill'},
{no:117, chinese:'窗子', pinyin:'chuāng zi', english:'window'},
{no:118, chinese:'春季', pinyin:'chūn jì', english:'spring; springtime'},
{no:119, chinese:'纯', pinyin:'chún', english:'pure; unmixed; simple; skilful'},
{no:120, chinese:'纯净水', pinyin:'chún jìng shuǐ', english:'pure water'},
{no:121, chinese:'词汇', pinyin:'cíhuì', english:'vocabulary'},
{no:122, chinese:'此', pinyin:'cǐ', english:'this; these; now; here'},
{no:123, chinese:'此外', pinyin:'cǐwài', english:'in addition'},
{no:124, chinese:'次（形）', pinyin:'cì', english:'second-rate; secondary'},
{no:125, chinese:'刺', pinyin:'cì', english:'thorn'},
{no:126, chinese:'刺激', pinyin:'cìjī', english:'stimulate'},
{no:127, chinese:'从此', pinyin:'cóngcǐ', english:'from then on'},
{no:128, chinese:'粗', pinyin:'cū', english:'wide; thick; coarse; rough; rude'},
{no:129, chinese:'粗心', pinyin:'cūxīn', english:'careless'},
{no:130, chinese:'促进', pinyin:'cùjìn', english:'Promote'},
{no:131, chinese:'促使', pinyin:'cùshǐ', english:'Urge'},
{no:132, chinese:'促销', pinyin:'cù xiāo', english:'promotion'},
{no:133, chinese:'措施', pinyin:'cuòshī', english:'Measures'},
{no:134, chinese:'打', pinyin:'dǎ', english:'strike; hit; break; fight; build'},
{no:135, chinese:'答案', pinyin:'dá’àn', english:'Answer'},
{no:136, chinese:'打败', pinyin:'dǎ bài', english:'defeat; beat; be defeated'},
{no:137, chinese:'打雷', pinyin:'dǎ léi', english:'thunder'},
{no:138, chinese:'打扫', pinyin:'dǎsǎo', english:'Clean'},
{no:139, chinese:'打折', pinyin:'dǎzhé', english:'Discount'},
{no:140, chinese:'打针', pinyin:'dǎzhēn', english:'To make an injection'},
{no:141, chinese:'大巴', pinyin:'dà bā', english:'bus'},
{no:142, chinese:'大多', pinyin:'dà duō', english:'mostly; for the most part'},
{no:143, chinese:'大方', pinyin:'dàfang', english:'generous'},
{no:144, chinese:'大哥', pinyin:'dà gē', english:'big brother; elder brother'},
{no:145, chinese:'大规模', pinyin:'dà guī mó', english:'large-scale; extensive'},
{no:146, chinese:'大会', pinyin:'dà huì', english:'convention; general meeting'},
{no:147, chinese:'大姐', pinyin:'dà jiě', english:'elder sister'},
{no:148, chinese:'大楼', pinyin:'dà lóu', english:'building; large building'},
{no:149, chinese:'大陆', pinyin:'dà lù', english:'continent; mainland'},
{no:150, chinese:'大妈', pinyin:'dà mā', english:'aunt; father’s elder brother’s wife'},
{no:151, chinese:'大型', pinyin:'dàxíng', english:'large'},
{no:152, chinese:'大爷', pinyin:'dà ye', english:'uncle; father’s elder brother'},
{no:153, chinese:'大众', pinyin:'dà zhòng', english:'public; the masses; people'},
{no:154, chinese:'代替', pinyin:'dàitì', english:'replace'},
{no:155, chinese:'待遇', pinyin:'dàiyù', english:'treatment'},
{no:156, chinese:'袋', pinyin:'dài', english:'bag; sack; pocket'},
{no:157, chinese:'戴', pinyin:'dài', english:'wear'},
{no:158, chinese:'担保', pinyin:'dānbǎo', english:'assure; hypothecate'},
{no:159, chinese:'担任', pinyin:'dānrèn', english:'To serve as'},
{no:160, chinese:'担心', pinyin:'dānxīn', english:'Worry'},
{no:161, chinese:'单', pinyin:'dān', english:'single; odd; unlined; thin; weak; only'},
{no:162, chinese:'单纯', pinyin:'dānchún', english:'Simple'},
{no:163, chinese:'单调', pinyin:'dāndiào', english:'monotonous'},
{no:164, chinese:'单独', pinyin:'dāndú', english:'Alone'},
{no:165, chinese:'淡', pinyin:'dàn', english:'light'},
{no:166, chinese:'导游', pinyin:'dǎoyóu', english:'Guide'},
{no:167, chinese:'导致', pinyin:'dǎozhì', english:'cause'},
{no:168, chinese:'倒闭', pinyin:'dǎobì', english:'Collapse'},
{no:169, chinese:'倒车', pinyin:'dǎo chē', english:'change trains or buses'},
{no:170, chinese:'倒车', pinyin:'dào chē', english:'back a car; reverse'},
{no:171, chinese:'得意', pinyin:'déyì', english:'Proud'},
{no:172, chinese:'得', pinyin:'děi', english:'need; must; have to'},
{no:173, chinese:'灯光', pinyin:'dēng guāng', english:'light; stage lighting'},
{no:174, chinese:'登', pinyin:'dēng', english:'ascend; mount; scale; publish'},
{no:175, chinese:'登记', pinyin:'dēngjì', english:'register'},
{no:176, chinese:'登录', pinyin:'dēnglù', english:'Sign in'},
{no:177, chinese:'登山', pinyin:'dēng shān', english:'mountaineer; mountain-climbing'},
{no:178, chinese:'的确', pinyin:'díquè', english:'indeed; be certain to'},
{no:179, chinese:'敌人', pinyin:'dírén', english:'Enemy'},
{no:180, chinese:'底', pinyin:'dǐ', english:'bottom'},
{no:181, chinese:'地方', pinyin:'dìfang', english:'local'},
{no:182, chinese:'地面', pinyin:'dì miàn', english:'ground; floor; surface'},
{no:183, chinese:'地位', pinyin:'dìwèi', english:'status'},
{no:184, chinese:'地下', pinyin:'dì xià', english:'underground; subterranean; secret'},
{no:185, chinese:'地址', pinyin:'dìzhǐ', english:'address'},
{no:186, chinese:'典型', pinyin:'diǎnxíng', english:'typical'},
{no:187, chinese:'点名', pinyin:'diǎn míng', english:'rollcall; mention sb. by name'},
{no:188, chinese:'电灯', pinyin:'diàn dēng', english:'electric light'},
{no:189, chinese:'电动车', pinyin:'diàn dòng chē', english:'electric car'},
{no:190, chinese:'电梯', pinyin:'diàntī', english:'Elevator'},
{no:191, chinese:'电源', pinyin:'diànyuán', english:'power supply'},
{no:192, chinese:'顶', pinyin:'dǐng', english:'top'},
{no:193, chinese:'定', pinyin:'dìng', english:'decide; fix; book; order; calm'},
{no:194, chinese:'冬季', pinyin:'dōng jì', english:'winter'},
{no:195, chinese:'动画片', pinyin:'dònghuàpiàn', english:'Cartoon'},
{no:196, chinese:'动摇', pinyin:'dòng yáo', english:'shake; vacillate; waver'},
{no:197, chinese:'豆腐', pinyin:'dòufu', english:'tofu'},
{no:198, chinese:'独立', pinyin:'dúlì', english:'Independent'},
{no:199, chinese:'独特', pinyin:'dútè', english:'unique'},
{no:200, chinese:'独自', pinyin:'dú zì', english:'alone; by oneself'},
{no:201, chinese:'堵', pinyin:'dǔ', english:'stop up; block up; stifled'},
{no:202, chinese:'堵车', pinyin:'dǔchē', english:'Traffic jam'},
{no:203, chinese:'肚子', pinyin:'dùzi', english:'belly'},
{no:204, chinese:'度过', pinyin:'dùguò', english:'Spend'},
{no:205, chinese:'锻炼', pinyin:'duànliàn', english:'Physical exercise'},
{no:206, chinese:'对比', pinyin:'duìbǐ', english:'Contrast'},
{no:207, chinese:'对付', pinyin:'duìfu', english:'deal with'},
{no:208, chinese:'对于', pinyin:'duìyú', english:'about'},
{no:209, chinese:'多次', pinyin:'duō cì', english:'repeatedly; many a time'},
{no:210, chinese:'多年', pinyin:'duō nián', english:'many years'},
{no:211, chinese:'多样', pinyin:'duō yàng', english:'diversity'},
{no:212, chinese:'多种', pinyin:'duō zhǒng', english:'multiple; various; diversified'},
{no:213, chinese:'恶心', pinyin:'ěxin', english:'disgusting'},
{no:214, chinese:'儿童', pinyin:'értóng', english:'children'},
{no:215, chinese:'而', pinyin:'ér', english:'and'},
{no:216, chinese:'而是', pinyin:'ér shì', english:'but'},
{no:217, chinese:'耳机', pinyin:'ěr jī', english:'earphone; headphone'},
{no:218, chinese:'二手', pinyin:'èr shǒu', english:'second hand'},
{no:219, chinese:'发挥', pinyin:'fāhuī', english:'Develop'},
{no:220, chinese:'发票', pinyin:'fāpiào', english:'invoice'},
{no:221, chinese:'发烧', pinyin:'fāshāo', english:'Have a fever'},
{no:222, chinese:'法', pinyin:'fǎ', english:'law; way; method'},
{no:223, chinese:'法官', pinyin:'fǎ guān', english:'judge'},
{no:224, chinese:'法律', pinyin:'fǎlǜ', english:'Law'},
{no:225, chinese:'法院', pinyin:'fǎyuàn', english:'Court'},
{no:226, chinese:'翻', pinyin:'fān', english:'Turn'},
{no:227, chinese:'翻译', pinyin:'fānyì', english:'translate'},
{no:228, chinese:'烦', pinyin:'fán', english:'bother'},
{no:229, chinese:'反', pinyin:'fǎn', english:'turn over; rebel; on the contrary'},
{no:230, chinese:'反而', pinyin:'fǎn’ér', english:'Instead'},
{no:231, chinese:'反映', pinyin:'fǎnyìng', english:'reflect'},
{no:232, chinese:'方', pinyin:'fāng', english:'square'},
{no:233, chinese:'方案', pinyin:'fāng’àn', english:'programme'},
{no:234, chinese:'方针', pinyin:'fāngzhēn', english:'policy'},
{no:235, chinese:'放松', pinyin:'fàngsōng', english:'Relax'},
{no:236, chinese:'非', pinyin:'fēi', english:'wrong'},
{no:237, chinese:'肥', pinyin:'féi', english:'fat; fertile'},
{no:238, chinese:'分布', pinyin:'fēnbù', english:'distribution'},
{no:239, chinese:'分散', pinyin:'fēnsàn', english:'Dispersed'},
{no:240, chinese:'分手', pinyin:'fēnshǒu', english:'Break up'},
{no:241, chinese:'分为', pinyin:'fēn wéi', english:'divide into'},
{no:242, chinese:'…分之…', pinyin:'… fēn zhī …', english:'fractional number'},
{no:243, chinese:'纷纷', pinyin:'fēnfēn', english:'one after another'},
{no:244, chinese:'奋斗', pinyin:'fèndòu', english:'Struggle'},
{no:245, chinese:'风格', pinyin:'fēnggé', english:'style'},
{no:246, chinese:'风景', pinyin:'fēngjǐng', english:'Scenery'},
{no:247, chinese:'风俗', pinyin:'fēngsú', english:'Customs'},
{no:248, chinese:'封闭', pinyin:'fēngbì', english:'close'},
{no:249, chinese:'否则', pinyin:'fǒuzé', english:'otherwise'},
{no:250, chinese:'夫妇', pinyin:'fūfù', english:'couple'},
{no:251, chinese:'夫妻', pinyin:'fū qī', english:'man and wife'},
{no:252, chinese:'夫人', pinyin:'fūrén', english:'Madam'},
{no:253, chinese:'符号', pinyin:'fúhào', english:'Symbol'},
{no:254, chinese:'符合', pinyin:'fúhé', english:'accord with'},
{no:255, chinese:'付出', pinyin:'fù chū', english:'pay out'},
{no:256, chinese:'负担', pinyin:'fùdān', english:'burden'},
{no:257, chinese:'附近', pinyin:'fùjìn', english:'nearby'},
{no:258, chinese:'复制', pinyin:'fùzhì', english:'copy'},
{no:259, chinese:'改善', pinyin:'gǎishàn', english:'Improve'},
{no:260, chinese:'改正', pinyin:'gǎizhèng', english:'correction'},
{no:261, chinese:'盖', pinyin:'gài', english:'cover'},
{no:262, chinese:'概括', pinyin:'gàikuò', english:'Generalization'},
{no:263, chinese:'感兴趣', pinyin:'gǎnxìngqù', english:'be interested in'},
{no:264, chinese:'高潮', pinyin:'gāocháo', english:'climax'},
{no:265, chinese:'高价', pinyin:'gāo jià', english:'high price'},
{no:266, chinese:'高尚', pinyin:'gāoshàng', english:'noble'},
{no:267, chinese:'高铁', pinyin:'gāo tiě', english:'high-speed train'},
{no:268, chinese:'格外', pinyin:'géwài', english:'especially'},
{no:269, chinese:'隔', pinyin:'gé', english:'partition; separate; divide'},
{no:270, chinese:'隔开', pinyin:'gé kāi', english:'separate; space out'},
{no:271, chinese:'个别', pinyin:'gèbié', english:'individual'},
{no:272, chinese:'个体', pinyin:'gètǐ', english:'individual'},
{no:273, chinese:'各个', pinyin:'gè gè', english:'each'},
{no:274, chinese:'根', pinyin:'gēn', english:'root'},
{no:275, chinese:'根据', pinyin:'gēnjù', english:'according to'},
{no:276, chinese:'工程', pinyin:'gōng chéng', english:'engineering; project'},
{no:277, chinese:'公元', pinyin:'gōngyuán', english:'A.D.'},
{no:278, chinese:'供应', pinyin:'gōng yìng', english:'supply; provide'},
{no:279, chinese:'共', pinyin:'gòng', english:'common; general; share; together'},
{no:280, chinese:'构成', pinyin:'gòuchéng', english:'constitute'},
{no:281, chinese:'构造', pinyin:'gòu zào', english:'structure; construction'},
{no:282, chinese:'购买', pinyin:'gòu mǎi', english:'buy; purchase'},
{no:283, chinese:'购物', pinyin:'gòuwù', english:'Shopping'},
{no:284, chinese:'骨头', pinyin:'gǔtou', english:'Bone'},
{no:285, chinese:'固定', pinyin:'gùdìng', english:'fixed'},
{no:286, chinese:'瓜', pinyin:'guā', english:'melon'},
{no:287, chinese:'怪', pinyin:'guài', english:'strange; odd; very; quite'},
{no:288, chinese:'关（名）', pinyin:'guān', english:'pass; checkpoint; barrier'},
{no:289, chinese:'关闭', pinyin:'guānbì', english:'close; shut'},
{no:290, chinese:'关于', pinyin:'guānyú', english:'about'},
{no:291, chinese:'官', pinyin:'guān', english:'officer'},
{no:292, chinese:'官方', pinyin:'guānfāng', english:'by the government official'},
{no:293, chinese:'光临', pinyin:'guānglín', english:'presence'},
{no:294, chinese:'光盘', pinyin:'guāngpán', english:'CD'},
{no:295, chinese:'逛', pinyin:'guàng', english:'Stroll'},
{no:296, chinese:'归', pinyin:'guī', english:'return; go back'},
{no:297, chinese:'规律', pinyin:'guīlǜ', english:'Law'},
{no:298, chinese:'规模', pinyin:'guīmó', english:'scale'},
{no:299, chinese:'规则', pinyin:'guīzé', english:'rule'},
{no:300, chinese:'果实', pinyin:'guǒshí', english:'fruit'},
{no:301, chinese:'过分', pinyin:'guòfèn', english:'excessive'},
{no:302, chinese:'海水', pinyin:'hǎi shuǐ', english:'seawater; brine'},
{no:303, chinese:'海鲜', pinyin:'hǎixiān', english:'seafood'},
{no:304, chinese:'含', pinyin:'hán', english:'contain; cherish; keep'},
{no:305, chinese:'含量', pinyin:'hán liàng', english:'content'},
{no:306, chinese:'含义', pinyin:'hányì', english:'signification; meanings'},
{no:307, chinese:'含有', pinyin:'hán yǒu', english:'contain; have'},
{no:308, chinese:'寒假', pinyin:'hánjià', english:'The winter vacation'},
{no:309, chinese:'寒冷', pinyin:'hán lěng', english:'cold; frigid; chill'},
{no:310, chinese:'行业', pinyin:'hángyè', english:'industry'},
{no:311, chinese:'航班', pinyin:'hángbān', english:'flight'},
{no:312, chinese:'航空', pinyin:'hángkōng', english:'aviation'},
{no:313, chinese:'毫米', pinyin:'háomǐ', english:'millimeter'},
{no:314, chinese:'毫升', pinyin:'háo shēng', english:'milliliter'},
{no:315, chinese:'好友', pinyin:'hǎo yǒu', english:'friend'},
{no:316, chinese:'号码', pinyin:'hàomǎ', english:'number'},
{no:317, chinese:'好', pinyin:'hǎo', english:'good'},
{no:318, chinese:'合同', pinyin:'hétong', english:'contract'},
{no:319, chinese:'黑暗', pinyin:'hēi àn', english:'dark; darkness; murk'},
{no:320, chinese:'红包', pinyin:'hóng bāo', english:'red envelope; red packet'},
{no:321, chinese:'后头', pinyin:'hòu tou', english:'back'},
{no:322, chinese:'厚', pinyin:'hòu', english:'thick'},
{no:323, chinese:'呼吸', pinyin:'hūxī', english:'breathing'},
{no:324, chinese:'忽视', pinyin:'hūshì', english:'Ignore'},
{no:325, chinese:'户', pinyin:'hù', english:'household; family; door'},
{no:326, chinese:'护士', pinyin:'hùshi', english:'Nurse'},
{no:327, chinese:'花（形）', pinyin:'huā', english:'multicoloured; coloured; flowery'},
{no:328, chinese:'划', pinyin:'huá', english:'paddle; row'},
{no:329, chinese:'划', pinyin:'huà', english:'transfer; assign; differentiate'},
{no:330, chinese:'怀念', pinyin:'huáiniàn', english:'Miss'},
{no:331, chinese:'怀疑', pinyin:'huáiyí', english:'doubt'},
{no:332, chinese:'缓解', pinyin:'huǎnjiě', english:'relieve'},
{no:333, chinese:'黄瓜', pinyin:'huáng guā', english:'cucumber; cuke'},
{no:334, chinese:'黄金', pinyin:'huángjīn', english:'gold'},
{no:335, chinese:'回复', pinyin:'huí fù', english:'reply'},
{no:336, chinese:'汇', pinyin:'huì', english:'remit; converge; collection'},
{no:337, chinese:'汇报', pinyin:'huìbào', english:'report'},
{no:338, chinese:'汇率', pinyin:'huìlǜ', english:'exchange rate'},
{no:339, chinese:'婚礼', pinyin:'hūnlǐ', english:'wedding'},
{no:340, chinese:'火（形）', pinyin:'huǒ', english:'fiery; flaming; urgent'},
{no:341, chinese:'伙', pinyin:'huǒ', english:'partner; partnership'},
{no:342, chinese:'伙伴', pinyin:'huǒbàn', english:'Partner'},
{no:343, chinese:'或许', pinyin:'huòxǔ', english:'maybe; probably'},
{no:344, chinese:'货', pinyin:'huò', english:'goods; commodity; money'},
{no:345, chinese:'获', pinyin:'huò', english:'obtain; win; reap'},
{no:346, chinese:'获得', pinyin:'huòdé', english:'Get'},
{no:347, chinese:'获奖', pinyin:'huò jiǎng', english:'win a prize; receive an award'},
{no:348, chinese:'获取', pinyin:'huò qǔ', english:'gain; obtain'},
{no:349, chinese:'几乎', pinyin:'jīhū', english:'almost'},
{no:350, chinese:'机构', pinyin:'jīgòu', english:'mechanism'},
{no:351, chinese:'机遇', pinyin:'jīyù', english:'Opportunity'},
{no:352, chinese:'积累', pinyin:'jīlěi', english:'accumulation'},
{no:353, chinese:'激动', pinyin:'jīdòng', english:'Excited'},
{no:354, chinese:'激烈', pinyin:'jīliè', english:'fierce'},
{no:355, chinese:'及格', pinyin:'jígé', english:'pass'},
{no:356, chinese:'极', pinyin:'jí', english:'extremely'},
{no:357, chinese:'极其', pinyin:'jíqí', english:'extremely'},
{no:358, chinese:'即将', pinyin:'jíjiāng', english:'soon'},
{no:359, chinese:'急忙', pinyin:'jímáng', english:'Hastily'},
{no:360, chinese:'集合', pinyin:'jíhé', english:'aggregate'},
{no:361, chinese:'记载', pinyin:'jìzǎi', english:'Record'},
{no:362, chinese:'纪律', pinyin:'jìlǜ', english:'discipline'},
{no:363, chinese:'技巧', pinyin:'jìqiǎo', english:'Skill'},
{no:364, chinese:'系', pinyin:'xì', english:'department'},
{no:365, chinese:'季', pinyin:'jì', english:'season; period'},
{no:366, chinese:'季度', pinyin:'jìdù', english:'quarter (of a year)'},
{no:367, chinese:'季节', pinyin:'jìjié', english:'Season'},
{no:368, chinese:'既', pinyin:'jì', english:'already; since; as'},
{no:369, chinese:'既然', pinyin:'jìrán', english:'Since'},
{no:370, chinese:'寄', pinyin:'jì', english:'send'},
{no:371, chinese:'加班', pinyin:'jiābān', english:'overtime work'},
{no:372, chinese:'加入', pinyin:'jiā rù', english:'add; mix; join; become a member'},
{no:373, chinese:'加油站', pinyin:'jiāyóuzhàn', english:'Gas station'},
{no:374, chinese:'家务', pinyin:'jiāwù', english:'Housework'},
{no:375, chinese:'假如', pinyin:'jiǎrú', english:'If'},
{no:376, chinese:'坚固', pinyin:'jiāngù', english:'strong'},
{no:377, chinese:'检测', pinyin:'jiǎn cè', english:'detect; test'},
{no:378, chinese:'减', pinyin:'jiǎn', english:'subtract; reduce; decrease'},
{no:379, chinese:'减肥', pinyin:'jiǎnféi', english:'Reduce weight'},
{no:380, chinese:'减少', pinyin:'jiǎnshǎo', english:'reduce'},
{no:381, chinese:'简历', pinyin:'jiǎnlì', english:'resume'},
{no:382, chinese:'健身', pinyin:'jiànshēn', english:'workout'},
{no:383, chinese:'渐渐', pinyin:'jiàn jiàn', english:'gradually; step by step'},
{no:384, chinese:'江', pinyin:'jiāng', english:'river'},
{no:385, chinese:'讲究', pinyin:'jiǎngjiu', english:'Pay attention to, stress'},
{no:386, chinese:'讲座', pinyin:'jiǎngzuò', english:'Lecture'},
{no:387, chinese:'奖', pinyin:'jiǎng', english:'award; prize; reward'},
{no:388, chinese:'奖金', pinyin:'jiǎngjīn', english:'bonus'},
{no:389, chinese:'奖学金', pinyin:'jiǎng xué jīn', english:'scholarship; fellowship'},
{no:390, chinese:'降', pinyin:'jiàng', english:'fall; drop; descend; lower'},
{no:391, chinese:'降低', pinyin:'jiàngdī', english:'reduce'},
{no:392, chinese:'降价', pinyin:'jiàng jià', english:'cut price; reduce price'},
{no:393, chinese:'降落', pinyin:'jiàngluò', english:'land'},
{no:394, chinese:'降温', pinyin:'jiàng wēn', english:'lower the temperature'},
{no:395, chinese:'交换', pinyin:'jiāohuàn', english:'exchange'},
{no:396, chinese:'交际', pinyin:'jiāojì', english:'communication'},
{no:397, chinese:'教授', pinyin:'jiàoshòu', english:'professor'},
{no:398, chinese:'教训', pinyin:'jiàoxùn', english:'lesson'},
{no:399, chinese:'阶段', pinyin:'jiēduàn', english:'stage'},
{no:400, chinese:'街道', pinyin:'jiēdào', english:'Street'},
{no:401, chinese:'节省', pinyin:'jiéshěng', english:'save'},
{no:402, chinese:'结', pinyin:'jié', english:'bear; form; knit; knot'},
{no:403, chinese:'结构', pinyin:'jiégòu', english:'structure'},
{no:404, chinese:'结论', pinyin:'jiélùn', english:'conclusion'},
{no:405, chinese:'姐妹', pinyin:'jiě mèi', english:'sisters'},
{no:406, chinese:'解释', pinyin:'jiěshì', english:'explain'},
{no:407, chinese:'尽快', pinyin:'jǐnkuài', english:'as soon as possible'},
{no:408, chinese:'紧密', pinyin:'jǐn mì', english:'close; inseparable'},
{no:409, chinese:'尽力', pinyin:'jìnlì', english:'Try the best'},
{no:410, chinese:'进口', pinyin:'jìnkǒu', english:'Imported'},
{no:411, chinese:'近代', pinyin:'jìndài', english:'Modern'},
{no:412, chinese:'禁止', pinyin:'jìnzhǐ', english:'prohibit'},
{no:413, chinese:'经典', pinyin:'jīngdiǎn', english:'classics; scriptures'},
{no:414, chinese:'精力', pinyin:'jīnglì', english:'energy'},
{no:415, chinese:'竟然', pinyin:'jìngrán', english:'Unexpectedly'},
{no:416, chinese:'镜头', pinyin:'jìngtóu', english:'Camera lens'},
{no:417, chinese:'镜子', pinyin:'jìngzi', english:'Mirror'},
{no:418, chinese:'究竟', pinyin:'jiūjìng', english:'exactly'},
{no:419, chinese:'酒吧', pinyin:'jiǔbā', english:'Bar'},
{no:420, chinese:'居民', pinyin:'jūmín', english:'residents'},
{no:421, chinese:'居住', pinyin:'jūzhù', english:'live'},
{no:422, chinese:'局（名）', pinyin:'jú', english:'bureau; part; portion; gathering'},
{no:423, chinese:'巨大', pinyin:'jùdà', english:'huge'},
{no:424, chinese:'具备', pinyin:'jùbèi', english:'Have, possess'},
{no:425, chinese:'距离', pinyin:'jùlí', english:'distance'},
{no:426, chinese:'聚', pinyin:'jù', english:'assemble; gather; get together'},
{no:427, chinese:'聚会', pinyin:'jùhuì', english:'Party'},
{no:428, chinese:'卷', pinyin:'juǎn', english:'roll, curly, reel'},
{no:429, chinese:'卷', pinyin:'juàn', english:'volume; file'},
{no:430, chinese:'角色', pinyin:'juésè', english:'role'},
{no:431, chinese:'开花', pinyin:'kāi huā', english:'flower; bloom; blossom'},
{no:432, chinese:'开水', pinyin:'kāishuǐ', english:'Boiling water'},
{no:433, chinese:'看不起', pinyin:'kànbuqǐ', english:'Despise'},
{no:434, chinese:'看来', pinyin:'kàn lái', english:'it seems; it appears'},
{no:435, chinese:'看望', pinyin:'kànwàng', english:'visit'},
{no:436, chinese:'考察', pinyin:'kǎochá', english:'Investigate'},
{no:437, chinese:'考虑', pinyin:'kǎolǜ', english:'Consider'},
{no:438, chinese:'棵', pinyin:'kē', english:'Tree (measure word)'},
{no:439, chinese:'可见', pinyin:'kějiàn', english:'So'},
{no:440, chinese:'空间', pinyin:'kōngjiān', english:'space'},
{no:441, chinese:'空', pinyin:'kōng', english:'empty'},
{no:442, chinese:'口袋', pinyin:'kǒu dài', english:'pocket'},
{no:443, chinese:'口语', pinyin:'kǒu yǔ', english:'spoken language'},
{no:444, chinese:'苦', pinyin:'kǔ', english:'bitter'},
{no:445, chinese:'会计', pinyin:'kuàijì', english:'accountant'},
{no:446, chinese:'快递', pinyin:'kuài dì', english:'express delivery'},
{no:447, chinese:'宽', pinyin:'kuān', english:'wide'},
{no:448, chinese:'宽广', pinyin:'kuān guǎng', english:'broad; vast; extensive'},
{no:449, chinese:'矿泉水', pinyin:'kuàngquánshuǐ', english:'Mineral water'},
{no:450, chinese:'扩大', pinyin:'kuòdà', english:'Expand'},
{no:451, chinese:'扩展', pinyin:'kuò zhǎn', english:'expand; extend; spread'},
{no:452, chinese:'括号', pinyin:'kuò hào', english:'brackets; parentheses'},
{no:453, chinese:'垃圾', pinyin:'lā jī', english:'rubbish; garbage'},
{no:454, chinese:'拉开', pinyin:'lā kāi', english:'pull open; zip'},
{no:455, chinese:'辣', pinyin:'là', english:'hot, spicy'},
{no:456, chinese:'来不及', pinyin:'láibují', english:'There’s not enough time'},
{no:457, chinese:'来得及', pinyin:'láidejí', english:'In time'},
{no:458, chinese:'来源', pinyin:'láiyuán', english:'source'},
{no:459, chinese:'老公', pinyin:'lǎo gōng', english:'husband'},
{no:460, chinese:'老家', pinyin:'lǎo jiā', english:'hometown; home state'},
{no:461, chinese:'老婆', pinyin:'lǎopó', english:'wife'},
{no:462, chinese:'老实', pinyin:'lǎoshi', english:'honest'},
{no:463, chinese:'乐趣', pinyin:'lèqù', english:'pleasure'},
{no:464, chinese:'泪', pinyin:'lèi', english:'tear; teardrop'},
{no:465, chinese:'泪水', pinyin:'lèi shuǐ', english:'tear; teardrop'},
{no:466, chinese:'类型', pinyin:'lèixíng', english:'type'},
{no:467, chinese:'冷静', pinyin:'lěngjìng', english:'calm down'},
{no:468, chinese:'厘米', pinyin:'límǐ', english:'centimeter'},
{no:469, chinese:'离不开', pinyin:'lí bù kāi', english:'can’t do without'},
{no:470, chinese:'力气', pinyin:'lìqi', english:'Strength'},
{no:471, chinese:'历史', pinyin:'lìshǐ', english:'History'},
{no:472, chinese:'立即', pinyin:'lìjí', english:'immediately'},
{no:473, chinese:'利息', pinyin:'lìxī', english:'accrual; interest'},
{no:474, chinese:'利益', pinyin:'lìyì', english:'interest'},
{no:475, chinese:'俩', pinyin:'liǎ', english:'Two'},
{no:476, chinese:'良好', pinyin:'liánghǎo', english:'good'},
{no:477, chinese:'量', pinyin:'liáng', english:'measure; estimate; amount'},
{no:478, chinese:'粮食', pinyin:'liángshi', english:'foodstuff'},
{no:479, chinese:'两边', pinyin:'liǎng biān', english:'both sides'},
{no:480, chinese:'疗养', pinyin:'liáo yǎng', english:'recuperate; convalesce'},
{no:481, chinese:'了不起', pinyin:'liǎobuqǐ', english:'Amazing'},
{no:482, chinese:'了解', pinyin:'liǎojiě', english:'understand'},
{no:483, chinese:'列', pinyin:'liè', english:'arrange; line up; list'},
{no:484, chinese:'列车', pinyin:'lièchē', english:'train'},
{no:485, chinese:'列入', pinyin:'liè rù', english:'included in'},
{no:486, chinese:'列为', pinyin:'liè wéi', english:'be classified as'},
{no:487, chinese:'临时', pinyin:'línshí', english:'temporary'},
{no:488, chinese:'零食', pinyin:'língshí', english:'snacks'},
{no:489, chinese:'流传', pinyin:'liúchuán', english:'spread'},
{no:490, chinese:'楼梯', pinyin:'lóu tī', english:'stairs; staircase'},
{no:491, chinese:'陆地', pinyin:'lùdì', english:'land'},
{no:492, chinese:'陆续', pinyin:'lùxù', english:'One after another'},
{no:493, chinese:'录取', pinyin:'lùqǔ', english:'matriculate'},
{no:494, chinese:'律师', pinyin:'lǜshī', english:'Lawyer'},
{no:495, chinese:'轮', pinyin:'lún', english:'wheel; ring; take turns'},
{no:496, chinese:'轮船', pinyin:'lúnchuán', english:'Ship'},
{no:497, chinese:'轮椅', pinyin:'lún yǐ', english:'wheelchair'},
{no:498, chinese:'轮子', pinyin:'lún zi', english:'wheel'},
{no:499, chinese:'论文', pinyin:'lùnwén', english:'paper'},
{no:500, chinese:'落', pinyin:'luò', english:'fall; drop; go down; set; decline'},

{no:1000, chinese:'做梦', pinyin:'zuò mèng', english:'dream'}
];

/* ---------- tabulator ---------- */
new Tabulator('#hsk4-table', {
  data: vocab,
  layout: 'fitColumns',
  resizableColumns: false,
  columns: [
    {title:'#', field:'no', width:60},
    {title:'Chinese', field:'chinese'},
    {title:'Pinyin', field:'pinyin'},
    {title:'English', field:'english'},
  ]
});