/* ---------- 1000 entires ---------- */
const vocab = [
{no:1,  chinese:'阿姨', pinyin:'āyí', english:'aunt'},
{no:2,  chinese:'啊', pinyin:'a', english:'ah'},
{no:3,  chinese:'矮', pinyin:'ǎi', english:'short'},
{no:4,  chinese:'矮小', pinyin:'ǎi xiǎo', english:'short and small'},
{no:5,  chinese:'爱国', pinyin:'ài guó', english:'love one’s country'},
{no:6,  chinese:'爱护', pinyin:'àihù', english:'Care'},
{no:7,  chinese:'安', pinyin:'ān', english:'quiet; safe; secure'},
{no:8,  chinese:'安置', pinyin:'ānzhì', english:'put; arrange for'},
{no:9,  chinese:'按时', pinyin:'ànshí', english:'on time'},
{no:10, chinese:'暗', pinyin:'àn', english:'dark'},
{no:11, chinese:'暗示', pinyin:'ànshì', english:'suggest secretly'},
{no:12, chinese:'巴士', pinyin:'bā shì', english:'bus'},
{no:13, chinese:'百货', pinyin:'bǎi huò', english:'department store'},
{no:14, chinese:'摆', pinyin:'bǎi', english:'pendulum'},
{no:15, chinese:'摆动', pinyin:'bǎi dòng', english:'swing; sway'},
{no:16, chinese:'摆脱', pinyin:'bǎituō', english:'cast off'},
{no:17, chinese:'败', pinyin:'bài', english:'defeat; fail'},
{no:18, chinese:'办事', pinyin:'bàn shì', english:'handle affairs'},
{no:19, chinese:'包裹', pinyin:'bāoguǒ', english:'package'},
{no:20, chinese:'包含', pinyin:'bāohán', english:'Contain'},
{no:21, chinese:'包括', pinyin:'bāokuò', english:'Include'},
{no:22, chinese:'薄', pinyin:'báo', english:'thin'},
{no:23, chinese:'宝', pinyin:'bǎo', english:'treasure'},
{no:24, chinese:'宝宝', pinyin:'bǎo bao', english:'baby'},
{no:25, chinese:'宝贝', pinyin:'bǎobèi', english:'baby'},
{no:26, chinese:'宝贵', pinyin:'bǎoguì', english:'valuable'},
{no:27, chinese:'宝石', pinyin:'bǎo shí', english:'gemstone'},
{no:28, chinese:'保密', pinyin:'bǎomì', english:'secrecy'},
{no:29, chinese:'保守', pinyin:'bǎoshǒu', english:'Conservative'},
{no:30, chinese:'抱', pinyin:'bào', english:'Hold, hug'},
{no:31, chinese:'背景', pinyin:'bèijǐng', english:'background'},
{no:32, chinese:'倍', pinyin:'bèi', english:'times'},
{no:33, chinese:'被迫', pinyin:'bèi pò', english:'be compelled'},
{no:34, chinese:'本科', pinyin:'běnkē', english:'Undergraduate'},
{no:35, chinese:'笨', pinyin:'bèn', english:'stupid'},
{no:36, chinese:'比分', pinyin:'bǐ fēn', english:'score'},
{no:37, chinese:'毕业', pinyin:'bìyè', english:'graduation'},
{no:38, chinese:'毕业生', pinyin:'bì yè shēng', english:'graduate'},
{no:39, chinese:'避', pinyin:'bì', english:'avoid'},
{no:40, chinese:'避免', pinyin:'bìmiǎn', english:'avoid'},
{no:41, chinese:'编', pinyin:'biān', english:'invent; edit'},
{no:42, chinese:'辩论', pinyin:'biànlùn', english:'Debate'},
{no:43, chinese:'标志', pinyin:'biāozhì', english:'sign'},
{no:44, chinese:'表情', pinyin:'biǎoqíng', english:'Expression'},
{no:45, chinese:'表扬', pinyin:'biǎoyáng', english:'Praise'},
{no:46, chinese:'别（动）', pinyin:'bié', english:'do not; leave'},
{no:47, chinese:'冰', pinyin:'bīng', english:'ice'},
{no:48, chinese:'冰箱', pinyin:'bīngxiāng', english:'Refrigerator'},
{no:49, chinese:'冰雪', pinyin:'bīng xuě', english:'ice and snow'},
{no:50, chinese:'兵', pinyin:'bīng', english:'soldier'},
{no:51, chinese:'并（动）', pinyin:'bìng', english:'combine'},
{no:52, chinese:'不要紧', pinyin:'búyàojǐn', english:'Never mind'},
{no:53, chinese:'不在乎', pinyin:'bú zài hū', english:'not care'},
{no:54, chinese:'不管', pinyin:'bùguǎn', english:'no matter'},
{no:55, chinese:'不然', pinyin:'bùrán', english:'otherwise'},
{no:56, chinese:'布置', pinyin:'bùzhì', english:'Arrangement'},
{no:57, chinese:'步行', pinyin:'bù xíng', english:'walk'},
{no:58, chinese:'擦', pinyin:'cā', english:'wipe'},
{no:59, chinese:'才（名）', pinyin:'cái', english:'talent'},
{no:60, chinese:'材料', pinyin:'cáiliào', english:'Materials'},
{no:61, chinese:'财产', pinyin:'cáichǎn', english:'property'},
{no:62, chinese:'财富', pinyin:'cáifù', english:'wealth'},
{no:63, chinese:'采访', pinyin:'cǎifǎng', english:'interview'},
{no:64, chinese:'参考', pinyin:'cānkǎo', english:'Reference'},
{no:65, chinese:'参与', pinyin:'cānyù', english:'participate'},
{no:66, chinese:'操场', pinyin:'cāochǎng', english:'Playground'},
{no:67, chinese:'操作', pinyin:'cāozuò', english:'operation'},
{no:68, chinese:'测', pinyin:'cè', english:'measure'},
{no:69, chinese:'测量', pinyin:'cèliáng', english:'measure'},
{no:70, chinese:'测试', pinyin:'cè shì', english:'test'},
{no:71, chinese:'曾', pinyin:'céng', english:'once'},
{no:72, chinese:'茶叶', pinyin:'chá yè', english:'tea-leaves'},
{no:73, chinese:'产品', pinyin:'chǎnpǐn', english:'product'},
{no:74, chinese:'长途', pinyin:'chángtú', english:'Long-distance'},
{no:75, chinese:'常识', pinyin:'chángshí', english:'common sense'},
{no:76, chinese:'唱片', pinyin:'chàng piàn', english:'record'},
{no:77, chinese:'抄', pinyin:'chāo', english:'copy'},
{no:78, chinese:'抄写', pinyin:'chāo xiě', english:'transcribe'},
{no:79, chinese:'潮', pinyin:'cháo', english:'tide'},
{no:80, chinese:'潮流', pinyin:'cháoliú', english:'Trend'},
{no:81, chinese:'潮湿', pinyin:'cháoshī', english:'damp'},
{no:82, chinese:'彻底', pinyin:'chèdǐ', english:'thorough'},
{no:83, chinese:'沉', pinyin:'chén', english:'sink'},
{no:84, chinese:'沉默', pinyin:'chénmò', english:'silent'},
{no:85, chinese:'沉重', pinyin:'chénzhòng', english:'heavy'},
{no:86, chinese:'称赞', pinyin:'chēngzàn', english:'Praise'},
{no:87, chinese:'成人', pinyin:'chéngrén', english:'adult'},
{no:88, chinese:'诚实', pinyin:'chéngshí', english:'honest'},
{no:89, chinese:'诚信', pinyin:'chéng xìn', english:'integrity'},
{no:90, chinese:'承担', pinyin:'chéngdān', english:'bear'},
{no:91, chinese:'承认', pinyin:'chéngrèn', english:'Admit'},
{no:92, chinese:'承受', pinyin:'chéngshòu', english:'bear'},
{no:93, chinese:'程序', pinyin:'chéngxù', english:'program'},
{no:94, chinese:'吃惊', pinyin:'chījīng', english:'Be amazed'},
{no:95, chinese:'迟到', pinyin:'chídào', english:'Late'},
{no:96, chinese:'尺', pinyin:'chǐ', english:'ruler'},
{no:97, chinese:'尺寸', pinyin:'chǐ cùn', english:'size'},
{no:98, chinese:'尺子', pinyin:'chǐzi', english:'Ruler'},
{no:99, chinese:'冲', pinyin:'chōng', english:'punching'},
{no:100, chinese:'充电', pinyin:'chōng diàn', english:'recharge'},
/* …… 101-1000 omitted for brevity …… */
{no:1000, chinese:'做梦', pinyin:'zuò mèng', english:'dream'}
];

/* ---------- tabulator ---------- */
new Tabulator('#hsk4-table', {
  data: vocab,
  layout: 'fitColumns',
  resizableColumns: false,
  columns: [
    {title:'#', field:'no', width:60},
    {title:'Chinese', field:'chinese'},
    {title:'Pinyin', field:'pinyin'},
    {title:'English', field:'english'},
  ]
});